/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFINDSEP_H
#define _MOCKFINDSEP_H

#include "findsep.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockfindsep_Init(void);
void Mockfindsep_Destroy(void);
void Mockfindsep_Verify(void);




#define findsep_silence_IgnoreAndReturn(cmock_retval) findsep_silence_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void findsep_silence_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define findsep_silence_ExpectAndReturn(mpgbuf, mpgsize, len_to_sw, searchwindow, silence_length, padding1, padding2, pos1, pos2, cmock_retval) findsep_silence_CMockExpectAndReturn(__LINE__, mpgbuf, mpgsize, len_to_sw, searchwindow, silence_length, padding1, padding2, pos1, pos2, cmock_retval)
void findsep_silence_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2, error_code cmock_to_return);
typedef error_code (* CMOCK_findsep_silence_CALLBACK)(const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2, int cmock_num_calls);
void findsep_silence_StubWithCallback(CMOCK_findsep_silence_CALLBACK Callback);
#define findsep_silence_2_IgnoreAndReturn(cmock_retval) findsep_silence_2_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void findsep_silence_2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define findsep_silence_2_ExpectAndReturn(mpgbuf, mpgsize, len_to_sw, searchwindow, silence_length, padding1, padding2, pos1, pos2, cmock_retval) findsep_silence_2_CMockExpectAndReturn(__LINE__, mpgbuf, mpgsize, len_to_sw, searchwindow, silence_length, padding1, padding2, pos1, pos2, cmock_retval)
void findsep_silence_2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2, error_code cmock_to_return);
typedef error_code (* CMOCK_findsep_silence_2_CALLBACK)(const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2, int cmock_num_calls);
void findsep_silence_2_StubWithCallback(CMOCK_findsep_silence_2_CALLBACK Callback);
#define find_bitrate_IgnoreAndReturn(cmock_retval) find_bitrate_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void find_bitrate_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define find_bitrate_ExpectAndReturn(bitrate, mpgbuf, mpgsize, cmock_retval) find_bitrate_CMockExpectAndReturn(__LINE__, bitrate, mpgbuf, mpgsize, cmock_retval)
void find_bitrate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned long* bitrate, const char* mpgbuf, long mpgsize, error_code cmock_to_return);
typedef error_code (* CMOCK_find_bitrate_CALLBACK)(unsigned long* bitrate, const char* mpgbuf, long mpgsize, int cmock_num_calls);
void find_bitrate_StubWithCallback(CMOCK_find_bitrate_CALLBACK Callback);

#endif
