/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUTF8_H
#define _MOCKUTF8_H

#include "utf8.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockutf8_Init(void);
void Mockutf8_Destroy(void);
void Mockutf8_Verify(void);




#define convert_set_charset_Ignore() convert_set_charset_CMockIgnore()
void convert_set_charset_CMockIgnore(void);
#define convert_set_charset_Expect(charset) convert_set_charset_CMockExpect(__LINE__, charset)
void convert_set_charset_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* charset);
typedef void (* CMOCK_convert_set_charset_CALLBACK)(const char* charset, int cmock_num_calls);
void convert_set_charset_StubWithCallback(CMOCK_convert_set_charset_CALLBACK Callback);
#define utf8_encode_IgnoreAndReturn(cmock_retval) utf8_encode_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void utf8_encode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define utf8_encode_ExpectAndReturn(from, to, cmock_retval) utf8_encode_CMockExpectAndReturn(__LINE__, from, to, cmock_retval)
void utf8_encode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* from, char** to, int cmock_to_return);
typedef int (* CMOCK_utf8_encode_CALLBACK)(const char* from, char** to, int cmock_num_calls);
void utf8_encode_StubWithCallback(CMOCK_utf8_encode_CALLBACK Callback);
#define utf8_decode_IgnoreAndReturn(cmock_retval) utf8_decode_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void utf8_decode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define utf8_decode_ExpectAndReturn(from, to, cmock_retval) utf8_decode_CMockExpectAndReturn(__LINE__, from, to, cmock_retval)
void utf8_decode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* from, char** to, int cmock_to_return);
typedef int (* CMOCK_utf8_decode_CALLBACK)(const char* from, char** to, int cmock_num_calls);
void utf8_decode_StubWithCallback(CMOCK_utf8_decode_CALLBACK Callback);

#endif
