/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKEXTERNAL_H
#define _MOCKEXTERNAL_H

#include "external.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockexternal_Init(void);
void Mockexternal_Destroy(void);
void Mockexternal_Verify(void);




#define spawn_external_IgnoreAndReturn(cmock_retval) spawn_external_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void spawn_external_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, External_Process* cmock_to_return);
#define spawn_external_ExpectAndReturn(cmd, cmock_retval) spawn_external_CMockExpectAndReturn(__LINE__, cmd, cmock_retval)
void spawn_external_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* cmd, External_Process* cmock_to_return);
typedef External_Process* (* CMOCK_spawn_external_CALLBACK)(char* cmd, int cmock_num_calls);
void spawn_external_StubWithCallback(CMOCK_spawn_external_CALLBACK Callback);
#define read_external_IgnoreAndReturn(cmock_retval) read_external_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void read_external_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define read_external_ExpectAndReturn(rmi, ep, ti, cmock_retval) read_external_CMockExpectAndReturn(__LINE__, rmi, ep, ti, cmock_retval)
void read_external_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, External_Process* ep, TRACK_INFO* ti, int cmock_to_return);
typedef int (* CMOCK_read_external_CALLBACK)(RIP_MANAGER_INFO* rmi, External_Process* ep, TRACK_INFO* ti, int cmock_num_calls);
void read_external_StubWithCallback(CMOCK_read_external_CALLBACK Callback);
#define close_external_Ignore() close_external_CMockIgnore()
void close_external_CMockIgnore(void);
#define close_external_Expect(epp) close_external_CMockExpect(__LINE__, epp)
void close_external_CMockExpect(UNITY_LINE_TYPE cmock_line, External_Process** epp);
typedef void (* CMOCK_close_external_CALLBACK)(External_Process** epp, int cmock_num_calls);
void close_external_StubWithCallback(CMOCK_close_external_CALLBACK Callback);

#endif
