/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKRELAYLIB_H
#define _MOCKRELAYLIB_H

#include "relaylib.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockrelaylib_Init(void);
void Mockrelaylib_Destroy(void);
void Mockrelaylib_Verify(void);




#define relaylib_set_response_header_IgnoreAndReturn(cmock_retval) relaylib_set_response_header_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void relaylib_set_response_header_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define relaylib_set_response_header_ExpectAndReturn(http_header, cmock_retval) relaylib_set_response_header_CMockExpectAndReturn(__LINE__, http_header, cmock_retval)
void relaylib_set_response_header_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* http_header, error_code cmock_to_return);
typedef error_code (* CMOCK_relaylib_set_response_header_CALLBACK)(char* http_header, int cmock_num_calls);
void relaylib_set_response_header_StubWithCallback(CMOCK_relaylib_set_response_header_CALLBACK Callback);
#define relaylib_start_IgnoreAndReturn(cmock_retval) relaylib_start_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void relaylib_start_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define relaylib_start_ExpectAndReturn(rmi, search_ports, relay_port, max_port, port_used, if_name, max_connections, relay_ip, have_metadata, cmock_retval) relaylib_start_CMockExpectAndReturn(__LINE__, rmi, search_ports, relay_port, max_port, port_used, if_name, max_connections, relay_ip, have_metadata, cmock_retval)
void relaylib_start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, BOOL search_ports, u_short relay_port, u_short max_port, u_short* port_used, char* if_name, int max_connections, char* relay_ip, int have_metadata, error_code cmock_to_return);
typedef error_code (* CMOCK_relaylib_start_CALLBACK)(RIP_MANAGER_INFO* rmi, BOOL search_ports, u_short relay_port, u_short max_port, u_short* port_used, char* if_name, int max_connections, char* relay_ip, int have_metadata, int cmock_num_calls);
void relaylib_start_StubWithCallback(CMOCK_relaylib_start_CALLBACK Callback);
#define relaylib_send_IgnoreAndReturn(cmock_retval) relaylib_send_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void relaylib_send_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define relaylib_send_ExpectAndReturn(data, len, accept_new, is_meta, cmock_retval) relaylib_send_CMockExpectAndReturn(__LINE__, data, len, accept_new, is_meta, cmock_retval)
void relaylib_send_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* data, int len, int accept_new, int is_meta, error_code cmock_to_return);
typedef error_code (* CMOCK_relaylib_send_CALLBACK)(char* data, int len, int accept_new, int is_meta, int cmock_num_calls);
void relaylib_send_StubWithCallback(CMOCK_relaylib_send_CALLBACK Callback);
#define relaylib_stop_Ignore() relaylib_stop_CMockIgnore()
void relaylib_stop_CMockIgnore(void);
#define relaylib_stop_Expect(rmi) relaylib_stop_CMockExpect(__LINE__, rmi)
void relaylib_stop_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi);
typedef void (* CMOCK_relaylib_stop_CALLBACK)(RIP_MANAGER_INFO* rmi, int cmock_num_calls);
void relaylib_stop_StubWithCallback(CMOCK_relaylib_stop_CALLBACK Callback);
#define relaylib_isrunning_IgnoreAndReturn(cmock_retval) relaylib_isrunning_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void relaylib_isrunning_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, BOOL cmock_to_return);
#define relaylib_isrunning_ExpectAndReturn(cmock_retval) relaylib_isrunning_CMockExpectAndReturn(__LINE__, cmock_retval)
void relaylib_isrunning_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BOOL cmock_to_return);
typedef BOOL (* CMOCK_relaylib_isrunning_CALLBACK)(int cmock_num_calls);
void relaylib_isrunning_StubWithCallback(CMOCK_relaylib_isrunning_CALLBACK Callback);
#define relaylib_send_meta_data_IgnoreAndReturn(cmock_retval) relaylib_send_meta_data_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void relaylib_send_meta_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define relaylib_send_meta_data_ExpectAndReturn(track, cmock_retval) relaylib_send_meta_data_CMockExpectAndReturn(__LINE__, track, cmock_retval)
void relaylib_send_meta_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* track, error_code cmock_to_return);
typedef error_code (* CMOCK_relaylib_send_meta_data_CALLBACK)(char* track, int cmock_num_calls);
void relaylib_send_meta_data_StubWithCallback(CMOCK_relaylib_send_meta_data_CALLBACK Callback);
#define relaylib_disconnect_Ignore() relaylib_disconnect_CMockIgnore()
void relaylib_disconnect_CMockIgnore(void);
#define relaylib_disconnect_Expect(rmi, prev, ptr) relaylib_disconnect_CMockExpect(__LINE__, rmi, prev, ptr)
void relaylib_disconnect_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, RELAY_LIST* prev, RELAY_LIST* ptr);
typedef void (* CMOCK_relaylib_disconnect_CALLBACK)(RIP_MANAGER_INFO* rmi, RELAY_LIST* prev, RELAY_LIST* ptr, int cmock_num_calls);
void relaylib_disconnect_StubWithCallback(CMOCK_relaylib_disconnect_CALLBACK Callback);

#endif
