/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPREFS_H
#define _MOCKPREFS_H

#include "prefs.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockprefs_Init(void);
void Mockprefs_Destroy(void);
void Mockprefs_Verify(void);




#define prefs_load_IgnoreAndReturn(cmock_retval) prefs_load_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void prefs_load_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define prefs_load_ExpectAndReturn(cmock_retval) prefs_load_CMockExpectAndReturn(__LINE__, cmock_retval)
void prefs_load_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
typedef int (* CMOCK_prefs_load_CALLBACK)(int cmock_num_calls);
void prefs_load_StubWithCallback(CMOCK_prefs_load_CALLBACK Callback);
#define prefs_save_Ignore() prefs_save_CMockIgnore()
void prefs_save_CMockIgnore(void);
#define prefs_save_Expect() prefs_save_CMockExpect(__LINE__)
void prefs_save_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_prefs_save_CALLBACK)(int cmock_num_calls);
void prefs_save_StubWithCallback(CMOCK_prefs_save_CALLBACK Callback);
#define prefs_get_global_prefs_Ignore() prefs_get_global_prefs_CMockIgnore()
void prefs_get_global_prefs_CMockIgnore(void);
#define prefs_get_global_prefs_Expect(global_prefs) prefs_get_global_prefs_CMockExpect(__LINE__, global_prefs)
void prefs_get_global_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, GLOBAL_PREFS* global_prefs);
typedef void (* CMOCK_prefs_get_global_prefs_CALLBACK)(GLOBAL_PREFS* global_prefs, int cmock_num_calls);
void prefs_get_global_prefs_StubWithCallback(CMOCK_prefs_get_global_prefs_CALLBACK Callback);
#define prefs_set_global_prefs_Ignore() prefs_set_global_prefs_CMockIgnore()
void prefs_set_global_prefs_CMockIgnore(void);
#define prefs_set_global_prefs_Expect(global_prefs) prefs_set_global_prefs_CMockExpect(__LINE__, global_prefs)
void prefs_set_global_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, GLOBAL_PREFS* global_prefs);
typedef void (* CMOCK_prefs_set_global_prefs_CALLBACK)(GLOBAL_PREFS* global_prefs, int cmock_num_calls);
void prefs_set_global_prefs_StubWithCallback(CMOCK_prefs_set_global_prefs_CALLBACK Callback);
#define prefs_get_stream_prefs_Ignore() prefs_get_stream_prefs_CMockIgnore()
void prefs_get_stream_prefs_CMockIgnore(void);
#define prefs_get_stream_prefs_Expect(prefs, label) prefs_get_stream_prefs_CMockExpect(__LINE__, prefs, label)
void prefs_get_stream_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, STREAM_PREFS* prefs, char* label);
typedef void (* CMOCK_prefs_get_stream_prefs_CALLBACK)(STREAM_PREFS* prefs, char* label, int cmock_num_calls);
void prefs_get_stream_prefs_StubWithCallback(CMOCK_prefs_get_stream_prefs_CALLBACK Callback);
#define prefs_set_stream_prefs_Ignore() prefs_set_stream_prefs_CMockIgnore()
void prefs_set_stream_prefs_CMockIgnore(void);
#define prefs_set_stream_prefs_Expect(prefs, label) prefs_set_stream_prefs_CMockExpect(__LINE__, prefs, label)
void prefs_set_stream_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, STREAM_PREFS* prefs, char* label);
typedef void (* CMOCK_prefs_set_stream_prefs_CALLBACK)(STREAM_PREFS* prefs, char* label, int cmock_num_calls);
void prefs_set_stream_prefs_StubWithCallback(CMOCK_prefs_set_stream_prefs_CALLBACK Callback);
#define prefs_get_wstreamripper_prefs_Ignore() prefs_get_wstreamripper_prefs_CMockIgnore()
void prefs_get_wstreamripper_prefs_CMockIgnore(void);
#define prefs_get_wstreamripper_prefs_Expect(wsr_prefs) prefs_get_wstreamripper_prefs_CMockExpect(__LINE__, wsr_prefs)
void prefs_get_wstreamripper_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, WSTREAMRIPPER_PREFS* wsr_prefs);
typedef void (* CMOCK_prefs_get_wstreamripper_prefs_CALLBACK)(WSTREAMRIPPER_PREFS* wsr_prefs, int cmock_num_calls);
void prefs_get_wstreamripper_prefs_StubWithCallback(CMOCK_prefs_get_wstreamripper_prefs_CALLBACK Callback);
#define prefs_set_wstreamripper_prefs_Ignore() prefs_set_wstreamripper_prefs_CMockIgnore()
void prefs_set_wstreamripper_prefs_CMockIgnore(void);
#define prefs_set_wstreamripper_prefs_Expect(wsr_prefs) prefs_set_wstreamripper_prefs_CMockExpect(__LINE__, wsr_prefs)
void prefs_set_wstreamripper_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, WSTREAMRIPPER_PREFS* wsr_prefs);
typedef void (* CMOCK_prefs_set_wstreamripper_prefs_CALLBACK)(WSTREAMRIPPER_PREFS* wsr_prefs, int cmock_num_calls);
void prefs_set_wstreamripper_prefs_StubWithCallback(CMOCK_prefs_set_wstreamripper_prefs_CALLBACK Callback);
#define prefs_is_https_IgnoreAndReturn(cmock_retval) prefs_is_https_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void prefs_is_https_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define prefs_is_https_ExpectAndReturn(global_prefs, cmock_retval) prefs_is_https_CMockExpectAndReturn(__LINE__, global_prefs, cmock_retval)
void prefs_is_https_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GLOBAL_PREFS* global_prefs, bool cmock_to_return);
typedef bool (* CMOCK_prefs_is_https_CALLBACK)(GLOBAL_PREFS* global_prefs, int cmock_num_calls);
void prefs_is_https_StubWithCallback(CMOCK_prefs_is_https_CALLBACK Callback);
#define debug_stream_prefs_Ignore() debug_stream_prefs_CMockIgnore()
void debug_stream_prefs_CMockIgnore(void);
#define debug_stream_prefs_Expect(prefs) debug_stream_prefs_CMockExpect(__LINE__, prefs)
void debug_stream_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, STREAM_PREFS* prefs);
typedef void (* CMOCK_debug_stream_prefs_CALLBACK)(STREAM_PREFS* prefs, int cmock_num_calls);
void debug_stream_prefs_StubWithCallback(CMOCK_debug_stream_prefs_CALLBACK Callback);

#endif
