/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCHARSET_H
#define _MOCKCHARSET_H

#include "charset.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockcharset_Init(void);
void Mockcharset_Destroy(void);
void Mockcharset_Verify(void);




#define utf8_mbtowc_IgnoreAndReturn(cmock_retval) utf8_mbtowc_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void utf8_mbtowc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define utf8_mbtowc_ExpectAndReturn(pwc, s, n, cmock_retval) utf8_mbtowc_CMockExpectAndReturn(__LINE__, pwc, s, n, cmock_retval)
void utf8_mbtowc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* pwc, const char* s, size_t n, int cmock_to_return);
typedef int (* CMOCK_utf8_mbtowc_CALLBACK)(int* pwc, const char* s, size_t n, int cmock_num_calls);
void utf8_mbtowc_StubWithCallback(CMOCK_utf8_mbtowc_CALLBACK Callback);
#define utf8_wctomb_IgnoreAndReturn(cmock_retval) utf8_wctomb_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void utf8_wctomb_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define utf8_wctomb_ExpectAndReturn(s, wc, cmock_retval) utf8_wctomb_CMockExpectAndReturn(__LINE__, s, wc, cmock_retval)
void utf8_wctomb_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* s, int wc, int cmock_to_return);
typedef int (* CMOCK_utf8_wctomb_CALLBACK)(char* s, int wc, int cmock_num_calls);
void utf8_wctomb_StubWithCallback(CMOCK_utf8_wctomb_CALLBACK Callback);
#define charset_find_IgnoreAndReturn(cmock_retval) charset_find_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void charset_find_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, struct charset* cmock_to_return);
#define charset_find_ExpectAndReturn(code, cmock_retval) charset_find_CMockExpectAndReturn(__LINE__, code, cmock_retval)
void charset_find_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* code, struct charset* cmock_to_return);
typedef struct charset* (* CMOCK_charset_find_CALLBACK)(const char* code, int cmock_num_calls);
void charset_find_StubWithCallback(CMOCK_charset_find_CALLBACK Callback);
#define charset_mbtowc_IgnoreAndReturn(cmock_retval) charset_mbtowc_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void charset_mbtowc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define charset_mbtowc_ExpectAndReturn(charset, pwc, s, n, cmock_retval) charset_mbtowc_CMockExpectAndReturn(__LINE__, charset, pwc, s, n, cmock_retval)
void charset_mbtowc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct charset* charset, int* pwc, const char* s, size_t n, int cmock_to_return);
typedef int (* CMOCK_charset_mbtowc_CALLBACK)(struct charset* charset, int* pwc, const char* s, size_t n, int cmock_num_calls);
void charset_mbtowc_StubWithCallback(CMOCK_charset_mbtowc_CALLBACK Callback);
#define charset_wctomb_IgnoreAndReturn(cmock_retval) charset_wctomb_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void charset_wctomb_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define charset_wctomb_ExpectAndReturn(charset, s, wc, cmock_retval) charset_wctomb_CMockExpectAndReturn(__LINE__, charset, s, wc, cmock_retval)
void charset_wctomb_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct charset* charset, char* s, int wc, int cmock_to_return);
typedef int (* CMOCK_charset_wctomb_CALLBACK)(struct charset* charset, char* s, int wc, int cmock_num_calls);
void charset_wctomb_StubWithCallback(CMOCK_charset_wctomb_CALLBACK Callback);
#define charset_max_IgnoreAndReturn(cmock_retval) charset_max_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void charset_max_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define charset_max_ExpectAndReturn(charset, cmock_retval) charset_max_CMockExpectAndReturn(__LINE__, charset, cmock_retval)
void charset_max_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct charset* charset, int cmock_to_return);
typedef int (* CMOCK_charset_max_CALLBACK)(struct charset* charset, int cmock_num_calls);
void charset_max_StubWithCallback(CMOCK_charset_max_CALLBACK Callback);
#define charset_convert_IgnoreAndReturn(cmock_retval) charset_convert_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void charset_convert_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define charset_convert_ExpectAndReturn(fromcode, tocode, from, fromlen, to, tolen, cmock_retval) charset_convert_CMockExpectAndReturn(__LINE__, fromcode, tocode, from, fromlen, to, tolen, cmock_retval)
void charset_convert_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* fromcode, const char* tocode, const char* from, size_t fromlen, char** to, size_t* tolen, int cmock_to_return);
typedef int (* CMOCK_charset_convert_CALLBACK)(const char* fromcode, const char* tocode, const char* from, size_t fromlen, char** to, size_t* tolen, int cmock_num_calls);
void charset_convert_StubWithCallback(CMOCK_charset_convert_CALLBACK Callback);

#endif
