/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockexternal.h"

typedef struct _CMOCK_spawn_external_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  External_Process* ReturnVal;
  char* Expected_cmd;

} CMOCK_spawn_external_CALL_INSTANCE;

typedef struct _CMOCK_read_external_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  External_Process* Expected_ep;
  TRACK_INFO* Expected_ti;

} CMOCK_read_external_CALL_INSTANCE;

typedef struct _CMOCK_close_external_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  External_Process** Expected_epp;

} CMOCK_close_external_CALL_INSTANCE;

static struct MockexternalInstance
{
  int spawn_external_IgnoreBool;
  External_Process* spawn_external_FinalReturn;
  CMOCK_spawn_external_CALLBACK spawn_external_CallbackFunctionPointer;
  int spawn_external_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE spawn_external_CallInstance;
  int read_external_IgnoreBool;
  int read_external_FinalReturn;
  CMOCK_read_external_CALLBACK read_external_CallbackFunctionPointer;
  int read_external_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE read_external_CallInstance;
  int close_external_IgnoreBool;
  CMOCK_close_external_CALLBACK close_external_CallbackFunctionPointer;
  int close_external_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE close_external_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockexternal_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.spawn_external_IgnoreBool)
    Mock.spawn_external_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.spawn_external_CallInstance, cmock_line, "Function 'spawn_external' called less times than expected.");
  if (Mock.spawn_external_CallbackFunctionPointer != NULL)
    Mock.spawn_external_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.read_external_IgnoreBool)
    Mock.read_external_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.read_external_CallInstance, cmock_line, "Function 'read_external' called less times than expected.");
  if (Mock.read_external_CallbackFunctionPointer != NULL)
    Mock.read_external_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.close_external_IgnoreBool)
    Mock.close_external_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.close_external_CallInstance, cmock_line, "Function 'close_external' called less times than expected.");
  if (Mock.close_external_CallbackFunctionPointer != NULL)
    Mock.close_external_CallInstance = CMOCK_GUTS_NONE;
}

void Mockexternal_Init(void)
{
  Mockexternal_Destroy();
}

void Mockexternal_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.spawn_external_CallbackFunctionPointer = NULL;
  Mock.spawn_external_CallbackCalls = 0;
  Mock.read_external_CallbackFunctionPointer = NULL;
  Mock.read_external_CallbackCalls = 0;
  Mock.close_external_CallbackFunctionPointer = NULL;
  Mock.close_external_CallbackCalls = 0;
}

External_Process* spawn_external(char* cmd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spawn_external_CALL_INSTANCE* cmock_call_instance = (CMOCK_spawn_external_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spawn_external_CallInstance);
  Mock.spawn_external_CallInstance = CMock_Guts_MemNext(Mock.spawn_external_CallInstance);
  if (Mock.spawn_external_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.spawn_external_FinalReturn;
    Mock.spawn_external_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.spawn_external_CallbackFunctionPointer != NULL)
  {
    return Mock.spawn_external_CallbackFunctionPointer(cmd, Mock.spawn_external_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'spawn_external' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_cmd, cmd, cmock_line, "Function 'spawn_external' called with unexpected value for argument 'cmd'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spawn_external(CMOCK_spawn_external_CALL_INSTANCE* cmock_call_instance, char* cmd)
{
  cmock_call_instance->Expected_cmd = cmd;
}

void spawn_external_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, External_Process* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spawn_external_CALL_INSTANCE));
  CMOCK_spawn_external_CALL_INSTANCE* cmock_call_instance = (CMOCK_spawn_external_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spawn_external_CallInstance = CMock_Guts_MemChain(Mock.spawn_external_CallInstance, cmock_guts_index);
  Mock.spawn_external_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.spawn_external_IgnoreBool = (int)1;
}

void spawn_external_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* cmd, External_Process* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spawn_external_CALL_INSTANCE));
  CMOCK_spawn_external_CALL_INSTANCE* cmock_call_instance = (CMOCK_spawn_external_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spawn_external_CallInstance = CMock_Guts_MemChain(Mock.spawn_external_CallInstance, cmock_guts_index);
  Mock.spawn_external_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spawn_external(cmock_call_instance, cmd);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void spawn_external_StubWithCallback(CMOCK_spawn_external_CALLBACK Callback)
{
  Mock.spawn_external_CallbackFunctionPointer = Callback;
}

int read_external(RIP_MANAGER_INFO* rmi, External_Process* ep, TRACK_INFO* ti)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_read_external_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_external_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.read_external_CallInstance);
  Mock.read_external_CallInstance = CMock_Guts_MemNext(Mock.read_external_CallInstance);
  if (Mock.read_external_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.read_external_FinalReturn;
    Mock.read_external_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.read_external_CallbackFunctionPointer != NULL)
  {
    return Mock.read_external_CallbackFunctionPointer(rmi, ep, ti, Mock.read_external_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'read_external' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'read_external' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ep), (void*)(ep), sizeof(External_Process), cmock_line, "Function 'read_external' called with unexpected value for argument 'ep'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ti), (void*)(ti), sizeof(TRACK_INFO), cmock_line, "Function 'read_external' called with unexpected value for argument 'ti'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_read_external(CMOCK_read_external_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, External_Process* ep, TRACK_INFO* ti)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_ep = ep;
  cmock_call_instance->Expected_ti = ti;
}

void read_external_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_external_CALL_INSTANCE));
  CMOCK_read_external_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_external_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_external_CallInstance = CMock_Guts_MemChain(Mock.read_external_CallInstance, cmock_guts_index);
  Mock.read_external_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.read_external_IgnoreBool = (int)1;
}

void read_external_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, External_Process* ep, TRACK_INFO* ti, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_external_CALL_INSTANCE));
  CMOCK_read_external_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_external_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_external_CallInstance = CMock_Guts_MemChain(Mock.read_external_CallInstance, cmock_guts_index);
  Mock.read_external_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_read_external(cmock_call_instance, rmi, ep, ti);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void read_external_StubWithCallback(CMOCK_read_external_CALLBACK Callback)
{
  Mock.read_external_CallbackFunctionPointer = Callback;
}

void close_external(External_Process** epp)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_close_external_CALL_INSTANCE* cmock_call_instance = (CMOCK_close_external_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.close_external_CallInstance);
  Mock.close_external_CallInstance = CMock_Guts_MemNext(Mock.close_external_CallInstance);
  if (Mock.close_external_IgnoreBool)
  {
    return;
  }
  if (Mock.close_external_CallbackFunctionPointer != NULL)
  {
    Mock.close_external_CallbackFunctionPointer(epp, Mock.close_external_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'close_external' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_epp, epp, cmock_line, "Function 'close_external' called with unexpected value for argument 'epp'.");
  }
}

void CMockExpectParameters_close_external(CMOCK_close_external_CALL_INSTANCE* cmock_call_instance, External_Process** epp)
{
  cmock_call_instance->Expected_epp = epp;
}

void close_external_CMockIgnore(void)
{
  Mock.close_external_IgnoreBool = (int)1;
}

void close_external_CMockExpect(UNITY_LINE_TYPE cmock_line, External_Process** epp)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_close_external_CALL_INSTANCE));
  CMOCK_close_external_CALL_INSTANCE* cmock_call_instance = (CMOCK_close_external_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.close_external_CallInstance = CMock_Guts_MemChain(Mock.close_external_CallInstance, cmock_guts_index);
  Mock.close_external_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_close_external(cmock_call_instance, epp);
}

void close_external_StubWithCallback(CMOCK_close_external_CALLBACK Callback)
{
  Mock.close_external_CallbackFunctionPointer = Callback;
}

