/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockerrors.h"

typedef struct _CMOCK_errors_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_errors_init_CALL_INSTANCE;

typedef struct _CMOCK_errors_get_string_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* ReturnVal;
  error_code Expected_code;

} CMOCK_errors_get_string_CALL_INSTANCE;

static struct MockerrorsInstance
{
  int errors_init_IgnoreBool;
  CMOCK_errors_init_CALLBACK errors_init_CallbackFunctionPointer;
  int errors_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE errors_init_CallInstance;
  int errors_get_string_IgnoreBool;
  char* errors_get_string_FinalReturn;
  CMOCK_errors_get_string_CALLBACK errors_get_string_CallbackFunctionPointer;
  int errors_get_string_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE errors_get_string_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockerrors_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.errors_init_IgnoreBool)
    Mock.errors_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.errors_init_CallInstance, cmock_line, "Function 'errors_init' called less times than expected.");
  if (Mock.errors_init_CallbackFunctionPointer != NULL)
    Mock.errors_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.errors_get_string_IgnoreBool)
    Mock.errors_get_string_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.errors_get_string_CallInstance, cmock_line, "Function 'errors_get_string' called less times than expected.");
  if (Mock.errors_get_string_CallbackFunctionPointer != NULL)
    Mock.errors_get_string_CallInstance = CMOCK_GUTS_NONE;
}

void Mockerrors_Init(void)
{
  Mockerrors_Destroy();
}

void Mockerrors_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.errors_init_CallbackFunctionPointer = NULL;
  Mock.errors_init_CallbackCalls = 0;
  Mock.errors_get_string_CallbackFunctionPointer = NULL;
  Mock.errors_get_string_CallbackCalls = 0;
}

void errors_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_errors_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_errors_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.errors_init_CallInstance);
  Mock.errors_init_CallInstance = CMock_Guts_MemNext(Mock.errors_init_CallInstance);
  if (Mock.errors_init_IgnoreBool)
  {
    return;
  }
  if (Mock.errors_init_CallbackFunctionPointer != NULL)
  {
    Mock.errors_init_CallbackFunctionPointer(Mock.errors_init_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'errors_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void errors_init_CMockIgnore(void)
{
  Mock.errors_init_IgnoreBool = (int)1;
}

void errors_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_errors_init_CALL_INSTANCE));
  CMOCK_errors_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_errors_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.errors_init_CallInstance = CMock_Guts_MemChain(Mock.errors_init_CallInstance, cmock_guts_index);
  Mock.errors_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void errors_init_StubWithCallback(CMOCK_errors_init_CALLBACK Callback)
{
  Mock.errors_init_CallbackFunctionPointer = Callback;
}

char* errors_get_string(error_code code)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_errors_get_string_CALL_INSTANCE* cmock_call_instance = (CMOCK_errors_get_string_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.errors_get_string_CallInstance);
  Mock.errors_get_string_CallInstance = CMock_Guts_MemNext(Mock.errors_get_string_CallInstance);
  if (Mock.errors_get_string_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.errors_get_string_FinalReturn;
    Mock.errors_get_string_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.errors_get_string_CallbackFunctionPointer != NULL)
  {
    return Mock.errors_get_string_CallbackFunctionPointer(code, Mock.errors_get_string_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'errors_get_string' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_code), (void*)(&code), sizeof(error_code), cmock_line, "Function 'errors_get_string' called with unexpected value for argument 'code'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_errors_get_string(CMOCK_errors_get_string_CALL_INSTANCE* cmock_call_instance, error_code code)
{
  memcpy(&cmock_call_instance->Expected_code, &code, sizeof(error_code));
}

void errors_get_string_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_errors_get_string_CALL_INSTANCE));
  CMOCK_errors_get_string_CALL_INSTANCE* cmock_call_instance = (CMOCK_errors_get_string_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.errors_get_string_CallInstance = CMock_Guts_MemChain(Mock.errors_get_string_CallInstance, cmock_guts_index);
  Mock.errors_get_string_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.errors_get_string_IgnoreBool = (int)1;
}

void errors_get_string_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, error_code code, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_errors_get_string_CALL_INSTANCE));
  CMOCK_errors_get_string_CALL_INSTANCE* cmock_call_instance = (CMOCK_errors_get_string_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.errors_get_string_CallInstance = CMock_Guts_MemChain(Mock.errors_get_string_CallInstance, cmock_guts_index);
  Mock.errors_get_string_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_errors_get_string(cmock_call_instance, code);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void errors_get_string_StubWithCallback(CMOCK_errors_get_string_CALLBACK Callback)
{
  Mock.errors_get_string_CallbackFunctionPointer = Callback;
}

