/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockfilelib.h"

typedef struct _CMOCK_filelib_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  BOOL Expected_do_individual_tracks;
  BOOL Expected_do_count;
  int Expected_count_start;
  BOOL Expected_keep_incomplete;
  BOOL Expected_do_show_file;
  int Expected_content_type;
  char* Expected_output_directory;
  char* Expected_output_pattern;
  char* Expected_showfile_pattern;
  int Expected_get_separate_dirs;
  int Expected_get_date_stamp;
  char* Expected_icy_name;

} CMOCK_filelib_init_CALL_INSTANCE;

typedef struct _CMOCK_filelib_start_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  TRACK_INFO* Expected_ti;

} CMOCK_filelib_start_CALL_INSTANCE;

typedef struct _CMOCK_filelib_write_track_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  char* Expected_buf;
  u_long Expected_size;

} CMOCK_filelib_write_track_CALL_INSTANCE;

typedef struct _CMOCK_filelib_write_show_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  char* Expected_buf;
  u_long Expected_size;

} CMOCK_filelib_write_show_CALL_INSTANCE;

typedef struct _CMOCK_filelib_write_cue_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  TRACK_INFO* Expected_ti;
  int Expected_secs;

} CMOCK_filelib_write_cue_CALL_INSTANCE;

typedef struct _CMOCK_filelib_end_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  TRACK_INFO* Expected_ti;
  enum OverwriteOpt Expected_overwrite;
  BOOL Expected_truncate_dup;
  mchar* Expected_fullpath;

} CMOCK_filelib_end_CALL_INSTANCE;

typedef struct _CMOCK_filelib_shutdown_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RIP_MANAGER_INFO* Expected_rmi;

} CMOCK_filelib_shutdown_CALL_INSTANCE;

static struct MockfilelibInstance
{
  int filelib_init_IgnoreBool;
  error_code filelib_init_FinalReturn;
  CMOCK_filelib_init_CALLBACK filelib_init_CallbackFunctionPointer;
  int filelib_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE filelib_init_CallInstance;
  int filelib_start_IgnoreBool;
  error_code filelib_start_FinalReturn;
  CMOCK_filelib_start_CALLBACK filelib_start_CallbackFunctionPointer;
  int filelib_start_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE filelib_start_CallInstance;
  int filelib_write_track_IgnoreBool;
  error_code filelib_write_track_FinalReturn;
  CMOCK_filelib_write_track_CALLBACK filelib_write_track_CallbackFunctionPointer;
  int filelib_write_track_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE filelib_write_track_CallInstance;
  int filelib_write_show_IgnoreBool;
  error_code filelib_write_show_FinalReturn;
  CMOCK_filelib_write_show_CALLBACK filelib_write_show_CallbackFunctionPointer;
  int filelib_write_show_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE filelib_write_show_CallInstance;
  int filelib_write_cue_IgnoreBool;
  error_code filelib_write_cue_FinalReturn;
  CMOCK_filelib_write_cue_CALLBACK filelib_write_cue_CallbackFunctionPointer;
  int filelib_write_cue_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE filelib_write_cue_CallInstance;
  int filelib_end_IgnoreBool;
  error_code filelib_end_FinalReturn;
  CMOCK_filelib_end_CALLBACK filelib_end_CallbackFunctionPointer;
  int filelib_end_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE filelib_end_CallInstance;
  int filelib_shutdown_IgnoreBool;
  CMOCK_filelib_shutdown_CALLBACK filelib_shutdown_CallbackFunctionPointer;
  int filelib_shutdown_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE filelib_shutdown_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfilelib_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.filelib_init_IgnoreBool)
    Mock.filelib_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.filelib_init_CallInstance, cmock_line, "Function 'filelib_init' called less times than expected.");
  if (Mock.filelib_init_CallbackFunctionPointer != NULL)
    Mock.filelib_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.filelib_start_IgnoreBool)
    Mock.filelib_start_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.filelib_start_CallInstance, cmock_line, "Function 'filelib_start' called less times than expected.");
  if (Mock.filelib_start_CallbackFunctionPointer != NULL)
    Mock.filelib_start_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.filelib_write_track_IgnoreBool)
    Mock.filelib_write_track_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.filelib_write_track_CallInstance, cmock_line, "Function 'filelib_write_track' called less times than expected.");
  if (Mock.filelib_write_track_CallbackFunctionPointer != NULL)
    Mock.filelib_write_track_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.filelib_write_show_IgnoreBool)
    Mock.filelib_write_show_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.filelib_write_show_CallInstance, cmock_line, "Function 'filelib_write_show' called less times than expected.");
  if (Mock.filelib_write_show_CallbackFunctionPointer != NULL)
    Mock.filelib_write_show_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.filelib_write_cue_IgnoreBool)
    Mock.filelib_write_cue_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.filelib_write_cue_CallInstance, cmock_line, "Function 'filelib_write_cue' called less times than expected.");
  if (Mock.filelib_write_cue_CallbackFunctionPointer != NULL)
    Mock.filelib_write_cue_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.filelib_end_IgnoreBool)
    Mock.filelib_end_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.filelib_end_CallInstance, cmock_line, "Function 'filelib_end' called less times than expected.");
  if (Mock.filelib_end_CallbackFunctionPointer != NULL)
    Mock.filelib_end_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.filelib_shutdown_IgnoreBool)
    Mock.filelib_shutdown_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.filelib_shutdown_CallInstance, cmock_line, "Function 'filelib_shutdown' called less times than expected.");
  if (Mock.filelib_shutdown_CallbackFunctionPointer != NULL)
    Mock.filelib_shutdown_CallInstance = CMOCK_GUTS_NONE;
}

void Mockfilelib_Init(void)
{
  Mockfilelib_Destroy();
}

void Mockfilelib_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.filelib_init_CallbackFunctionPointer = NULL;
  Mock.filelib_init_CallbackCalls = 0;
  Mock.filelib_start_CallbackFunctionPointer = NULL;
  Mock.filelib_start_CallbackCalls = 0;
  Mock.filelib_write_track_CallbackFunctionPointer = NULL;
  Mock.filelib_write_track_CallbackCalls = 0;
  Mock.filelib_write_show_CallbackFunctionPointer = NULL;
  Mock.filelib_write_show_CallbackCalls = 0;
  Mock.filelib_write_cue_CallbackFunctionPointer = NULL;
  Mock.filelib_write_cue_CallbackCalls = 0;
  Mock.filelib_end_CallbackFunctionPointer = NULL;
  Mock.filelib_end_CallbackCalls = 0;
  Mock.filelib_shutdown_CallbackFunctionPointer = NULL;
  Mock.filelib_shutdown_CallbackCalls = 0;
}

error_code filelib_init(RIP_MANAGER_INFO* rmi, BOOL do_individual_tracks, BOOL do_count, int count_start, BOOL keep_incomplete, BOOL do_show_file, int content_type, char* output_directory, char* output_pattern, char* showfile_pattern, int get_separate_dirs, int get_date_stamp, char* icy_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_filelib_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.filelib_init_CallInstance);
  Mock.filelib_init_CallInstance = CMock_Guts_MemNext(Mock.filelib_init_CallInstance);
  if (Mock.filelib_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.filelib_init_FinalReturn;
    memcpy(&Mock.filelib_init_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.filelib_init_CallbackFunctionPointer != NULL)
  {
    return Mock.filelib_init_CallbackFunctionPointer(rmi, do_individual_tracks, do_count, count_start, keep_incomplete, do_show_file, content_type, output_directory, output_pattern, showfile_pattern, get_separate_dirs, get_date_stamp, icy_name, Mock.filelib_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'filelib_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'filelib_init' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_do_individual_tracks, do_individual_tracks, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'do_individual_tracks'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_do_count, do_count, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'do_count'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_count_start, count_start, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'count_start'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_keep_incomplete, keep_incomplete, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'keep_incomplete'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_do_show_file, do_show_file, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'do_show_file'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_content_type, content_type, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'content_type'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_output_directory, output_directory, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'output_directory'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_output_pattern, output_pattern, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'output_pattern'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_showfile_pattern, showfile_pattern, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'showfile_pattern'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_get_separate_dirs, get_separate_dirs, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'get_separate_dirs'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_get_date_stamp, get_date_stamp, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'get_date_stamp'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_icy_name, icy_name, cmock_line, "Function 'filelib_init' called with unexpected value for argument 'icy_name'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_filelib_init(CMOCK_filelib_init_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, BOOL do_individual_tracks, BOOL do_count, int count_start, BOOL keep_incomplete, BOOL do_show_file, int content_type, char* output_directory, char* output_pattern, char* showfile_pattern, int get_separate_dirs, int get_date_stamp, char* icy_name)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_do_individual_tracks = do_individual_tracks;
  cmock_call_instance->Expected_do_count = do_count;
  cmock_call_instance->Expected_count_start = count_start;
  cmock_call_instance->Expected_keep_incomplete = keep_incomplete;
  cmock_call_instance->Expected_do_show_file = do_show_file;
  cmock_call_instance->Expected_content_type = content_type;
  cmock_call_instance->Expected_output_directory = output_directory;
  cmock_call_instance->Expected_output_pattern = output_pattern;
  cmock_call_instance->Expected_showfile_pattern = showfile_pattern;
  cmock_call_instance->Expected_get_separate_dirs = get_separate_dirs;
  cmock_call_instance->Expected_get_date_stamp = get_date_stamp;
  cmock_call_instance->Expected_icy_name = icy_name;
}

void filelib_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_init_CALL_INSTANCE));
  CMOCK_filelib_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_init_CallInstance = CMock_Guts_MemChain(Mock.filelib_init_CallInstance, cmock_guts_index);
  Mock.filelib_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.filelib_init_IgnoreBool = (int)1;
}

void filelib_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, BOOL do_individual_tracks, BOOL do_count, int count_start, BOOL keep_incomplete, BOOL do_show_file, int content_type, char* output_directory, char* output_pattern, char* showfile_pattern, int get_separate_dirs, int get_date_stamp, char* icy_name, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_init_CALL_INSTANCE));
  CMOCK_filelib_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_init_CallInstance = CMock_Guts_MemChain(Mock.filelib_init_CallInstance, cmock_guts_index);
  Mock.filelib_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_filelib_init(cmock_call_instance, rmi, do_individual_tracks, do_count, count_start, keep_incomplete, do_show_file, content_type, output_directory, output_pattern, showfile_pattern, get_separate_dirs, get_date_stamp, icy_name);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void filelib_init_StubWithCallback(CMOCK_filelib_init_CALLBACK Callback)
{
  Mock.filelib_init_CallbackFunctionPointer = Callback;
}

error_code filelib_start(RIP_MANAGER_INFO* rmi, TRACK_INFO* ti)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_filelib_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.filelib_start_CallInstance);
  Mock.filelib_start_CallInstance = CMock_Guts_MemNext(Mock.filelib_start_CallInstance);
  if (Mock.filelib_start_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.filelib_start_FinalReturn;
    memcpy(&Mock.filelib_start_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.filelib_start_CallbackFunctionPointer != NULL)
  {
    return Mock.filelib_start_CallbackFunctionPointer(rmi, ti, Mock.filelib_start_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'filelib_start' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'filelib_start' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ti), (void*)(ti), sizeof(TRACK_INFO), cmock_line, "Function 'filelib_start' called with unexpected value for argument 'ti'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_filelib_start(CMOCK_filelib_start_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_ti = ti;
}

void filelib_start_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_start_CALL_INSTANCE));
  CMOCK_filelib_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_start_CallInstance = CMock_Guts_MemChain(Mock.filelib_start_CallInstance, cmock_guts_index);
  Mock.filelib_start_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.filelib_start_IgnoreBool = (int)1;
}

void filelib_start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_start_CALL_INSTANCE));
  CMOCK_filelib_start_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_start_CallInstance = CMock_Guts_MemChain(Mock.filelib_start_CallInstance, cmock_guts_index);
  Mock.filelib_start_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_filelib_start(cmock_call_instance, rmi, ti);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void filelib_start_StubWithCallback(CMOCK_filelib_start_CALLBACK Callback)
{
  Mock.filelib_start_CallbackFunctionPointer = Callback;
}

error_code filelib_write_track(RIP_MANAGER_INFO* rmi, char* buf, u_long size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_filelib_write_track_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_track_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.filelib_write_track_CallInstance);
  Mock.filelib_write_track_CallInstance = CMock_Guts_MemNext(Mock.filelib_write_track_CallInstance);
  if (Mock.filelib_write_track_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.filelib_write_track_FinalReturn;
    memcpy(&Mock.filelib_write_track_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.filelib_write_track_CallbackFunctionPointer != NULL)
  {
    return Mock.filelib_write_track_CallbackFunctionPointer(rmi, buf, size, Mock.filelib_write_track_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'filelib_write_track' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'filelib_write_track' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buf, buf, cmock_line, "Function 'filelib_write_track' called with unexpected value for argument 'buf'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(u_long), cmock_line, "Function 'filelib_write_track' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_filelib_write_track(CMOCK_filelib_write_track_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, char* buf, u_long size)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_buf = buf;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(u_long));
}

void filelib_write_track_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_write_track_CALL_INSTANCE));
  CMOCK_filelib_write_track_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_track_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_write_track_CallInstance = CMock_Guts_MemChain(Mock.filelib_write_track_CallInstance, cmock_guts_index);
  Mock.filelib_write_track_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.filelib_write_track_IgnoreBool = (int)1;
}

void filelib_write_track_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, char* buf, u_long size, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_write_track_CALL_INSTANCE));
  CMOCK_filelib_write_track_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_track_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_write_track_CallInstance = CMock_Guts_MemChain(Mock.filelib_write_track_CallInstance, cmock_guts_index);
  Mock.filelib_write_track_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_filelib_write_track(cmock_call_instance, rmi, buf, size);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void filelib_write_track_StubWithCallback(CMOCK_filelib_write_track_CALLBACK Callback)
{
  Mock.filelib_write_track_CallbackFunctionPointer = Callback;
}

error_code filelib_write_show(RIP_MANAGER_INFO* rmi, char* buf, u_long size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_filelib_write_show_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_show_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.filelib_write_show_CallInstance);
  Mock.filelib_write_show_CallInstance = CMock_Guts_MemNext(Mock.filelib_write_show_CallInstance);
  if (Mock.filelib_write_show_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.filelib_write_show_FinalReturn;
    memcpy(&Mock.filelib_write_show_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.filelib_write_show_CallbackFunctionPointer != NULL)
  {
    return Mock.filelib_write_show_CallbackFunctionPointer(rmi, buf, size, Mock.filelib_write_show_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'filelib_write_show' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'filelib_write_show' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buf, buf, cmock_line, "Function 'filelib_write_show' called with unexpected value for argument 'buf'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(u_long), cmock_line, "Function 'filelib_write_show' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_filelib_write_show(CMOCK_filelib_write_show_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, char* buf, u_long size)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_buf = buf;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(u_long));
}

void filelib_write_show_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_write_show_CALL_INSTANCE));
  CMOCK_filelib_write_show_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_show_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_write_show_CallInstance = CMock_Guts_MemChain(Mock.filelib_write_show_CallInstance, cmock_guts_index);
  Mock.filelib_write_show_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.filelib_write_show_IgnoreBool = (int)1;
}

void filelib_write_show_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, char* buf, u_long size, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_write_show_CALL_INSTANCE));
  CMOCK_filelib_write_show_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_show_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_write_show_CallInstance = CMock_Guts_MemChain(Mock.filelib_write_show_CallInstance, cmock_guts_index);
  Mock.filelib_write_show_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_filelib_write_show(cmock_call_instance, rmi, buf, size);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void filelib_write_show_StubWithCallback(CMOCK_filelib_write_show_CALLBACK Callback)
{
  Mock.filelib_write_show_CallbackFunctionPointer = Callback;
}

error_code filelib_write_cue(RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, int secs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_filelib_write_cue_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_cue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.filelib_write_cue_CallInstance);
  Mock.filelib_write_cue_CallInstance = CMock_Guts_MemNext(Mock.filelib_write_cue_CallInstance);
  if (Mock.filelib_write_cue_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.filelib_write_cue_FinalReturn;
    memcpy(&Mock.filelib_write_cue_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.filelib_write_cue_CallbackFunctionPointer != NULL)
  {
    return Mock.filelib_write_cue_CallbackFunctionPointer(rmi, ti, secs, Mock.filelib_write_cue_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'filelib_write_cue' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'filelib_write_cue' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ti), (void*)(ti), sizeof(TRACK_INFO), cmock_line, "Function 'filelib_write_cue' called with unexpected value for argument 'ti'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_secs, secs, cmock_line, "Function 'filelib_write_cue' called with unexpected value for argument 'secs'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_filelib_write_cue(CMOCK_filelib_write_cue_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, int secs)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_ti = ti;
  cmock_call_instance->Expected_secs = secs;
}

void filelib_write_cue_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_write_cue_CALL_INSTANCE));
  CMOCK_filelib_write_cue_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_cue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_write_cue_CallInstance = CMock_Guts_MemChain(Mock.filelib_write_cue_CallInstance, cmock_guts_index);
  Mock.filelib_write_cue_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.filelib_write_cue_IgnoreBool = (int)1;
}

void filelib_write_cue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, int secs, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_write_cue_CALL_INSTANCE));
  CMOCK_filelib_write_cue_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_write_cue_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_write_cue_CallInstance = CMock_Guts_MemChain(Mock.filelib_write_cue_CallInstance, cmock_guts_index);
  Mock.filelib_write_cue_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_filelib_write_cue(cmock_call_instance, rmi, ti, secs);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void filelib_write_cue_StubWithCallback(CMOCK_filelib_write_cue_CALLBACK Callback)
{
  Mock.filelib_write_cue_CallbackFunctionPointer = Callback;
}

error_code filelib_end(RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, enum OverwriteOpt overwrite, BOOL truncate_dup, mchar* fullpath)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_filelib_end_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_end_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.filelib_end_CallInstance);
  Mock.filelib_end_CallInstance = CMock_Guts_MemNext(Mock.filelib_end_CallInstance);
  if (Mock.filelib_end_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.filelib_end_FinalReturn;
    memcpy(&Mock.filelib_end_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.filelib_end_CallbackFunctionPointer != NULL)
  {
    return Mock.filelib_end_CallbackFunctionPointer(rmi, ti, overwrite, truncate_dup, fullpath, Mock.filelib_end_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'filelib_end' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'filelib_end' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ti), (void*)(ti), sizeof(TRACK_INFO), cmock_line, "Function 'filelib_end' called with unexpected value for argument 'ti'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_overwrite), (void*)(&overwrite), sizeof(enum OverwriteOpt), cmock_line, "Function 'filelib_end' called with unexpected value for argument 'overwrite'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_truncate_dup, truncate_dup, cmock_line, "Function 'filelib_end' called with unexpected value for argument 'truncate_dup'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_fullpath), (void*)(fullpath), sizeof(mchar), cmock_line, "Function 'filelib_end' called with unexpected value for argument 'fullpath'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_filelib_end(CMOCK_filelib_end_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, enum OverwriteOpt overwrite, BOOL truncate_dup, mchar* fullpath)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_ti = ti;
  memcpy(&cmock_call_instance->Expected_overwrite, &overwrite, sizeof(enum OverwriteOpt));
  cmock_call_instance->Expected_truncate_dup = truncate_dup;
  cmock_call_instance->Expected_fullpath = fullpath;
}

void filelib_end_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_end_CALL_INSTANCE));
  CMOCK_filelib_end_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_end_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_end_CallInstance = CMock_Guts_MemChain(Mock.filelib_end_CallInstance, cmock_guts_index);
  Mock.filelib_end_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.filelib_end_IgnoreBool = (int)1;
}

void filelib_end_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, enum OverwriteOpt overwrite, BOOL truncate_dup, mchar* fullpath, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_end_CALL_INSTANCE));
  CMOCK_filelib_end_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_end_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_end_CallInstance = CMock_Guts_MemChain(Mock.filelib_end_CallInstance, cmock_guts_index);
  Mock.filelib_end_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_filelib_end(cmock_call_instance, rmi, ti, overwrite, truncate_dup, fullpath);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void filelib_end_StubWithCallback(CMOCK_filelib_end_CALLBACK Callback)
{
  Mock.filelib_end_CallbackFunctionPointer = Callback;
}

void filelib_shutdown(RIP_MANAGER_INFO* rmi)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_filelib_shutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.filelib_shutdown_CallInstance);
  Mock.filelib_shutdown_CallInstance = CMock_Guts_MemNext(Mock.filelib_shutdown_CallInstance);
  if (Mock.filelib_shutdown_IgnoreBool)
  {
    return;
  }
  if (Mock.filelib_shutdown_CallbackFunctionPointer != NULL)
  {
    Mock.filelib_shutdown_CallbackFunctionPointer(rmi, Mock.filelib_shutdown_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'filelib_shutdown' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'filelib_shutdown' called with unexpected value for argument 'rmi'.");
  }
}

void CMockExpectParameters_filelib_shutdown(CMOCK_filelib_shutdown_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi)
{
  cmock_call_instance->Expected_rmi = rmi;
}

void filelib_shutdown_CMockIgnore(void)
{
  Mock.filelib_shutdown_IgnoreBool = (int)1;
}

void filelib_shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_filelib_shutdown_CALL_INSTANCE));
  CMOCK_filelib_shutdown_CALL_INSTANCE* cmock_call_instance = (CMOCK_filelib_shutdown_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.filelib_shutdown_CallInstance = CMock_Guts_MemChain(Mock.filelib_shutdown_CallInstance, cmock_guts_index);
  Mock.filelib_shutdown_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_filelib_shutdown(cmock_call_instance, rmi);
}

void filelib_shutdown_StubWithCallback(CMOCK_filelib_shutdown_CALLBACK Callback)
{
  Mock.filelib_shutdown_CallbackFunctionPointer = Callback;
}

