/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockprefs.h"

typedef struct _CMOCK_prefs_load_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;

} CMOCK_prefs_load_CALL_INSTANCE;

typedef struct _CMOCK_prefs_save_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_prefs_save_CALL_INSTANCE;

typedef struct _CMOCK_prefs_get_global_prefs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GLOBAL_PREFS* Expected_global_prefs;

} CMOCK_prefs_get_global_prefs_CALL_INSTANCE;

typedef struct _CMOCK_prefs_set_global_prefs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  GLOBAL_PREFS* Expected_global_prefs;

} CMOCK_prefs_set_global_prefs_CALL_INSTANCE;

typedef struct _CMOCK_prefs_get_stream_prefs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  STREAM_PREFS* Expected_prefs;
  char* Expected_label;

} CMOCK_prefs_get_stream_prefs_CALL_INSTANCE;

typedef struct _CMOCK_prefs_set_stream_prefs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  STREAM_PREFS* Expected_prefs;
  char* Expected_label;

} CMOCK_prefs_set_stream_prefs_CALL_INSTANCE;

typedef struct _CMOCK_prefs_get_wstreamripper_prefs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WSTREAMRIPPER_PREFS* Expected_wsr_prefs;

} CMOCK_prefs_get_wstreamripper_prefs_CALL_INSTANCE;

typedef struct _CMOCK_prefs_set_wstreamripper_prefs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  WSTREAMRIPPER_PREFS* Expected_wsr_prefs;

} CMOCK_prefs_set_wstreamripper_prefs_CALL_INSTANCE;

typedef struct _CMOCK_prefs_is_https_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  GLOBAL_PREFS* Expected_global_prefs;

} CMOCK_prefs_is_https_CALL_INSTANCE;

typedef struct _CMOCK_debug_stream_prefs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  STREAM_PREFS* Expected_prefs;

} CMOCK_debug_stream_prefs_CALL_INSTANCE;

static struct MockprefsInstance
{
  int prefs_load_IgnoreBool;
  int prefs_load_FinalReturn;
  CMOCK_prefs_load_CALLBACK prefs_load_CallbackFunctionPointer;
  int prefs_load_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_load_CallInstance;
  int prefs_save_IgnoreBool;
  CMOCK_prefs_save_CALLBACK prefs_save_CallbackFunctionPointer;
  int prefs_save_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_save_CallInstance;
  int prefs_get_global_prefs_IgnoreBool;
  CMOCK_prefs_get_global_prefs_CALLBACK prefs_get_global_prefs_CallbackFunctionPointer;
  int prefs_get_global_prefs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_get_global_prefs_CallInstance;
  int prefs_set_global_prefs_IgnoreBool;
  CMOCK_prefs_set_global_prefs_CALLBACK prefs_set_global_prefs_CallbackFunctionPointer;
  int prefs_set_global_prefs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_set_global_prefs_CallInstance;
  int prefs_get_stream_prefs_IgnoreBool;
  CMOCK_prefs_get_stream_prefs_CALLBACK prefs_get_stream_prefs_CallbackFunctionPointer;
  int prefs_get_stream_prefs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_get_stream_prefs_CallInstance;
  int prefs_set_stream_prefs_IgnoreBool;
  CMOCK_prefs_set_stream_prefs_CALLBACK prefs_set_stream_prefs_CallbackFunctionPointer;
  int prefs_set_stream_prefs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_set_stream_prefs_CallInstance;
  int prefs_get_wstreamripper_prefs_IgnoreBool;
  CMOCK_prefs_get_wstreamripper_prefs_CALLBACK prefs_get_wstreamripper_prefs_CallbackFunctionPointer;
  int prefs_get_wstreamripper_prefs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_get_wstreamripper_prefs_CallInstance;
  int prefs_set_wstreamripper_prefs_IgnoreBool;
  CMOCK_prefs_set_wstreamripper_prefs_CALLBACK prefs_set_wstreamripper_prefs_CallbackFunctionPointer;
  int prefs_set_wstreamripper_prefs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_set_wstreamripper_prefs_CallInstance;
  int prefs_is_https_IgnoreBool;
  bool prefs_is_https_FinalReturn;
  CMOCK_prefs_is_https_CALLBACK prefs_is_https_CallbackFunctionPointer;
  int prefs_is_https_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE prefs_is_https_CallInstance;
  int debug_stream_prefs_IgnoreBool;
  CMOCK_debug_stream_prefs_CALLBACK debug_stream_prefs_CallbackFunctionPointer;
  int debug_stream_prefs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE debug_stream_prefs_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockprefs_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.prefs_load_IgnoreBool)
    Mock.prefs_load_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_load_CallInstance, cmock_line, "Function 'prefs_load' called less times than expected.");
  if (Mock.prefs_load_CallbackFunctionPointer != NULL)
    Mock.prefs_load_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.prefs_save_IgnoreBool)
    Mock.prefs_save_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_save_CallInstance, cmock_line, "Function 'prefs_save' called less times than expected.");
  if (Mock.prefs_save_CallbackFunctionPointer != NULL)
    Mock.prefs_save_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.prefs_get_global_prefs_IgnoreBool)
    Mock.prefs_get_global_prefs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_get_global_prefs_CallInstance, cmock_line, "Function 'prefs_get_global_prefs' called less times than expected.");
  if (Mock.prefs_get_global_prefs_CallbackFunctionPointer != NULL)
    Mock.prefs_get_global_prefs_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.prefs_set_global_prefs_IgnoreBool)
    Mock.prefs_set_global_prefs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_set_global_prefs_CallInstance, cmock_line, "Function 'prefs_set_global_prefs' called less times than expected.");
  if (Mock.prefs_set_global_prefs_CallbackFunctionPointer != NULL)
    Mock.prefs_set_global_prefs_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.prefs_get_stream_prefs_IgnoreBool)
    Mock.prefs_get_stream_prefs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_get_stream_prefs_CallInstance, cmock_line, "Function 'prefs_get_stream_prefs' called less times than expected.");
  if (Mock.prefs_get_stream_prefs_CallbackFunctionPointer != NULL)
    Mock.prefs_get_stream_prefs_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.prefs_set_stream_prefs_IgnoreBool)
    Mock.prefs_set_stream_prefs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_set_stream_prefs_CallInstance, cmock_line, "Function 'prefs_set_stream_prefs' called less times than expected.");
  if (Mock.prefs_set_stream_prefs_CallbackFunctionPointer != NULL)
    Mock.prefs_set_stream_prefs_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.prefs_get_wstreamripper_prefs_IgnoreBool)
    Mock.prefs_get_wstreamripper_prefs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_get_wstreamripper_prefs_CallInstance, cmock_line, "Function 'prefs_get_wstreamripper_prefs' called less times than expected.");
  if (Mock.prefs_get_wstreamripper_prefs_CallbackFunctionPointer != NULL)
    Mock.prefs_get_wstreamripper_prefs_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.prefs_set_wstreamripper_prefs_IgnoreBool)
    Mock.prefs_set_wstreamripper_prefs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_set_wstreamripper_prefs_CallInstance, cmock_line, "Function 'prefs_set_wstreamripper_prefs' called less times than expected.");
  if (Mock.prefs_set_wstreamripper_prefs_CallbackFunctionPointer != NULL)
    Mock.prefs_set_wstreamripper_prefs_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.prefs_is_https_IgnoreBool)
    Mock.prefs_is_https_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.prefs_is_https_CallInstance, cmock_line, "Function 'prefs_is_https' called less times than expected.");
  if (Mock.prefs_is_https_CallbackFunctionPointer != NULL)
    Mock.prefs_is_https_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.debug_stream_prefs_IgnoreBool)
    Mock.debug_stream_prefs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debug_stream_prefs_CallInstance, cmock_line, "Function 'debug_stream_prefs' called less times than expected.");
  if (Mock.debug_stream_prefs_CallbackFunctionPointer != NULL)
    Mock.debug_stream_prefs_CallInstance = CMOCK_GUTS_NONE;
}

void Mockprefs_Init(void)
{
  Mockprefs_Destroy();
}

void Mockprefs_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.prefs_load_CallbackFunctionPointer = NULL;
  Mock.prefs_load_CallbackCalls = 0;
  Mock.prefs_save_CallbackFunctionPointer = NULL;
  Mock.prefs_save_CallbackCalls = 0;
  Mock.prefs_get_global_prefs_CallbackFunctionPointer = NULL;
  Mock.prefs_get_global_prefs_CallbackCalls = 0;
  Mock.prefs_set_global_prefs_CallbackFunctionPointer = NULL;
  Mock.prefs_set_global_prefs_CallbackCalls = 0;
  Mock.prefs_get_stream_prefs_CallbackFunctionPointer = NULL;
  Mock.prefs_get_stream_prefs_CallbackCalls = 0;
  Mock.prefs_set_stream_prefs_CallbackFunctionPointer = NULL;
  Mock.prefs_set_stream_prefs_CallbackCalls = 0;
  Mock.prefs_get_wstreamripper_prefs_CallbackFunctionPointer = NULL;
  Mock.prefs_get_wstreamripper_prefs_CallbackCalls = 0;
  Mock.prefs_set_wstreamripper_prefs_CallbackFunctionPointer = NULL;
  Mock.prefs_set_wstreamripper_prefs_CallbackCalls = 0;
  Mock.prefs_is_https_CallbackFunctionPointer = NULL;
  Mock.prefs_is_https_CallbackCalls = 0;
  Mock.debug_stream_prefs_CallbackFunctionPointer = NULL;
  Mock.debug_stream_prefs_CallbackCalls = 0;
}

int prefs_load(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_load_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_load_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_load_CallInstance);
  Mock.prefs_load_CallInstance = CMock_Guts_MemNext(Mock.prefs_load_CallInstance);
  if (Mock.prefs_load_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.prefs_load_FinalReturn;
    Mock.prefs_load_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.prefs_load_CallbackFunctionPointer != NULL)
  {
    return Mock.prefs_load_CallbackFunctionPointer(Mock.prefs_load_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_load' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void prefs_load_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_load_CALL_INSTANCE));
  CMOCK_prefs_load_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_load_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_load_CallInstance = CMock_Guts_MemChain(Mock.prefs_load_CallInstance, cmock_guts_index);
  Mock.prefs_load_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.prefs_load_IgnoreBool = (int)1;
}

void prefs_load_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_load_CALL_INSTANCE));
  CMOCK_prefs_load_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_load_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_load_CallInstance = CMock_Guts_MemChain(Mock.prefs_load_CallInstance, cmock_guts_index);
  Mock.prefs_load_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void prefs_load_StubWithCallback(CMOCK_prefs_load_CALLBACK Callback)
{
  Mock.prefs_load_CallbackFunctionPointer = Callback;
}

void prefs_save(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_save_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_save_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_save_CallInstance);
  Mock.prefs_save_CallInstance = CMock_Guts_MemNext(Mock.prefs_save_CallInstance);
  if (Mock.prefs_save_IgnoreBool)
  {
    return;
  }
  if (Mock.prefs_save_CallbackFunctionPointer != NULL)
  {
    Mock.prefs_save_CallbackFunctionPointer(Mock.prefs_save_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_save' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void prefs_save_CMockIgnore(void)
{
  Mock.prefs_save_IgnoreBool = (int)1;
}

void prefs_save_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_save_CALL_INSTANCE));
  CMOCK_prefs_save_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_save_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_save_CallInstance = CMock_Guts_MemChain(Mock.prefs_save_CallInstance, cmock_guts_index);
  Mock.prefs_save_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void prefs_save_StubWithCallback(CMOCK_prefs_save_CALLBACK Callback)
{
  Mock.prefs_save_CallbackFunctionPointer = Callback;
}

void prefs_get_global_prefs(GLOBAL_PREFS* global_prefs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_get_global_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_get_global_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_get_global_prefs_CallInstance);
  Mock.prefs_get_global_prefs_CallInstance = CMock_Guts_MemNext(Mock.prefs_get_global_prefs_CallInstance);
  if (Mock.prefs_get_global_prefs_IgnoreBool)
  {
    return;
  }
  if (Mock.prefs_get_global_prefs_CallbackFunctionPointer != NULL)
  {
    Mock.prefs_get_global_prefs_CallbackFunctionPointer(global_prefs, Mock.prefs_get_global_prefs_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_get_global_prefs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_global_prefs), (void*)(global_prefs), sizeof(GLOBAL_PREFS), cmock_line, "Function 'prefs_get_global_prefs' called with unexpected value for argument 'global_prefs'.");
  }
}

void CMockExpectParameters_prefs_get_global_prefs(CMOCK_prefs_get_global_prefs_CALL_INSTANCE* cmock_call_instance, GLOBAL_PREFS* global_prefs)
{
  cmock_call_instance->Expected_global_prefs = global_prefs;
}

void prefs_get_global_prefs_CMockIgnore(void)
{
  Mock.prefs_get_global_prefs_IgnoreBool = (int)1;
}

void prefs_get_global_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, GLOBAL_PREFS* global_prefs)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_get_global_prefs_CALL_INSTANCE));
  CMOCK_prefs_get_global_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_get_global_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_get_global_prefs_CallInstance = CMock_Guts_MemChain(Mock.prefs_get_global_prefs_CallInstance, cmock_guts_index);
  Mock.prefs_get_global_prefs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_prefs_get_global_prefs(cmock_call_instance, global_prefs);
}

void prefs_get_global_prefs_StubWithCallback(CMOCK_prefs_get_global_prefs_CALLBACK Callback)
{
  Mock.prefs_get_global_prefs_CallbackFunctionPointer = Callback;
}

void prefs_set_global_prefs(GLOBAL_PREFS* global_prefs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_set_global_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_set_global_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_set_global_prefs_CallInstance);
  Mock.prefs_set_global_prefs_CallInstance = CMock_Guts_MemNext(Mock.prefs_set_global_prefs_CallInstance);
  if (Mock.prefs_set_global_prefs_IgnoreBool)
  {
    return;
  }
  if (Mock.prefs_set_global_prefs_CallbackFunctionPointer != NULL)
  {
    Mock.prefs_set_global_prefs_CallbackFunctionPointer(global_prefs, Mock.prefs_set_global_prefs_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_set_global_prefs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_global_prefs), (void*)(global_prefs), sizeof(GLOBAL_PREFS), cmock_line, "Function 'prefs_set_global_prefs' called with unexpected value for argument 'global_prefs'.");
  }
}

void CMockExpectParameters_prefs_set_global_prefs(CMOCK_prefs_set_global_prefs_CALL_INSTANCE* cmock_call_instance, GLOBAL_PREFS* global_prefs)
{
  cmock_call_instance->Expected_global_prefs = global_prefs;
}

void prefs_set_global_prefs_CMockIgnore(void)
{
  Mock.prefs_set_global_prefs_IgnoreBool = (int)1;
}

void prefs_set_global_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, GLOBAL_PREFS* global_prefs)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_set_global_prefs_CALL_INSTANCE));
  CMOCK_prefs_set_global_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_set_global_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_set_global_prefs_CallInstance = CMock_Guts_MemChain(Mock.prefs_set_global_prefs_CallInstance, cmock_guts_index);
  Mock.prefs_set_global_prefs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_prefs_set_global_prefs(cmock_call_instance, global_prefs);
}

void prefs_set_global_prefs_StubWithCallback(CMOCK_prefs_set_global_prefs_CALLBACK Callback)
{
  Mock.prefs_set_global_prefs_CallbackFunctionPointer = Callback;
}

void prefs_get_stream_prefs(STREAM_PREFS* prefs, char* label)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_get_stream_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_get_stream_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_get_stream_prefs_CallInstance);
  Mock.prefs_get_stream_prefs_CallInstance = CMock_Guts_MemNext(Mock.prefs_get_stream_prefs_CallInstance);
  if (Mock.prefs_get_stream_prefs_IgnoreBool)
  {
    return;
  }
  if (Mock.prefs_get_stream_prefs_CallbackFunctionPointer != NULL)
  {
    Mock.prefs_get_stream_prefs_CallbackFunctionPointer(prefs, label, Mock.prefs_get_stream_prefs_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_get_stream_prefs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_prefs), (void*)(prefs), sizeof(STREAM_PREFS), cmock_line, "Function 'prefs_get_stream_prefs' called with unexpected value for argument 'prefs'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_label, label, cmock_line, "Function 'prefs_get_stream_prefs' called with unexpected value for argument 'label'.");
  }
}

void CMockExpectParameters_prefs_get_stream_prefs(CMOCK_prefs_get_stream_prefs_CALL_INSTANCE* cmock_call_instance, STREAM_PREFS* prefs, char* label)
{
  cmock_call_instance->Expected_prefs = prefs;
  cmock_call_instance->Expected_label = label;
}

void prefs_get_stream_prefs_CMockIgnore(void)
{
  Mock.prefs_get_stream_prefs_IgnoreBool = (int)1;
}

void prefs_get_stream_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, STREAM_PREFS* prefs, char* label)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_get_stream_prefs_CALL_INSTANCE));
  CMOCK_prefs_get_stream_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_get_stream_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_get_stream_prefs_CallInstance = CMock_Guts_MemChain(Mock.prefs_get_stream_prefs_CallInstance, cmock_guts_index);
  Mock.prefs_get_stream_prefs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_prefs_get_stream_prefs(cmock_call_instance, prefs, label);
}

void prefs_get_stream_prefs_StubWithCallback(CMOCK_prefs_get_stream_prefs_CALLBACK Callback)
{
  Mock.prefs_get_stream_prefs_CallbackFunctionPointer = Callback;
}

void prefs_set_stream_prefs(STREAM_PREFS* prefs, char* label)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_set_stream_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_set_stream_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_set_stream_prefs_CallInstance);
  Mock.prefs_set_stream_prefs_CallInstance = CMock_Guts_MemNext(Mock.prefs_set_stream_prefs_CallInstance);
  if (Mock.prefs_set_stream_prefs_IgnoreBool)
  {
    return;
  }
  if (Mock.prefs_set_stream_prefs_CallbackFunctionPointer != NULL)
  {
    Mock.prefs_set_stream_prefs_CallbackFunctionPointer(prefs, label, Mock.prefs_set_stream_prefs_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_set_stream_prefs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_prefs), (void*)(prefs), sizeof(STREAM_PREFS), cmock_line, "Function 'prefs_set_stream_prefs' called with unexpected value for argument 'prefs'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_label, label, cmock_line, "Function 'prefs_set_stream_prefs' called with unexpected value for argument 'label'.");
  }
}

void CMockExpectParameters_prefs_set_stream_prefs(CMOCK_prefs_set_stream_prefs_CALL_INSTANCE* cmock_call_instance, STREAM_PREFS* prefs, char* label)
{
  cmock_call_instance->Expected_prefs = prefs;
  cmock_call_instance->Expected_label = label;
}

void prefs_set_stream_prefs_CMockIgnore(void)
{
  Mock.prefs_set_stream_prefs_IgnoreBool = (int)1;
}

void prefs_set_stream_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, STREAM_PREFS* prefs, char* label)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_set_stream_prefs_CALL_INSTANCE));
  CMOCK_prefs_set_stream_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_set_stream_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_set_stream_prefs_CallInstance = CMock_Guts_MemChain(Mock.prefs_set_stream_prefs_CallInstance, cmock_guts_index);
  Mock.prefs_set_stream_prefs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_prefs_set_stream_prefs(cmock_call_instance, prefs, label);
}

void prefs_set_stream_prefs_StubWithCallback(CMOCK_prefs_set_stream_prefs_CALLBACK Callback)
{
  Mock.prefs_set_stream_prefs_CallbackFunctionPointer = Callback;
}

void prefs_get_wstreamripper_prefs(WSTREAMRIPPER_PREFS* wsr_prefs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_get_wstreamripper_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_get_wstreamripper_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_get_wstreamripper_prefs_CallInstance);
  Mock.prefs_get_wstreamripper_prefs_CallInstance = CMock_Guts_MemNext(Mock.prefs_get_wstreamripper_prefs_CallInstance);
  if (Mock.prefs_get_wstreamripper_prefs_IgnoreBool)
  {
    return;
  }
  if (Mock.prefs_get_wstreamripper_prefs_CallbackFunctionPointer != NULL)
  {
    Mock.prefs_get_wstreamripper_prefs_CallbackFunctionPointer(wsr_prefs, Mock.prefs_get_wstreamripper_prefs_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_get_wstreamripper_prefs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_wsr_prefs), (void*)(wsr_prefs), sizeof(WSTREAMRIPPER_PREFS), cmock_line, "Function 'prefs_get_wstreamripper_prefs' called with unexpected value for argument 'wsr_prefs'.");
  }
}

void CMockExpectParameters_prefs_get_wstreamripper_prefs(CMOCK_prefs_get_wstreamripper_prefs_CALL_INSTANCE* cmock_call_instance, WSTREAMRIPPER_PREFS* wsr_prefs)
{
  cmock_call_instance->Expected_wsr_prefs = wsr_prefs;
}

void prefs_get_wstreamripper_prefs_CMockIgnore(void)
{
  Mock.prefs_get_wstreamripper_prefs_IgnoreBool = (int)1;
}

void prefs_get_wstreamripper_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, WSTREAMRIPPER_PREFS* wsr_prefs)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_get_wstreamripper_prefs_CALL_INSTANCE));
  CMOCK_prefs_get_wstreamripper_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_get_wstreamripper_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_get_wstreamripper_prefs_CallInstance = CMock_Guts_MemChain(Mock.prefs_get_wstreamripper_prefs_CallInstance, cmock_guts_index);
  Mock.prefs_get_wstreamripper_prefs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_prefs_get_wstreamripper_prefs(cmock_call_instance, wsr_prefs);
}

void prefs_get_wstreamripper_prefs_StubWithCallback(CMOCK_prefs_get_wstreamripper_prefs_CALLBACK Callback)
{
  Mock.prefs_get_wstreamripper_prefs_CallbackFunctionPointer = Callback;
}

void prefs_set_wstreamripper_prefs(WSTREAMRIPPER_PREFS* wsr_prefs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_set_wstreamripper_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_set_wstreamripper_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_set_wstreamripper_prefs_CallInstance);
  Mock.prefs_set_wstreamripper_prefs_CallInstance = CMock_Guts_MemNext(Mock.prefs_set_wstreamripper_prefs_CallInstance);
  if (Mock.prefs_set_wstreamripper_prefs_IgnoreBool)
  {
    return;
  }
  if (Mock.prefs_set_wstreamripper_prefs_CallbackFunctionPointer != NULL)
  {
    Mock.prefs_set_wstreamripper_prefs_CallbackFunctionPointer(wsr_prefs, Mock.prefs_set_wstreamripper_prefs_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_set_wstreamripper_prefs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_wsr_prefs), (void*)(wsr_prefs), sizeof(WSTREAMRIPPER_PREFS), cmock_line, "Function 'prefs_set_wstreamripper_prefs' called with unexpected value for argument 'wsr_prefs'.");
  }
}

void CMockExpectParameters_prefs_set_wstreamripper_prefs(CMOCK_prefs_set_wstreamripper_prefs_CALL_INSTANCE* cmock_call_instance, WSTREAMRIPPER_PREFS* wsr_prefs)
{
  cmock_call_instance->Expected_wsr_prefs = wsr_prefs;
}

void prefs_set_wstreamripper_prefs_CMockIgnore(void)
{
  Mock.prefs_set_wstreamripper_prefs_IgnoreBool = (int)1;
}

void prefs_set_wstreamripper_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, WSTREAMRIPPER_PREFS* wsr_prefs)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_set_wstreamripper_prefs_CALL_INSTANCE));
  CMOCK_prefs_set_wstreamripper_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_set_wstreamripper_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_set_wstreamripper_prefs_CallInstance = CMock_Guts_MemChain(Mock.prefs_set_wstreamripper_prefs_CallInstance, cmock_guts_index);
  Mock.prefs_set_wstreamripper_prefs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_prefs_set_wstreamripper_prefs(cmock_call_instance, wsr_prefs);
}

void prefs_set_wstreamripper_prefs_StubWithCallback(CMOCK_prefs_set_wstreamripper_prefs_CALLBACK Callback)
{
  Mock.prefs_set_wstreamripper_prefs_CallbackFunctionPointer = Callback;
}

bool prefs_is_https(GLOBAL_PREFS* global_prefs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_prefs_is_https_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_is_https_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.prefs_is_https_CallInstance);
  Mock.prefs_is_https_CallInstance = CMock_Guts_MemNext(Mock.prefs_is_https_CallInstance);
  if (Mock.prefs_is_https_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.prefs_is_https_FinalReturn;
    Mock.prefs_is_https_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.prefs_is_https_CallbackFunctionPointer != NULL)
  {
    return Mock.prefs_is_https_CallbackFunctionPointer(global_prefs, Mock.prefs_is_https_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'prefs_is_https' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_global_prefs), (void*)(global_prefs), sizeof(GLOBAL_PREFS), cmock_line, "Function 'prefs_is_https' called with unexpected value for argument 'global_prefs'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_prefs_is_https(CMOCK_prefs_is_https_CALL_INSTANCE* cmock_call_instance, GLOBAL_PREFS* global_prefs)
{
  cmock_call_instance->Expected_global_prefs = global_prefs;
}

void prefs_is_https_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_is_https_CALL_INSTANCE));
  CMOCK_prefs_is_https_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_is_https_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_is_https_CallInstance = CMock_Guts_MemChain(Mock.prefs_is_https_CallInstance, cmock_guts_index);
  Mock.prefs_is_https_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.prefs_is_https_IgnoreBool = (int)1;
}

void prefs_is_https_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, GLOBAL_PREFS* global_prefs, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_prefs_is_https_CALL_INSTANCE));
  CMOCK_prefs_is_https_CALL_INSTANCE* cmock_call_instance = (CMOCK_prefs_is_https_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.prefs_is_https_CallInstance = CMock_Guts_MemChain(Mock.prefs_is_https_CallInstance, cmock_guts_index);
  Mock.prefs_is_https_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_prefs_is_https(cmock_call_instance, global_prefs);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void prefs_is_https_StubWithCallback(CMOCK_prefs_is_https_CALLBACK Callback)
{
  Mock.prefs_is_https_CallbackFunctionPointer = Callback;
}

void debug_stream_prefs(STREAM_PREFS* prefs)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debug_stream_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_stream_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debug_stream_prefs_CallInstance);
  Mock.debug_stream_prefs_CallInstance = CMock_Guts_MemNext(Mock.debug_stream_prefs_CallInstance);
  if (Mock.debug_stream_prefs_IgnoreBool)
  {
    return;
  }
  if (Mock.debug_stream_prefs_CallbackFunctionPointer != NULL)
  {
    Mock.debug_stream_prefs_CallbackFunctionPointer(prefs, Mock.debug_stream_prefs_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'debug_stream_prefs' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_prefs), (void*)(prefs), sizeof(STREAM_PREFS), cmock_line, "Function 'debug_stream_prefs' called with unexpected value for argument 'prefs'.");
  }
}

void CMockExpectParameters_debug_stream_prefs(CMOCK_debug_stream_prefs_CALL_INSTANCE* cmock_call_instance, STREAM_PREFS* prefs)
{
  cmock_call_instance->Expected_prefs = prefs;
}

void debug_stream_prefs_CMockIgnore(void)
{
  Mock.debug_stream_prefs_IgnoreBool = (int)1;
}

void debug_stream_prefs_CMockExpect(UNITY_LINE_TYPE cmock_line, STREAM_PREFS* prefs)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debug_stream_prefs_CALL_INSTANCE));
  CMOCK_debug_stream_prefs_CALL_INSTANCE* cmock_call_instance = (CMOCK_debug_stream_prefs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debug_stream_prefs_CallInstance = CMock_Guts_MemChain(Mock.debug_stream_prefs_CallInstance, cmock_guts_index);
  Mock.debug_stream_prefs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debug_stream_prefs(cmock_call_instance, prefs);
}

void debug_stream_prefs_StubWithCallback(CMOCK_debug_stream_prefs_CALLBACK Callback)
{
  Mock.debug_stream_prefs_CallbackFunctionPointer = Callback;
}

