/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKERRORS_H
#define _MOCKERRORS_H

#include "errors.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockerrors_Init(void);
void Mockerrors_Destroy(void);
void Mockerrors_Verify(void);




#define errors_init_Ignore() errors_init_CMockIgnore()
void errors_init_CMockIgnore(void);
#define errors_init_Expect() errors_init_CMockExpect(__LINE__)
void errors_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_errors_init_CALLBACK)(int cmock_num_calls);
void errors_init_StubWithCallback(CMOCK_errors_init_CALLBACK Callback);
#define errors_get_string_IgnoreAndReturn(cmock_retval) errors_get_string_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void errors_get_string_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return);
#define errors_get_string_ExpectAndReturn(code, cmock_retval) errors_get_string_CMockExpectAndReturn(__LINE__, code, cmock_retval)
void errors_get_string_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, error_code code, char* cmock_to_return);
typedef char* (* CMOCK_errors_get_string_CALLBACK)(error_code code, int cmock_num_calls);
void errors_get_string_StubWithCallback(CMOCK_errors_get_string_CALLBACK Callback);

#endif
