/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPARSE_H
#define _MOCKPARSE_H

#include "parse.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockparse_Init(void);
void Mockparse_Destroy(void);
void Mockparse_Verify(void);




#define init_metadata_parser_Ignore() init_metadata_parser_CMockIgnore()
void init_metadata_parser_CMockIgnore(void);
#define init_metadata_parser_Expect(rmi, rules_file) init_metadata_parser_CMockExpect(__LINE__, rmi, rules_file)
void init_metadata_parser_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, char* rules_file);
typedef void (* CMOCK_init_metadata_parser_CALLBACK)(RIP_MANAGER_INFO* rmi, char* rules_file, int cmock_num_calls);
void init_metadata_parser_StubWithCallback(CMOCK_init_metadata_parser_CALLBACK Callback);
#define parse_metadata_Ignore() parse_metadata_CMockIgnore()
void parse_metadata_CMockIgnore(void);
#define parse_metadata_Expect(rmi, ti) parse_metadata_CMockExpect(__LINE__, rmi, ti)
void parse_metadata_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti);
typedef void (* CMOCK_parse_metadata_CALLBACK)(RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, int cmock_num_calls);
void parse_metadata_StubWithCallback(CMOCK_parse_metadata_CALLBACK Callback);
#define parser_free_Ignore() parser_free_CMockIgnore()
void parser_free_CMockIgnore(void);
#define parser_free_Expect(rmi) parser_free_CMockExpect(__LINE__, rmi)
void parser_free_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi);
typedef void (* CMOCK_parser_free_CALLBACK)(RIP_MANAGER_INFO* rmi, int cmock_num_calls);
void parser_free_StubWithCallback(CMOCK_parser_free_CALLBACK Callback);

#endif
