/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockhttps.h"

typedef struct _CMOCK_https_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_https_init_CALL_INSTANCE;

typedef struct _CMOCK_https_sc_connect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  HTTPS_DATA** Expected_data;
  char* Expected_url;
  char* Expected_proxyurl;
  SR_HTTP_HEADER* Expected_info;
  char* Expected_useragent;
  char* Expected_if_name;

} CMOCK_https_sc_connect_CALL_INSTANCE;

typedef struct _CMOCK_https_get_sc_header_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  HTTPS_DATA* Expected_data;
  char* Expected_url;
  SR_HTTP_HEADER* Expected_info;

} CMOCK_https_get_sc_header_CALL_INSTANCE;

typedef struct _CMOCK_https_sc_read_line_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  HTTPS_DATA* Expected_data;
  char* Expected_buffer;
  size_t Expected_size;

} CMOCK_https_sc_read_line_CALL_INSTANCE;

typedef struct _CMOCK_https_sc_read_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  HTTPS_DATA* Expected_data;
  char* Expected_buffer;
  size_t Expected_size;

} CMOCK_https_sc_read_data_CALL_INSTANCE;

typedef struct _CMOCK_https_sc_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HTTPS_DATA* Expected_data;

} CMOCK_https_sc_close_CALL_INSTANCE;

static struct MockhttpsInstance
{
  int https_init_IgnoreBool;
  CMOCK_https_init_CALLBACK https_init_CallbackFunctionPointer;
  int https_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE https_init_CallInstance;
  int https_sc_connect_IgnoreBool;
  error_code https_sc_connect_FinalReturn;
  CMOCK_https_sc_connect_CALLBACK https_sc_connect_CallbackFunctionPointer;
  int https_sc_connect_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE https_sc_connect_CallInstance;
  int https_get_sc_header_IgnoreBool;
  error_code https_get_sc_header_FinalReturn;
  CMOCK_https_get_sc_header_CALLBACK https_get_sc_header_CallbackFunctionPointer;
  int https_get_sc_header_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE https_get_sc_header_CallInstance;
  int https_sc_read_line_IgnoreBool;
  int https_sc_read_line_FinalReturn;
  CMOCK_https_sc_read_line_CALLBACK https_sc_read_line_CallbackFunctionPointer;
  int https_sc_read_line_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE https_sc_read_line_CallInstance;
  int https_sc_read_data_IgnoreBool;
  int https_sc_read_data_FinalReturn;
  CMOCK_https_sc_read_data_CALLBACK https_sc_read_data_CallbackFunctionPointer;
  int https_sc_read_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE https_sc_read_data_CallInstance;
  int https_sc_close_IgnoreBool;
  CMOCK_https_sc_close_CALLBACK https_sc_close_CallbackFunctionPointer;
  int https_sc_close_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE https_sc_close_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockhttps_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.https_init_IgnoreBool)
    Mock.https_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.https_init_CallInstance, cmock_line, "Function 'https_init' called less times than expected.");
  if (Mock.https_init_CallbackFunctionPointer != NULL)
    Mock.https_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.https_sc_connect_IgnoreBool)
    Mock.https_sc_connect_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.https_sc_connect_CallInstance, cmock_line, "Function 'https_sc_connect' called less times than expected.");
  if (Mock.https_sc_connect_CallbackFunctionPointer != NULL)
    Mock.https_sc_connect_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.https_get_sc_header_IgnoreBool)
    Mock.https_get_sc_header_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.https_get_sc_header_CallInstance, cmock_line, "Function 'https_get_sc_header' called less times than expected.");
  if (Mock.https_get_sc_header_CallbackFunctionPointer != NULL)
    Mock.https_get_sc_header_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.https_sc_read_line_IgnoreBool)
    Mock.https_sc_read_line_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.https_sc_read_line_CallInstance, cmock_line, "Function 'https_sc_read_line' called less times than expected.");
  if (Mock.https_sc_read_line_CallbackFunctionPointer != NULL)
    Mock.https_sc_read_line_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.https_sc_read_data_IgnoreBool)
    Mock.https_sc_read_data_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.https_sc_read_data_CallInstance, cmock_line, "Function 'https_sc_read_data' called less times than expected.");
  if (Mock.https_sc_read_data_CallbackFunctionPointer != NULL)
    Mock.https_sc_read_data_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.https_sc_close_IgnoreBool)
    Mock.https_sc_close_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.https_sc_close_CallInstance, cmock_line, "Function 'https_sc_close' called less times than expected.");
  if (Mock.https_sc_close_CallbackFunctionPointer != NULL)
    Mock.https_sc_close_CallInstance = CMOCK_GUTS_NONE;
}

void Mockhttps_Init(void)
{
  Mockhttps_Destroy();
}

void Mockhttps_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.https_init_CallbackFunctionPointer = NULL;
  Mock.https_init_CallbackCalls = 0;
  Mock.https_sc_connect_CallbackFunctionPointer = NULL;
  Mock.https_sc_connect_CallbackCalls = 0;
  Mock.https_get_sc_header_CallbackFunctionPointer = NULL;
  Mock.https_get_sc_header_CallbackCalls = 0;
  Mock.https_sc_read_line_CallbackFunctionPointer = NULL;
  Mock.https_sc_read_line_CallbackCalls = 0;
  Mock.https_sc_read_data_CallbackFunctionPointer = NULL;
  Mock.https_sc_read_data_CallbackCalls = 0;
  Mock.https_sc_close_CallbackFunctionPointer = NULL;
  Mock.https_sc_close_CallbackCalls = 0;
}

void https_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_https_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.https_init_CallInstance);
  Mock.https_init_CallInstance = CMock_Guts_MemNext(Mock.https_init_CallInstance);
  if (Mock.https_init_IgnoreBool)
  {
    return;
  }
  if (Mock.https_init_CallbackFunctionPointer != NULL)
  {
    Mock.https_init_CallbackFunctionPointer(Mock.https_init_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'https_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void https_init_CMockIgnore(void)
{
  Mock.https_init_IgnoreBool = (int)1;
}

void https_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_init_CALL_INSTANCE));
  CMOCK_https_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_init_CallInstance = CMock_Guts_MemChain(Mock.https_init_CallInstance, cmock_guts_index);
  Mock.https_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void https_init_StubWithCallback(CMOCK_https_init_CALLBACK Callback)
{
  Mock.https_init_CallbackFunctionPointer = Callback;
}

error_code https_sc_connect(RIP_MANAGER_INFO* rmi, HTTPS_DATA** data, const char* url, const char* proxyurl, SR_HTTP_HEADER* info, const char* useragent, const char* if_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_https_sc_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.https_sc_connect_CallInstance);
  Mock.https_sc_connect_CallInstance = CMock_Guts_MemNext(Mock.https_sc_connect_CallInstance);
  if (Mock.https_sc_connect_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.https_sc_connect_FinalReturn;
    memcpy(&Mock.https_sc_connect_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.https_sc_connect_CallbackFunctionPointer != NULL)
  {
    return Mock.https_sc_connect_CallbackFunctionPointer(rmi, data, url, proxyurl, info, useragent, if_name, Mock.https_sc_connect_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'https_sc_connect' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'https_sc_connect' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_data, data, cmock_line, "Function 'https_sc_connect' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_url, url, cmock_line, "Function 'https_sc_connect' called with unexpected value for argument 'url'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_proxyurl, proxyurl, cmock_line, "Function 'https_sc_connect' called with unexpected value for argument 'proxyurl'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_info), (void*)(info), sizeof(SR_HTTP_HEADER), cmock_line, "Function 'https_sc_connect' called with unexpected value for argument 'info'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_useragent, useragent, cmock_line, "Function 'https_sc_connect' called with unexpected value for argument 'useragent'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_if_name, if_name, cmock_line, "Function 'https_sc_connect' called with unexpected value for argument 'if_name'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_https_sc_connect(CMOCK_https_sc_connect_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, HTTPS_DATA** data, const char* url, const char* proxyurl, SR_HTTP_HEADER* info, const char* useragent, const char* if_name)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_url = (char*)url;
  cmock_call_instance->Expected_proxyurl = (char*)proxyurl;
  cmock_call_instance->Expected_info = info;
  cmock_call_instance->Expected_useragent = (char*)useragent;
  cmock_call_instance->Expected_if_name = (char*)if_name;
}

void https_sc_connect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_sc_connect_CALL_INSTANCE));
  CMOCK_https_sc_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_sc_connect_CallInstance = CMock_Guts_MemChain(Mock.https_sc_connect_CallInstance, cmock_guts_index);
  Mock.https_sc_connect_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.https_sc_connect_IgnoreBool = (int)1;
}

void https_sc_connect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, HTTPS_DATA** data, const char* url, const char* proxyurl, SR_HTTP_HEADER* info, const char* useragent, const char* if_name, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_sc_connect_CALL_INSTANCE));
  CMOCK_https_sc_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_sc_connect_CallInstance = CMock_Guts_MemChain(Mock.https_sc_connect_CallInstance, cmock_guts_index);
  Mock.https_sc_connect_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_https_sc_connect(cmock_call_instance, rmi, data, url, proxyurl, info, useragent, if_name);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void https_sc_connect_StubWithCallback(CMOCK_https_sc_connect_CALLBACK Callback)
{
  Mock.https_sc_connect_CallbackFunctionPointer = Callback;
}

error_code https_get_sc_header(RIP_MANAGER_INFO* rmi, HTTPS_DATA* data, const char* url, SR_HTTP_HEADER* info)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_https_get_sc_header_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_get_sc_header_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.https_get_sc_header_CallInstance);
  Mock.https_get_sc_header_CallInstance = CMock_Guts_MemNext(Mock.https_get_sc_header_CallInstance);
  if (Mock.https_get_sc_header_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.https_get_sc_header_FinalReturn;
    memcpy(&Mock.https_get_sc_header_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.https_get_sc_header_CallbackFunctionPointer != NULL)
  {
    return Mock.https_get_sc_header_CallbackFunctionPointer(rmi, data, url, info, Mock.https_get_sc_header_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'https_get_sc_header' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'https_get_sc_header' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(HTTPS_DATA), cmock_line, "Function 'https_get_sc_header' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_url, url, cmock_line, "Function 'https_get_sc_header' called with unexpected value for argument 'url'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_info), (void*)(info), sizeof(SR_HTTP_HEADER), cmock_line, "Function 'https_get_sc_header' called with unexpected value for argument 'info'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_https_get_sc_header(CMOCK_https_get_sc_header_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, HTTPS_DATA* data, const char* url, SR_HTTP_HEADER* info)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_url = (char*)url;
  cmock_call_instance->Expected_info = info;
}

void https_get_sc_header_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_get_sc_header_CALL_INSTANCE));
  CMOCK_https_get_sc_header_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_get_sc_header_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_get_sc_header_CallInstance = CMock_Guts_MemChain(Mock.https_get_sc_header_CallInstance, cmock_guts_index);
  Mock.https_get_sc_header_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.https_get_sc_header_IgnoreBool = (int)1;
}

void https_get_sc_header_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, HTTPS_DATA* data, const char* url, SR_HTTP_HEADER* info, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_get_sc_header_CALL_INSTANCE));
  CMOCK_https_get_sc_header_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_get_sc_header_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_get_sc_header_CallInstance = CMock_Guts_MemChain(Mock.https_get_sc_header_CallInstance, cmock_guts_index);
  Mock.https_get_sc_header_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_https_get_sc_header(cmock_call_instance, rmi, data, url, info);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void https_get_sc_header_StubWithCallback(CMOCK_https_get_sc_header_CALLBACK Callback)
{
  Mock.https_get_sc_header_CallbackFunctionPointer = Callback;
}

int https_sc_read_line(HTTPS_DATA* data, char* buffer, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_https_sc_read_line_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_read_line_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.https_sc_read_line_CallInstance);
  Mock.https_sc_read_line_CallInstance = CMock_Guts_MemNext(Mock.https_sc_read_line_CallInstance);
  if (Mock.https_sc_read_line_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.https_sc_read_line_FinalReturn;
    Mock.https_sc_read_line_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.https_sc_read_line_CallbackFunctionPointer != NULL)
  {
    return Mock.https_sc_read_line_CallbackFunctionPointer(data, buffer, size, Mock.https_sc_read_line_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'https_sc_read_line' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(HTTPS_DATA), cmock_line, "Function 'https_sc_read_line' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, "Function 'https_sc_read_line' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, "Function 'https_sc_read_line' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_https_sc_read_line(CMOCK_https_sc_read_line_CALL_INSTANCE* cmock_call_instance, HTTPS_DATA* data, char* buffer, size_t size)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_buffer = buffer;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(size_t));
}

void https_sc_read_line_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_sc_read_line_CALL_INSTANCE));
  CMOCK_https_sc_read_line_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_read_line_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_sc_read_line_CallInstance = CMock_Guts_MemChain(Mock.https_sc_read_line_CallInstance, cmock_guts_index);
  Mock.https_sc_read_line_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.https_sc_read_line_IgnoreBool = (int)1;
}

void https_sc_read_line_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HTTPS_DATA* data, char* buffer, size_t size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_sc_read_line_CALL_INSTANCE));
  CMOCK_https_sc_read_line_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_read_line_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_sc_read_line_CallInstance = CMock_Guts_MemChain(Mock.https_sc_read_line_CallInstance, cmock_guts_index);
  Mock.https_sc_read_line_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_https_sc_read_line(cmock_call_instance, data, buffer, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void https_sc_read_line_StubWithCallback(CMOCK_https_sc_read_line_CALLBACK Callback)
{
  Mock.https_sc_read_line_CallbackFunctionPointer = Callback;
}

int https_sc_read_data(HTTPS_DATA* data, char* buffer, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_https_sc_read_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_read_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.https_sc_read_data_CallInstance);
  Mock.https_sc_read_data_CallInstance = CMock_Guts_MemNext(Mock.https_sc_read_data_CallInstance);
  if (Mock.https_sc_read_data_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.https_sc_read_data_FinalReturn;
    Mock.https_sc_read_data_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.https_sc_read_data_CallbackFunctionPointer != NULL)
  {
    return Mock.https_sc_read_data_CallbackFunctionPointer(data, buffer, size, Mock.https_sc_read_data_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'https_sc_read_data' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(HTTPS_DATA), cmock_line, "Function 'https_sc_read_data' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, "Function 'https_sc_read_data' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, "Function 'https_sc_read_data' called with unexpected value for argument 'size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_https_sc_read_data(CMOCK_https_sc_read_data_CALL_INSTANCE* cmock_call_instance, HTTPS_DATA* data, char* buffer, size_t size)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_buffer = buffer;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(size_t));
}

void https_sc_read_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_sc_read_data_CALL_INSTANCE));
  CMOCK_https_sc_read_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_read_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_sc_read_data_CallInstance = CMock_Guts_MemChain(Mock.https_sc_read_data_CallInstance, cmock_guts_index);
  Mock.https_sc_read_data_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.https_sc_read_data_IgnoreBool = (int)1;
}

void https_sc_read_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HTTPS_DATA* data, char* buffer, size_t size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_sc_read_data_CALL_INSTANCE));
  CMOCK_https_sc_read_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_read_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_sc_read_data_CallInstance = CMock_Guts_MemChain(Mock.https_sc_read_data_CallInstance, cmock_guts_index);
  Mock.https_sc_read_data_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_https_sc_read_data(cmock_call_instance, data, buffer, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void https_sc_read_data_StubWithCallback(CMOCK_https_sc_read_data_CALLBACK Callback)
{
  Mock.https_sc_read_data_CallbackFunctionPointer = Callback;
}

void https_sc_close(HTTPS_DATA* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_https_sc_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.https_sc_close_CallInstance);
  Mock.https_sc_close_CallInstance = CMock_Guts_MemNext(Mock.https_sc_close_CallInstance);
  if (Mock.https_sc_close_IgnoreBool)
  {
    return;
  }
  if (Mock.https_sc_close_CallbackFunctionPointer != NULL)
  {
    Mock.https_sc_close_CallbackFunctionPointer(data, Mock.https_sc_close_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'https_sc_close' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(HTTPS_DATA), cmock_line, "Function 'https_sc_close' called with unexpected value for argument 'data'.");
  }
}

void CMockExpectParameters_https_sc_close(CMOCK_https_sc_close_CALL_INSTANCE* cmock_call_instance, HTTPS_DATA* data)
{
  cmock_call_instance->Expected_data = data;
}

void https_sc_close_CMockIgnore(void)
{
  Mock.https_sc_close_IgnoreBool = (int)1;
}

void https_sc_close_CMockExpect(UNITY_LINE_TYPE cmock_line, HTTPS_DATA* data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_https_sc_close_CALL_INSTANCE));
  CMOCK_https_sc_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_https_sc_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.https_sc_close_CallInstance = CMock_Guts_MemChain(Mock.https_sc_close_CallInstance, cmock_guts_index);
  Mock.https_sc_close_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_https_sc_close(cmock_call_instance, data);
}

void https_sc_close_StubWithCallback(CMOCK_https_sc_close_CALLBACK Callback)
{
  Mock.https_sc_close_CallbackFunctionPointer = Callback;
}

