/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockfindsep.h"

typedef struct _CMOCK_findsep_silence_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  char* Expected_mpgbuf;
  long Expected_mpgsize;
  long Expected_len_to_sw;
  long Expected_searchwindow;
  long Expected_silence_length;
  long Expected_padding1;
  long Expected_padding2;
  u_long* Expected_pos1;
  u_long* Expected_pos2;

} CMOCK_findsep_silence_CALL_INSTANCE;

typedef struct _CMOCK_findsep_silence_2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  char* Expected_mpgbuf;
  long Expected_mpgsize;
  long Expected_len_to_sw;
  long Expected_searchwindow;
  long Expected_silence_length;
  long Expected_padding1;
  long Expected_padding2;
  u_long* Expected_pos1;
  u_long* Expected_pos2;

} CMOCK_findsep_silence_2_CALL_INSTANCE;

typedef struct _CMOCK_find_bitrate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  unsigned long* Expected_bitrate;
  char* Expected_mpgbuf;
  long Expected_mpgsize;

} CMOCK_find_bitrate_CALL_INSTANCE;

static struct MockfindsepInstance
{
  int findsep_silence_IgnoreBool;
  error_code findsep_silence_FinalReturn;
  CMOCK_findsep_silence_CALLBACK findsep_silence_CallbackFunctionPointer;
  int findsep_silence_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE findsep_silence_CallInstance;
  int findsep_silence_2_IgnoreBool;
  error_code findsep_silence_2_FinalReturn;
  CMOCK_findsep_silence_2_CALLBACK findsep_silence_2_CallbackFunctionPointer;
  int findsep_silence_2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE findsep_silence_2_CallInstance;
  int find_bitrate_IgnoreBool;
  error_code find_bitrate_FinalReturn;
  CMOCK_find_bitrate_CALLBACK find_bitrate_CallbackFunctionPointer;
  int find_bitrate_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE find_bitrate_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfindsep_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.findsep_silence_IgnoreBool)
    Mock.findsep_silence_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.findsep_silence_CallInstance, cmock_line, "Function 'findsep_silence' called less times than expected.");
  if (Mock.findsep_silence_CallbackFunctionPointer != NULL)
    Mock.findsep_silence_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.findsep_silence_2_IgnoreBool)
    Mock.findsep_silence_2_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.findsep_silence_2_CallInstance, cmock_line, "Function 'findsep_silence_2' called less times than expected.");
  if (Mock.findsep_silence_2_CallbackFunctionPointer != NULL)
    Mock.findsep_silence_2_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.find_bitrate_IgnoreBool)
    Mock.find_bitrate_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.find_bitrate_CallInstance, cmock_line, "Function 'find_bitrate' called less times than expected.");
  if (Mock.find_bitrate_CallbackFunctionPointer != NULL)
    Mock.find_bitrate_CallInstance = CMOCK_GUTS_NONE;
}

void Mockfindsep_Init(void)
{
  Mockfindsep_Destroy();
}

void Mockfindsep_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.findsep_silence_CallbackFunctionPointer = NULL;
  Mock.findsep_silence_CallbackCalls = 0;
  Mock.findsep_silence_2_CallbackFunctionPointer = NULL;
  Mock.findsep_silence_2_CallbackCalls = 0;
  Mock.find_bitrate_CallbackFunctionPointer = NULL;
  Mock.find_bitrate_CallbackCalls = 0;
}

error_code findsep_silence(const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_findsep_silence_CALL_INSTANCE* cmock_call_instance = (CMOCK_findsep_silence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.findsep_silence_CallInstance);
  Mock.findsep_silence_CallInstance = CMock_Guts_MemNext(Mock.findsep_silence_CallInstance);
  if (Mock.findsep_silence_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.findsep_silence_FinalReturn;
    memcpy(&Mock.findsep_silence_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.findsep_silence_CallbackFunctionPointer != NULL)
  {
    return Mock.findsep_silence_CallbackFunctionPointer(mpgbuf, mpgsize, len_to_sw, searchwindow, silence_length, padding1, padding2, pos1, pos2, Mock.findsep_silence_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'findsep_silence' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_mpgbuf, mpgbuf, cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'mpgbuf'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_mpgsize, mpgsize, cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'mpgsize'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_len_to_sw, len_to_sw, cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'len_to_sw'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_searchwindow, searchwindow, cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'searchwindow'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_silence_length, silence_length, cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'silence_length'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_padding1, padding1, cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'padding1'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_padding2, padding2, cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'padding2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pos1), (void*)(pos1), sizeof(u_long), cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'pos1'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pos2), (void*)(pos2), sizeof(u_long), cmock_line, "Function 'findsep_silence' called with unexpected value for argument 'pos2'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_findsep_silence(CMOCK_findsep_silence_CALL_INSTANCE* cmock_call_instance, const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2)
{
  cmock_call_instance->Expected_mpgbuf = (char*)mpgbuf;
  cmock_call_instance->Expected_mpgsize = mpgsize;
  cmock_call_instance->Expected_len_to_sw = len_to_sw;
  cmock_call_instance->Expected_searchwindow = searchwindow;
  cmock_call_instance->Expected_silence_length = silence_length;
  cmock_call_instance->Expected_padding1 = padding1;
  cmock_call_instance->Expected_padding2 = padding2;
  cmock_call_instance->Expected_pos1 = pos1;
  cmock_call_instance->Expected_pos2 = pos2;
}

void findsep_silence_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_findsep_silence_CALL_INSTANCE));
  CMOCK_findsep_silence_CALL_INSTANCE* cmock_call_instance = (CMOCK_findsep_silence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.findsep_silence_CallInstance = CMock_Guts_MemChain(Mock.findsep_silence_CallInstance, cmock_guts_index);
  Mock.findsep_silence_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.findsep_silence_IgnoreBool = (int)1;
}

void findsep_silence_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_findsep_silence_CALL_INSTANCE));
  CMOCK_findsep_silence_CALL_INSTANCE* cmock_call_instance = (CMOCK_findsep_silence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.findsep_silence_CallInstance = CMock_Guts_MemChain(Mock.findsep_silence_CallInstance, cmock_guts_index);
  Mock.findsep_silence_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_findsep_silence(cmock_call_instance, mpgbuf, mpgsize, len_to_sw, searchwindow, silence_length, padding1, padding2, pos1, pos2);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void findsep_silence_StubWithCallback(CMOCK_findsep_silence_CALLBACK Callback)
{
  Mock.findsep_silence_CallbackFunctionPointer = Callback;
}

error_code findsep_silence_2(const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_findsep_silence_2_CALL_INSTANCE* cmock_call_instance = (CMOCK_findsep_silence_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.findsep_silence_2_CallInstance);
  Mock.findsep_silence_2_CallInstance = CMock_Guts_MemNext(Mock.findsep_silence_2_CallInstance);
  if (Mock.findsep_silence_2_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.findsep_silence_2_FinalReturn;
    memcpy(&Mock.findsep_silence_2_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.findsep_silence_2_CallbackFunctionPointer != NULL)
  {
    return Mock.findsep_silence_2_CallbackFunctionPointer(mpgbuf, mpgsize, len_to_sw, searchwindow, silence_length, padding1, padding2, pos1, pos2, Mock.findsep_silence_2_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'findsep_silence_2' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_mpgbuf, mpgbuf, cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'mpgbuf'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_mpgsize, mpgsize, cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'mpgsize'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_len_to_sw, len_to_sw, cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'len_to_sw'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_searchwindow, searchwindow, cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'searchwindow'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_silence_length, silence_length, cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'silence_length'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_padding1, padding1, cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'padding1'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_padding2, padding2, cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'padding2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pos1), (void*)(pos1), sizeof(u_long), cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'pos1'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pos2), (void*)(pos2), sizeof(u_long), cmock_line, "Function 'findsep_silence_2' called with unexpected value for argument 'pos2'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_findsep_silence_2(CMOCK_findsep_silence_2_CALL_INSTANCE* cmock_call_instance, const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2)
{
  cmock_call_instance->Expected_mpgbuf = (char*)mpgbuf;
  cmock_call_instance->Expected_mpgsize = mpgsize;
  cmock_call_instance->Expected_len_to_sw = len_to_sw;
  cmock_call_instance->Expected_searchwindow = searchwindow;
  cmock_call_instance->Expected_silence_length = silence_length;
  cmock_call_instance->Expected_padding1 = padding1;
  cmock_call_instance->Expected_padding2 = padding2;
  cmock_call_instance->Expected_pos1 = pos1;
  cmock_call_instance->Expected_pos2 = pos2;
}

void findsep_silence_2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_findsep_silence_2_CALL_INSTANCE));
  CMOCK_findsep_silence_2_CALL_INSTANCE* cmock_call_instance = (CMOCK_findsep_silence_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.findsep_silence_2_CallInstance = CMock_Guts_MemChain(Mock.findsep_silence_2_CallInstance, cmock_guts_index);
  Mock.findsep_silence_2_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.findsep_silence_2_IgnoreBool = (int)1;
}

void findsep_silence_2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* mpgbuf, long mpgsize, long len_to_sw, long searchwindow, long silence_length, long padding1, long padding2, u_long* pos1, u_long* pos2, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_findsep_silence_2_CALL_INSTANCE));
  CMOCK_findsep_silence_2_CALL_INSTANCE* cmock_call_instance = (CMOCK_findsep_silence_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.findsep_silence_2_CallInstance = CMock_Guts_MemChain(Mock.findsep_silence_2_CallInstance, cmock_guts_index);
  Mock.findsep_silence_2_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_findsep_silence_2(cmock_call_instance, mpgbuf, mpgsize, len_to_sw, searchwindow, silence_length, padding1, padding2, pos1, pos2);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void findsep_silence_2_StubWithCallback(CMOCK_findsep_silence_2_CALLBACK Callback)
{
  Mock.findsep_silence_2_CallbackFunctionPointer = Callback;
}

error_code find_bitrate(unsigned long* bitrate, const char* mpgbuf, long mpgsize)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_find_bitrate_CALL_INSTANCE* cmock_call_instance = (CMOCK_find_bitrate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.find_bitrate_CallInstance);
  Mock.find_bitrate_CallInstance = CMock_Guts_MemNext(Mock.find_bitrate_CallInstance);
  if (Mock.find_bitrate_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.find_bitrate_FinalReturn;
    memcpy(&Mock.find_bitrate_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.find_bitrate_CallbackFunctionPointer != NULL)
  {
    return Mock.find_bitrate_CallbackFunctionPointer(bitrate, mpgbuf, mpgsize, Mock.find_bitrate_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'find_bitrate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    if (cmock_call_instance->Expected_bitrate == NULL)
      { UNITY_TEST_ASSERT_NULL(bitrate, cmock_line, "Expected NULL. Function 'find_bitrate' called with unexpected value for argument 'bitrate'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_bitrate, bitrate, 1, cmock_line, "Function 'find_bitrate' called with unexpected value for argument 'bitrate'."); }
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_mpgbuf, mpgbuf, cmock_line, "Function 'find_bitrate' called with unexpected value for argument 'mpgbuf'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_mpgsize, mpgsize, cmock_line, "Function 'find_bitrate' called with unexpected value for argument 'mpgsize'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_find_bitrate(CMOCK_find_bitrate_CALL_INSTANCE* cmock_call_instance, unsigned long* bitrate, const char* mpgbuf, long mpgsize)
{
  cmock_call_instance->Expected_bitrate = bitrate;
  cmock_call_instance->Expected_mpgbuf = (char*)mpgbuf;
  cmock_call_instance->Expected_mpgsize = mpgsize;
}

void find_bitrate_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_find_bitrate_CALL_INSTANCE));
  CMOCK_find_bitrate_CALL_INSTANCE* cmock_call_instance = (CMOCK_find_bitrate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.find_bitrate_CallInstance = CMock_Guts_MemChain(Mock.find_bitrate_CallInstance, cmock_guts_index);
  Mock.find_bitrate_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.find_bitrate_IgnoreBool = (int)1;
}

void find_bitrate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned long* bitrate, const char* mpgbuf, long mpgsize, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_find_bitrate_CALL_INSTANCE));
  CMOCK_find_bitrate_CALL_INSTANCE* cmock_call_instance = (CMOCK_find_bitrate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.find_bitrate_CallInstance = CMock_Guts_MemChain(Mock.find_bitrate_CallInstance, cmock_guts_index);
  Mock.find_bitrate_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_find_bitrate(cmock_call_instance, bitrate, mpgbuf, mpgsize);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void find_bitrate_StubWithCallback(CMOCK_find_bitrate_CALLBACK Callback)
{
  Mock.find_bitrate_CallbackFunctionPointer = Callback;
}

