/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockparse.h"

typedef struct _CMOCK_init_metadata_parser_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RIP_MANAGER_INFO* Expected_rmi;
  char* Expected_rules_file;

} CMOCK_init_metadata_parser_CALL_INSTANCE;

typedef struct _CMOCK_parse_metadata_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RIP_MANAGER_INFO* Expected_rmi;
  TRACK_INFO* Expected_ti;

} CMOCK_parse_metadata_CALL_INSTANCE;

typedef struct _CMOCK_parser_free_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RIP_MANAGER_INFO* Expected_rmi;

} CMOCK_parser_free_CALL_INSTANCE;

static struct MockparseInstance
{
  int init_metadata_parser_IgnoreBool;
  CMOCK_init_metadata_parser_CALLBACK init_metadata_parser_CallbackFunctionPointer;
  int init_metadata_parser_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE init_metadata_parser_CallInstance;
  int parse_metadata_IgnoreBool;
  CMOCK_parse_metadata_CALLBACK parse_metadata_CallbackFunctionPointer;
  int parse_metadata_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE parse_metadata_CallInstance;
  int parser_free_IgnoreBool;
  CMOCK_parser_free_CALLBACK parser_free_CallbackFunctionPointer;
  int parser_free_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE parser_free_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockparse_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.init_metadata_parser_IgnoreBool)
    Mock.init_metadata_parser_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.init_metadata_parser_CallInstance, cmock_line, "Function 'init_metadata_parser' called less times than expected.");
  if (Mock.init_metadata_parser_CallbackFunctionPointer != NULL)
    Mock.init_metadata_parser_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.parse_metadata_IgnoreBool)
    Mock.parse_metadata_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.parse_metadata_CallInstance, cmock_line, "Function 'parse_metadata' called less times than expected.");
  if (Mock.parse_metadata_CallbackFunctionPointer != NULL)
    Mock.parse_metadata_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.parser_free_IgnoreBool)
    Mock.parser_free_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.parser_free_CallInstance, cmock_line, "Function 'parser_free' called less times than expected.");
  if (Mock.parser_free_CallbackFunctionPointer != NULL)
    Mock.parser_free_CallInstance = CMOCK_GUTS_NONE;
}

void Mockparse_Init(void)
{
  Mockparse_Destroy();
}

void Mockparse_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.init_metadata_parser_CallbackFunctionPointer = NULL;
  Mock.init_metadata_parser_CallbackCalls = 0;
  Mock.parse_metadata_CallbackFunctionPointer = NULL;
  Mock.parse_metadata_CallbackCalls = 0;
  Mock.parser_free_CallbackFunctionPointer = NULL;
  Mock.parser_free_CallbackCalls = 0;
}

void init_metadata_parser(RIP_MANAGER_INFO* rmi, char* rules_file)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_init_metadata_parser_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_metadata_parser_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.init_metadata_parser_CallInstance);
  Mock.init_metadata_parser_CallInstance = CMock_Guts_MemNext(Mock.init_metadata_parser_CallInstance);
  if (Mock.init_metadata_parser_IgnoreBool)
  {
    return;
  }
  if (Mock.init_metadata_parser_CallbackFunctionPointer != NULL)
  {
    Mock.init_metadata_parser_CallbackFunctionPointer(rmi, rules_file, Mock.init_metadata_parser_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'init_metadata_parser' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'init_metadata_parser' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_rules_file, rules_file, cmock_line, "Function 'init_metadata_parser' called with unexpected value for argument 'rules_file'.");
  }
}

void CMockExpectParameters_init_metadata_parser(CMOCK_init_metadata_parser_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, char* rules_file)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_rules_file = rules_file;
}

void init_metadata_parser_CMockIgnore(void)
{
  Mock.init_metadata_parser_IgnoreBool = (int)1;
}

void init_metadata_parser_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, char* rules_file)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_metadata_parser_CALL_INSTANCE));
  CMOCK_init_metadata_parser_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_metadata_parser_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_metadata_parser_CallInstance = CMock_Guts_MemChain(Mock.init_metadata_parser_CallInstance, cmock_guts_index);
  Mock.init_metadata_parser_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_init_metadata_parser(cmock_call_instance, rmi, rules_file);
}

void init_metadata_parser_StubWithCallback(CMOCK_init_metadata_parser_CALLBACK Callback)
{
  Mock.init_metadata_parser_CallbackFunctionPointer = Callback;
}

void parse_metadata(RIP_MANAGER_INFO* rmi, TRACK_INFO* ti)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_parse_metadata_CALL_INSTANCE* cmock_call_instance = (CMOCK_parse_metadata_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.parse_metadata_CallInstance);
  Mock.parse_metadata_CallInstance = CMock_Guts_MemNext(Mock.parse_metadata_CallInstance);
  if (Mock.parse_metadata_IgnoreBool)
  {
    return;
  }
  if (Mock.parse_metadata_CallbackFunctionPointer != NULL)
  {
    Mock.parse_metadata_CallbackFunctionPointer(rmi, ti, Mock.parse_metadata_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'parse_metadata' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'parse_metadata' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ti), (void*)(ti), sizeof(TRACK_INFO), cmock_line, "Function 'parse_metadata' called with unexpected value for argument 'ti'.");
  }
}

void CMockExpectParameters_parse_metadata(CMOCK_parse_metadata_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_ti = ti;
}

void parse_metadata_CMockIgnore(void)
{
  Mock.parse_metadata_IgnoreBool = (int)1;
}

void parse_metadata_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_parse_metadata_CALL_INSTANCE));
  CMOCK_parse_metadata_CALL_INSTANCE* cmock_call_instance = (CMOCK_parse_metadata_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.parse_metadata_CallInstance = CMock_Guts_MemChain(Mock.parse_metadata_CallInstance, cmock_guts_index);
  Mock.parse_metadata_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_parse_metadata(cmock_call_instance, rmi, ti);
}

void parse_metadata_StubWithCallback(CMOCK_parse_metadata_CALLBACK Callback)
{
  Mock.parse_metadata_CallbackFunctionPointer = Callback;
}

void parser_free(RIP_MANAGER_INFO* rmi)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_parser_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_parser_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.parser_free_CallInstance);
  Mock.parser_free_CallInstance = CMock_Guts_MemNext(Mock.parser_free_CallInstance);
  if (Mock.parser_free_IgnoreBool)
  {
    return;
  }
  if (Mock.parser_free_CallbackFunctionPointer != NULL)
  {
    Mock.parser_free_CallbackFunctionPointer(rmi, Mock.parser_free_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'parser_free' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'parser_free' called with unexpected value for argument 'rmi'.");
  }
}

void CMockExpectParameters_parser_free(CMOCK_parser_free_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi)
{
  cmock_call_instance->Expected_rmi = rmi;
}

void parser_free_CMockIgnore(void)
{
  Mock.parser_free_IgnoreBool = (int)1;
}

void parser_free_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_parser_free_CALL_INSTANCE));
  CMOCK_parser_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_parser_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.parser_free_CallInstance = CMock_Guts_MemChain(Mock.parser_free_CallInstance, cmock_guts_index);
  Mock.parser_free_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_parser_free(cmock_call_instance, rmi);
}

void parser_free_StubWithCallback(CMOCK_parser_free_CALLBACK Callback)
{
  Mock.parser_free_CallbackFunctionPointer = Callback;
}

