/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockcbuf2.h"

typedef struct _CMOCK_cbuf2_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  CBUF2* Expected_cbuf2;
  int Expected_content_type;
  int Expected_have_relay;
  unsigned long Expected_chunk_size;
  unsigned long Expected_num_chunks;

} CMOCK_cbuf2_init_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CBUF2* Expected_buffer;

} CMOCK_cbuf2_destroy_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_extract_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  CBUF2* Expected_cbuf2;
  char* Expected_data;
  u_long Expected_count;
  u_long* Expected_curr_song;

} CMOCK_cbuf2_extract_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_peek_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  CBUF2* Expected_buffer;
  char* Expected_items;
  u_long Expected_count;

} CMOCK_cbuf2_peek_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_insert_chunk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  CBUF2* Expected_cbuf2;
  char* Expected_data;
  u_long Expected_count;
  int Expected_content_type;
  TRACK_INFO* Expected_ti;

} CMOCK_cbuf2_insert_chunk_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_fastforward_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  CBUF2* Expected_buffer;
  u_long Expected_count;

} CMOCK_cbuf2_fastforward_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_peek_rgn_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  CBUF2* Expected_buffer;
  char* Expected_out_buf;
  u_long Expected_start;
  u_long Expected_length;

} CMOCK_cbuf2_peek_rgn_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_get_free_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  u_long ReturnVal;
  CBUF2* Expected_buffer;

} CMOCK_cbuf2_get_free_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_get_free_tail_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  u_long ReturnVal;
  CBUF2* Expected_cbuf2;

} CMOCK_cbuf2_get_free_tail_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_write_index_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  u_long ReturnVal;
  CBUF2* Expected_cbuf2;

} CMOCK_cbuf2_write_index_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_set_next_song_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CBUF2* Expected_cbuf2;
  u_long Expected_pos;

} CMOCK_cbuf2_set_next_song_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  CBUF2* Expected_cbuf2;
  RELAY_LIST* Expected_ptr;
  u_long Expected_burst_request;

} CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  CBUF2* Expected_cbuf2;
  char* Expected_out_buf;
  unsigned long Expected_buf_size;
  unsigned long* Expected_amt_filled;
  int* Expected_eos;

} CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_extract_relay_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  CBUF2* Expected_cbuf2;
  char* Expected_data;
  u_long* Expected_pos;
  u_long* Expected_len;
  int Expected_icy_metadata;

} CMOCK_cbuf2_extract_relay_CALL_INSTANCE;

typedef struct _CMOCK_cbuf2_advance_ogg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  RIP_MANAGER_INFO* Expected_rmi;
  CBUF2* Expected_cbuf2;
  int Expected_requested_free_size;

} CMOCK_cbuf2_advance_ogg_CALL_INSTANCE;

static struct Mockcbuf2Instance
{
  int cbuf2_init_IgnoreBool;
  error_code cbuf2_init_FinalReturn;
  CMOCK_cbuf2_init_CALLBACK cbuf2_init_CallbackFunctionPointer;
  int cbuf2_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_init_CallInstance;
  int cbuf2_destroy_IgnoreBool;
  CMOCK_cbuf2_destroy_CALLBACK cbuf2_destroy_CallbackFunctionPointer;
  int cbuf2_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_destroy_CallInstance;
  int cbuf2_extract_IgnoreBool;
  error_code cbuf2_extract_FinalReturn;
  CMOCK_cbuf2_extract_CALLBACK cbuf2_extract_CallbackFunctionPointer;
  int cbuf2_extract_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_extract_CallInstance;
  int cbuf2_peek_IgnoreBool;
  error_code cbuf2_peek_FinalReturn;
  CMOCK_cbuf2_peek_CALLBACK cbuf2_peek_CallbackFunctionPointer;
  int cbuf2_peek_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_peek_CallInstance;
  int cbuf2_insert_chunk_IgnoreBool;
  error_code cbuf2_insert_chunk_FinalReturn;
  CMOCK_cbuf2_insert_chunk_CALLBACK cbuf2_insert_chunk_CallbackFunctionPointer;
  int cbuf2_insert_chunk_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_insert_chunk_CallInstance;
  int cbuf2_fastforward_IgnoreBool;
  error_code cbuf2_fastforward_FinalReturn;
  CMOCK_cbuf2_fastforward_CALLBACK cbuf2_fastforward_CallbackFunctionPointer;
  int cbuf2_fastforward_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_fastforward_CallInstance;
  int cbuf2_peek_rgn_IgnoreBool;
  error_code cbuf2_peek_rgn_FinalReturn;
  CMOCK_cbuf2_peek_rgn_CALLBACK cbuf2_peek_rgn_CallbackFunctionPointer;
  int cbuf2_peek_rgn_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_peek_rgn_CallInstance;
  int cbuf2_get_free_IgnoreBool;
  u_long cbuf2_get_free_FinalReturn;
  CMOCK_cbuf2_get_free_CALLBACK cbuf2_get_free_CallbackFunctionPointer;
  int cbuf2_get_free_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_get_free_CallInstance;
  int cbuf2_get_free_tail_IgnoreBool;
  u_long cbuf2_get_free_tail_FinalReturn;
  CMOCK_cbuf2_get_free_tail_CALLBACK cbuf2_get_free_tail_CallbackFunctionPointer;
  int cbuf2_get_free_tail_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_get_free_tail_CallInstance;
  int cbuf2_write_index_IgnoreBool;
  u_long cbuf2_write_index_FinalReturn;
  CMOCK_cbuf2_write_index_CALLBACK cbuf2_write_index_CallbackFunctionPointer;
  int cbuf2_write_index_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_write_index_CallInstance;
  int cbuf2_set_next_song_IgnoreBool;
  CMOCK_cbuf2_set_next_song_CALLBACK cbuf2_set_next_song_CallbackFunctionPointer;
  int cbuf2_set_next_song_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_set_next_song_CallInstance;
  int cbuf2_init_relay_entry_IgnoreBool;
  error_code cbuf2_init_relay_entry_FinalReturn;
  CMOCK_cbuf2_init_relay_entry_CALLBACK cbuf2_init_relay_entry_CallbackFunctionPointer;
  int cbuf2_init_relay_entry_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_init_relay_entry_CallInstance;
  int cbuf2_ogg_peek_song_IgnoreBool;
  error_code cbuf2_ogg_peek_song_FinalReturn;
  CMOCK_cbuf2_ogg_peek_song_CALLBACK cbuf2_ogg_peek_song_CallbackFunctionPointer;
  int cbuf2_ogg_peek_song_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_ogg_peek_song_CallInstance;
  int cbuf2_extract_relay_IgnoreBool;
  error_code cbuf2_extract_relay_FinalReturn;
  CMOCK_cbuf2_extract_relay_CALLBACK cbuf2_extract_relay_CallbackFunctionPointer;
  int cbuf2_extract_relay_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_extract_relay_CallInstance;
  int cbuf2_advance_ogg_IgnoreBool;
  error_code cbuf2_advance_ogg_FinalReturn;
  CMOCK_cbuf2_advance_ogg_CALLBACK cbuf2_advance_ogg_CallbackFunctionPointer;
  int cbuf2_advance_ogg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cbuf2_advance_ogg_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcbuf2_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.cbuf2_init_IgnoreBool)
    Mock.cbuf2_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_init_CallInstance, cmock_line, "Function 'cbuf2_init' called less times than expected.");
  if (Mock.cbuf2_init_CallbackFunctionPointer != NULL)
    Mock.cbuf2_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_destroy_IgnoreBool)
    Mock.cbuf2_destroy_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_destroy_CallInstance, cmock_line, "Function 'cbuf2_destroy' called less times than expected.");
  if (Mock.cbuf2_destroy_CallbackFunctionPointer != NULL)
    Mock.cbuf2_destroy_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_extract_IgnoreBool)
    Mock.cbuf2_extract_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_extract_CallInstance, cmock_line, "Function 'cbuf2_extract' called less times than expected.");
  if (Mock.cbuf2_extract_CallbackFunctionPointer != NULL)
    Mock.cbuf2_extract_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_peek_IgnoreBool)
    Mock.cbuf2_peek_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_peek_CallInstance, cmock_line, "Function 'cbuf2_peek' called less times than expected.");
  if (Mock.cbuf2_peek_CallbackFunctionPointer != NULL)
    Mock.cbuf2_peek_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_insert_chunk_IgnoreBool)
    Mock.cbuf2_insert_chunk_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_insert_chunk_CallInstance, cmock_line, "Function 'cbuf2_insert_chunk' called less times than expected.");
  if (Mock.cbuf2_insert_chunk_CallbackFunctionPointer != NULL)
    Mock.cbuf2_insert_chunk_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_fastforward_IgnoreBool)
    Mock.cbuf2_fastforward_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_fastforward_CallInstance, cmock_line, "Function 'cbuf2_fastforward' called less times than expected.");
  if (Mock.cbuf2_fastforward_CallbackFunctionPointer != NULL)
    Mock.cbuf2_fastforward_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_peek_rgn_IgnoreBool)
    Mock.cbuf2_peek_rgn_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_peek_rgn_CallInstance, cmock_line, "Function 'cbuf2_peek_rgn' called less times than expected.");
  if (Mock.cbuf2_peek_rgn_CallbackFunctionPointer != NULL)
    Mock.cbuf2_peek_rgn_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_get_free_IgnoreBool)
    Mock.cbuf2_get_free_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_get_free_CallInstance, cmock_line, "Function 'cbuf2_get_free' called less times than expected.");
  if (Mock.cbuf2_get_free_CallbackFunctionPointer != NULL)
    Mock.cbuf2_get_free_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_get_free_tail_IgnoreBool)
    Mock.cbuf2_get_free_tail_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_get_free_tail_CallInstance, cmock_line, "Function 'cbuf2_get_free_tail' called less times than expected.");
  if (Mock.cbuf2_get_free_tail_CallbackFunctionPointer != NULL)
    Mock.cbuf2_get_free_tail_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_write_index_IgnoreBool)
    Mock.cbuf2_write_index_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_write_index_CallInstance, cmock_line, "Function 'cbuf2_write_index' called less times than expected.");
  if (Mock.cbuf2_write_index_CallbackFunctionPointer != NULL)
    Mock.cbuf2_write_index_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_set_next_song_IgnoreBool)
    Mock.cbuf2_set_next_song_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_set_next_song_CallInstance, cmock_line, "Function 'cbuf2_set_next_song' called less times than expected.");
  if (Mock.cbuf2_set_next_song_CallbackFunctionPointer != NULL)
    Mock.cbuf2_set_next_song_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_init_relay_entry_IgnoreBool)
    Mock.cbuf2_init_relay_entry_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_init_relay_entry_CallInstance, cmock_line, "Function 'cbuf2_init_relay_entry' called less times than expected.");
  if (Mock.cbuf2_init_relay_entry_CallbackFunctionPointer != NULL)
    Mock.cbuf2_init_relay_entry_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_ogg_peek_song_IgnoreBool)
    Mock.cbuf2_ogg_peek_song_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_ogg_peek_song_CallInstance, cmock_line, "Function 'cbuf2_ogg_peek_song' called less times than expected.");
  if (Mock.cbuf2_ogg_peek_song_CallbackFunctionPointer != NULL)
    Mock.cbuf2_ogg_peek_song_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_extract_relay_IgnoreBool)
    Mock.cbuf2_extract_relay_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_extract_relay_CallInstance, cmock_line, "Function 'cbuf2_extract_relay' called less times than expected.");
  if (Mock.cbuf2_extract_relay_CallbackFunctionPointer != NULL)
    Mock.cbuf2_extract_relay_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cbuf2_advance_ogg_IgnoreBool)
    Mock.cbuf2_advance_ogg_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cbuf2_advance_ogg_CallInstance, cmock_line, "Function 'cbuf2_advance_ogg' called less times than expected.");
  if (Mock.cbuf2_advance_ogg_CallbackFunctionPointer != NULL)
    Mock.cbuf2_advance_ogg_CallInstance = CMOCK_GUTS_NONE;
}

void Mockcbuf2_Init(void)
{
  Mockcbuf2_Destroy();
}

void Mockcbuf2_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.cbuf2_init_CallbackFunctionPointer = NULL;
  Mock.cbuf2_init_CallbackCalls = 0;
  Mock.cbuf2_destroy_CallbackFunctionPointer = NULL;
  Mock.cbuf2_destroy_CallbackCalls = 0;
  Mock.cbuf2_extract_CallbackFunctionPointer = NULL;
  Mock.cbuf2_extract_CallbackCalls = 0;
  Mock.cbuf2_peek_CallbackFunctionPointer = NULL;
  Mock.cbuf2_peek_CallbackCalls = 0;
  Mock.cbuf2_insert_chunk_CallbackFunctionPointer = NULL;
  Mock.cbuf2_insert_chunk_CallbackCalls = 0;
  Mock.cbuf2_fastforward_CallbackFunctionPointer = NULL;
  Mock.cbuf2_fastforward_CallbackCalls = 0;
  Mock.cbuf2_peek_rgn_CallbackFunctionPointer = NULL;
  Mock.cbuf2_peek_rgn_CallbackCalls = 0;
  Mock.cbuf2_get_free_CallbackFunctionPointer = NULL;
  Mock.cbuf2_get_free_CallbackCalls = 0;
  Mock.cbuf2_get_free_tail_CallbackFunctionPointer = NULL;
  Mock.cbuf2_get_free_tail_CallbackCalls = 0;
  Mock.cbuf2_write_index_CallbackFunctionPointer = NULL;
  Mock.cbuf2_write_index_CallbackCalls = 0;
  Mock.cbuf2_set_next_song_CallbackFunctionPointer = NULL;
  Mock.cbuf2_set_next_song_CallbackCalls = 0;
  Mock.cbuf2_init_relay_entry_CallbackFunctionPointer = NULL;
  Mock.cbuf2_init_relay_entry_CallbackCalls = 0;
  Mock.cbuf2_ogg_peek_song_CallbackFunctionPointer = NULL;
  Mock.cbuf2_ogg_peek_song_CallbackCalls = 0;
  Mock.cbuf2_extract_relay_CallbackFunctionPointer = NULL;
  Mock.cbuf2_extract_relay_CallbackCalls = 0;
  Mock.cbuf2_advance_ogg_CallbackFunctionPointer = NULL;
  Mock.cbuf2_advance_ogg_CallbackCalls = 0;
}

error_code cbuf2_init(CBUF2* cbuf2, int content_type, int have_relay, unsigned long chunk_size, unsigned long num_chunks)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_init_CallInstance);
  Mock.cbuf2_init_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_init_CallInstance);
  if (Mock.cbuf2_init_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_init_FinalReturn;
    memcpy(&Mock.cbuf2_init_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_init_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_init_CallbackFunctionPointer(cbuf2, content_type, have_relay, chunk_size, num_chunks, Mock.cbuf2_init_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_init' called with unexpected value for argument 'cbuf2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_content_type, content_type, cmock_line, "Function 'cbuf2_init' called with unexpected value for argument 'content_type'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_have_relay, have_relay, cmock_line, "Function 'cbuf2_init' called with unexpected value for argument 'have_relay'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_chunk_size, chunk_size, cmock_line, "Function 'cbuf2_init' called with unexpected value for argument 'chunk_size'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_num_chunks, num_chunks, cmock_line, "Function 'cbuf2_init' called with unexpected value for argument 'num_chunks'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_init(CMOCK_cbuf2_init_CALL_INSTANCE* cmock_call_instance, CBUF2* cbuf2, int content_type, int have_relay, unsigned long chunk_size, unsigned long num_chunks)
{
  cmock_call_instance->Expected_cbuf2 = cbuf2;
  cmock_call_instance->Expected_content_type = content_type;
  cmock_call_instance->Expected_have_relay = have_relay;
  cmock_call_instance->Expected_chunk_size = chunk_size;
  cmock_call_instance->Expected_num_chunks = num_chunks;
}

void cbuf2_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_init_CALL_INSTANCE));
  CMOCK_cbuf2_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_init_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_init_CallInstance, cmock_guts_index);
  Mock.cbuf2_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_init_IgnoreBool = (int)1;
}

void cbuf2_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, int content_type, int have_relay, unsigned long chunk_size, unsigned long num_chunks, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_init_CALL_INSTANCE));
  CMOCK_cbuf2_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_init_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_init_CallInstance, cmock_guts_index);
  Mock.cbuf2_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_init(cmock_call_instance, cbuf2, content_type, have_relay, chunk_size, num_chunks);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_init_StubWithCallback(CMOCK_cbuf2_init_CALLBACK Callback)
{
  Mock.cbuf2_init_CallbackFunctionPointer = Callback;
}

void cbuf2_destroy(CBUF2* buffer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_destroy_CallInstance);
  Mock.cbuf2_destroy_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_destroy_CallInstance);
  if (Mock.cbuf2_destroy_IgnoreBool)
  {
    return;
  }
  if (Mock.cbuf2_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.cbuf2_destroy_CallbackFunctionPointer(buffer, Mock.cbuf2_destroy_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_destroy' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_buffer), (void*)(buffer), sizeof(CBUF2), cmock_line, "Function 'cbuf2_destroy' called with unexpected value for argument 'buffer'.");
  }
}

void CMockExpectParameters_cbuf2_destroy(CMOCK_cbuf2_destroy_CALL_INSTANCE* cmock_call_instance, CBUF2* buffer)
{
  cmock_call_instance->Expected_buffer = buffer;
}

void cbuf2_destroy_CMockIgnore(void)
{
  Mock.cbuf2_destroy_IgnoreBool = (int)1;
}

void cbuf2_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, CBUF2* buffer)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_destroy_CALL_INSTANCE));
  CMOCK_cbuf2_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_destroy_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_destroy_CallInstance, cmock_guts_index);
  Mock.cbuf2_destroy_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_destroy(cmock_call_instance, buffer);
}

void cbuf2_destroy_StubWithCallback(CMOCK_cbuf2_destroy_CALLBACK Callback)
{
  Mock.cbuf2_destroy_CallbackFunctionPointer = Callback;
}

error_code cbuf2_extract(RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, char* data, u_long count, u_long* curr_song)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_extract_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_extract_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_extract_CallInstance);
  Mock.cbuf2_extract_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_extract_CallInstance);
  if (Mock.cbuf2_extract_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_extract_FinalReturn;
    memcpy(&Mock.cbuf2_extract_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_extract_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_extract_CallbackFunctionPointer(rmi, cbuf2, data, count, curr_song, Mock.cbuf2_extract_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_extract' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'cbuf2_extract' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_extract' called with unexpected value for argument 'cbuf2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_data, data, cmock_line, "Function 'cbuf2_extract' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_count), (void*)(&count), sizeof(u_long), cmock_line, "Function 'cbuf2_extract' called with unexpected value for argument 'count'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_curr_song), (void*)(curr_song), sizeof(u_long), cmock_line, "Function 'cbuf2_extract' called with unexpected value for argument 'curr_song'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_extract(CMOCK_cbuf2_extract_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, char* data, u_long count, u_long* curr_song)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_cbuf2 = cbuf2;
  cmock_call_instance->Expected_data = data;
  memcpy(&cmock_call_instance->Expected_count, &count, sizeof(u_long));
  cmock_call_instance->Expected_curr_song = curr_song;
}

void cbuf2_extract_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_extract_CALL_INSTANCE));
  CMOCK_cbuf2_extract_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_extract_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_extract_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_extract_CallInstance, cmock_guts_index);
  Mock.cbuf2_extract_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_extract_IgnoreBool = (int)1;
}

void cbuf2_extract_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, char* data, u_long count, u_long* curr_song, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_extract_CALL_INSTANCE));
  CMOCK_cbuf2_extract_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_extract_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_extract_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_extract_CallInstance, cmock_guts_index);
  Mock.cbuf2_extract_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_extract(cmock_call_instance, rmi, cbuf2, data, count, curr_song);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_extract_StubWithCallback(CMOCK_cbuf2_extract_CALLBACK Callback)
{
  Mock.cbuf2_extract_CallbackFunctionPointer = Callback;
}

error_code cbuf2_peek(CBUF2* buffer, char* items, u_long count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_peek_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_peek_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_peek_CallInstance);
  Mock.cbuf2_peek_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_peek_CallInstance);
  if (Mock.cbuf2_peek_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_peek_FinalReturn;
    memcpy(&Mock.cbuf2_peek_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_peek_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_peek_CallbackFunctionPointer(buffer, items, count, Mock.cbuf2_peek_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_peek' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_buffer), (void*)(buffer), sizeof(CBUF2), cmock_line, "Function 'cbuf2_peek' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_items, items, cmock_line, "Function 'cbuf2_peek' called with unexpected value for argument 'items'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_count), (void*)(&count), sizeof(u_long), cmock_line, "Function 'cbuf2_peek' called with unexpected value for argument 'count'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_peek(CMOCK_cbuf2_peek_CALL_INSTANCE* cmock_call_instance, CBUF2* buffer, char* items, u_long count)
{
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_items = items;
  memcpy(&cmock_call_instance->Expected_count, &count, sizeof(u_long));
}

void cbuf2_peek_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_peek_CALL_INSTANCE));
  CMOCK_cbuf2_peek_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_peek_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_peek_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_peek_CallInstance, cmock_guts_index);
  Mock.cbuf2_peek_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_peek_IgnoreBool = (int)1;
}

void cbuf2_peek_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* buffer, char* items, u_long count, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_peek_CALL_INSTANCE));
  CMOCK_cbuf2_peek_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_peek_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_peek_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_peek_CallInstance, cmock_guts_index);
  Mock.cbuf2_peek_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_peek(cmock_call_instance, buffer, items, count);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_peek_StubWithCallback(CMOCK_cbuf2_peek_CALLBACK Callback)
{
  Mock.cbuf2_peek_CallbackFunctionPointer = Callback;
}

error_code cbuf2_insert_chunk(RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, const char* data, u_long count, int content_type, TRACK_INFO* ti)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_insert_chunk_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_insert_chunk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_insert_chunk_CallInstance);
  Mock.cbuf2_insert_chunk_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_insert_chunk_CallInstance);
  if (Mock.cbuf2_insert_chunk_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_insert_chunk_FinalReturn;
    memcpy(&Mock.cbuf2_insert_chunk_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_insert_chunk_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_insert_chunk_CallbackFunctionPointer(rmi, cbuf2, data, count, content_type, ti, Mock.cbuf2_insert_chunk_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_insert_chunk' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'cbuf2_insert_chunk' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_insert_chunk' called with unexpected value for argument 'cbuf2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_data, data, cmock_line, "Function 'cbuf2_insert_chunk' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_count), (void*)(&count), sizeof(u_long), cmock_line, "Function 'cbuf2_insert_chunk' called with unexpected value for argument 'count'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_content_type, content_type, cmock_line, "Function 'cbuf2_insert_chunk' called with unexpected value for argument 'content_type'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ti), (void*)(ti), sizeof(TRACK_INFO), cmock_line, "Function 'cbuf2_insert_chunk' called with unexpected value for argument 'ti'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_insert_chunk(CMOCK_cbuf2_insert_chunk_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, const char* data, u_long count, int content_type, TRACK_INFO* ti)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_cbuf2 = cbuf2;
  cmock_call_instance->Expected_data = (char*)data;
  memcpy(&cmock_call_instance->Expected_count, &count, sizeof(u_long));
  cmock_call_instance->Expected_content_type = content_type;
  cmock_call_instance->Expected_ti = ti;
}

void cbuf2_insert_chunk_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_insert_chunk_CALL_INSTANCE));
  CMOCK_cbuf2_insert_chunk_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_insert_chunk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_insert_chunk_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_insert_chunk_CallInstance, cmock_guts_index);
  Mock.cbuf2_insert_chunk_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_insert_chunk_IgnoreBool = (int)1;
}

void cbuf2_insert_chunk_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, const char* data, u_long count, int content_type, TRACK_INFO* ti, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_insert_chunk_CALL_INSTANCE));
  CMOCK_cbuf2_insert_chunk_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_insert_chunk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_insert_chunk_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_insert_chunk_CallInstance, cmock_guts_index);
  Mock.cbuf2_insert_chunk_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_insert_chunk(cmock_call_instance, rmi, cbuf2, data, count, content_type, ti);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_insert_chunk_StubWithCallback(CMOCK_cbuf2_insert_chunk_CALLBACK Callback)
{
  Mock.cbuf2_insert_chunk_CallbackFunctionPointer = Callback;
}

error_code cbuf2_fastforward(CBUF2* buffer, u_long count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_fastforward_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_fastforward_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_fastforward_CallInstance);
  Mock.cbuf2_fastforward_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_fastforward_CallInstance);
  if (Mock.cbuf2_fastforward_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_fastforward_FinalReturn;
    memcpy(&Mock.cbuf2_fastforward_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_fastforward_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_fastforward_CallbackFunctionPointer(buffer, count, Mock.cbuf2_fastforward_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_fastforward' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_buffer), (void*)(buffer), sizeof(CBUF2), cmock_line, "Function 'cbuf2_fastforward' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_count), (void*)(&count), sizeof(u_long), cmock_line, "Function 'cbuf2_fastforward' called with unexpected value for argument 'count'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_fastforward(CMOCK_cbuf2_fastforward_CALL_INSTANCE* cmock_call_instance, CBUF2* buffer, u_long count)
{
  cmock_call_instance->Expected_buffer = buffer;
  memcpy(&cmock_call_instance->Expected_count, &count, sizeof(u_long));
}

void cbuf2_fastforward_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_fastforward_CALL_INSTANCE));
  CMOCK_cbuf2_fastforward_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_fastforward_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_fastforward_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_fastforward_CallInstance, cmock_guts_index);
  Mock.cbuf2_fastforward_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_fastforward_IgnoreBool = (int)1;
}

void cbuf2_fastforward_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* buffer, u_long count, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_fastforward_CALL_INSTANCE));
  CMOCK_cbuf2_fastforward_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_fastforward_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_fastforward_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_fastforward_CallInstance, cmock_guts_index);
  Mock.cbuf2_fastforward_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_fastforward(cmock_call_instance, buffer, count);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_fastforward_StubWithCallback(CMOCK_cbuf2_fastforward_CALLBACK Callback)
{
  Mock.cbuf2_fastforward_CallbackFunctionPointer = Callback;
}

error_code cbuf2_peek_rgn(CBUF2* buffer, char* out_buf, u_long start, u_long length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_peek_rgn_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_peek_rgn_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_peek_rgn_CallInstance);
  Mock.cbuf2_peek_rgn_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_peek_rgn_CallInstance);
  if (Mock.cbuf2_peek_rgn_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_peek_rgn_FinalReturn;
    memcpy(&Mock.cbuf2_peek_rgn_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_peek_rgn_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_peek_rgn_CallbackFunctionPointer(buffer, out_buf, start, length, Mock.cbuf2_peek_rgn_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_peek_rgn' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_buffer), (void*)(buffer), sizeof(CBUF2), cmock_line, "Function 'cbuf2_peek_rgn' called with unexpected value for argument 'buffer'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_out_buf, out_buf, cmock_line, "Function 'cbuf2_peek_rgn' called with unexpected value for argument 'out_buf'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_start), (void*)(&start), sizeof(u_long), cmock_line, "Function 'cbuf2_peek_rgn' called with unexpected value for argument 'start'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_length), (void*)(&length), sizeof(u_long), cmock_line, "Function 'cbuf2_peek_rgn' called with unexpected value for argument 'length'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_peek_rgn(CMOCK_cbuf2_peek_rgn_CALL_INSTANCE* cmock_call_instance, CBUF2* buffer, char* out_buf, u_long start, u_long length)
{
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_out_buf = out_buf;
  memcpy(&cmock_call_instance->Expected_start, &start, sizeof(u_long));
  memcpy(&cmock_call_instance->Expected_length, &length, sizeof(u_long));
}

void cbuf2_peek_rgn_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_peek_rgn_CALL_INSTANCE));
  CMOCK_cbuf2_peek_rgn_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_peek_rgn_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_peek_rgn_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_peek_rgn_CallInstance, cmock_guts_index);
  Mock.cbuf2_peek_rgn_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_peek_rgn_IgnoreBool = (int)1;
}

void cbuf2_peek_rgn_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* buffer, char* out_buf, u_long start, u_long length, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_peek_rgn_CALL_INSTANCE));
  CMOCK_cbuf2_peek_rgn_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_peek_rgn_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_peek_rgn_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_peek_rgn_CallInstance, cmock_guts_index);
  Mock.cbuf2_peek_rgn_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_peek_rgn(cmock_call_instance, buffer, out_buf, start, length);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_peek_rgn_StubWithCallback(CMOCK_cbuf2_peek_rgn_CALLBACK Callback)
{
  Mock.cbuf2_peek_rgn_CallbackFunctionPointer = Callback;
}

u_long cbuf2_get_free(CBUF2* buffer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_get_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_get_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_get_free_CallInstance);
  Mock.cbuf2_get_free_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_get_free_CallInstance);
  if (Mock.cbuf2_get_free_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_get_free_FinalReturn;
    memcpy(&Mock.cbuf2_get_free_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(u_long));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_get_free_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_get_free_CallbackFunctionPointer(buffer, Mock.cbuf2_get_free_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_get_free' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_buffer), (void*)(buffer), sizeof(CBUF2), cmock_line, "Function 'cbuf2_get_free' called with unexpected value for argument 'buffer'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_get_free(CMOCK_cbuf2_get_free_CALL_INSTANCE* cmock_call_instance, CBUF2* buffer)
{
  cmock_call_instance->Expected_buffer = buffer;
}

void cbuf2_get_free_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, u_long cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_get_free_CALL_INSTANCE));
  CMOCK_cbuf2_get_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_get_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_get_free_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_get_free_CallInstance, cmock_guts_index);
  Mock.cbuf2_get_free_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_get_free_IgnoreBool = (int)1;
}

void cbuf2_get_free_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* buffer, u_long cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_get_free_CALL_INSTANCE));
  CMOCK_cbuf2_get_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_get_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_get_free_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_get_free_CallInstance, cmock_guts_index);
  Mock.cbuf2_get_free_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_get_free(cmock_call_instance, buffer);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(u_long));
}

void cbuf2_get_free_StubWithCallback(CMOCK_cbuf2_get_free_CALLBACK Callback)
{
  Mock.cbuf2_get_free_CallbackFunctionPointer = Callback;
}

u_long cbuf2_get_free_tail(CBUF2* cbuf2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_get_free_tail_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_get_free_tail_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_get_free_tail_CallInstance);
  Mock.cbuf2_get_free_tail_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_get_free_tail_CallInstance);
  if (Mock.cbuf2_get_free_tail_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_get_free_tail_FinalReturn;
    memcpy(&Mock.cbuf2_get_free_tail_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(u_long));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_get_free_tail_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_get_free_tail_CallbackFunctionPointer(cbuf2, Mock.cbuf2_get_free_tail_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_get_free_tail' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_get_free_tail' called with unexpected value for argument 'cbuf2'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_get_free_tail(CMOCK_cbuf2_get_free_tail_CALL_INSTANCE* cmock_call_instance, CBUF2* cbuf2)
{
  cmock_call_instance->Expected_cbuf2 = cbuf2;
}

void cbuf2_get_free_tail_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, u_long cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_get_free_tail_CALL_INSTANCE));
  CMOCK_cbuf2_get_free_tail_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_get_free_tail_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_get_free_tail_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_get_free_tail_CallInstance, cmock_guts_index);
  Mock.cbuf2_get_free_tail_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_get_free_tail_IgnoreBool = (int)1;
}

void cbuf2_get_free_tail_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, u_long cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_get_free_tail_CALL_INSTANCE));
  CMOCK_cbuf2_get_free_tail_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_get_free_tail_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_get_free_tail_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_get_free_tail_CallInstance, cmock_guts_index);
  Mock.cbuf2_get_free_tail_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_get_free_tail(cmock_call_instance, cbuf2);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(u_long));
}

void cbuf2_get_free_tail_StubWithCallback(CMOCK_cbuf2_get_free_tail_CALLBACK Callback)
{
  Mock.cbuf2_get_free_tail_CallbackFunctionPointer = Callback;
}

u_long cbuf2_write_index(CBUF2* cbuf2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_write_index_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_write_index_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_write_index_CallInstance);
  Mock.cbuf2_write_index_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_write_index_CallInstance);
  if (Mock.cbuf2_write_index_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_write_index_FinalReturn;
    memcpy(&Mock.cbuf2_write_index_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(u_long));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_write_index_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_write_index_CallbackFunctionPointer(cbuf2, Mock.cbuf2_write_index_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_write_index' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_write_index' called with unexpected value for argument 'cbuf2'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_write_index(CMOCK_cbuf2_write_index_CALL_INSTANCE* cmock_call_instance, CBUF2* cbuf2)
{
  cmock_call_instance->Expected_cbuf2 = cbuf2;
}

void cbuf2_write_index_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, u_long cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_write_index_CALL_INSTANCE));
  CMOCK_cbuf2_write_index_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_write_index_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_write_index_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_write_index_CallInstance, cmock_guts_index);
  Mock.cbuf2_write_index_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_write_index_IgnoreBool = (int)1;
}

void cbuf2_write_index_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, u_long cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_write_index_CALL_INSTANCE));
  CMOCK_cbuf2_write_index_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_write_index_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_write_index_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_write_index_CallInstance, cmock_guts_index);
  Mock.cbuf2_write_index_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_write_index(cmock_call_instance, cbuf2);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(u_long));
}

void cbuf2_write_index_StubWithCallback(CMOCK_cbuf2_write_index_CALLBACK Callback)
{
  Mock.cbuf2_write_index_CallbackFunctionPointer = Callback;
}

void cbuf2_set_next_song(CBUF2* cbuf2, u_long pos)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_set_next_song_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_set_next_song_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_set_next_song_CallInstance);
  Mock.cbuf2_set_next_song_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_set_next_song_CallInstance);
  if (Mock.cbuf2_set_next_song_IgnoreBool)
  {
    return;
  }
  if (Mock.cbuf2_set_next_song_CallbackFunctionPointer != NULL)
  {
    Mock.cbuf2_set_next_song_CallbackFunctionPointer(cbuf2, pos, Mock.cbuf2_set_next_song_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_set_next_song' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_set_next_song' called with unexpected value for argument 'cbuf2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pos), (void*)(&pos), sizeof(u_long), cmock_line, "Function 'cbuf2_set_next_song' called with unexpected value for argument 'pos'.");
  }
}

void CMockExpectParameters_cbuf2_set_next_song(CMOCK_cbuf2_set_next_song_CALL_INSTANCE* cmock_call_instance, CBUF2* cbuf2, u_long pos)
{
  cmock_call_instance->Expected_cbuf2 = cbuf2;
  memcpy(&cmock_call_instance->Expected_pos, &pos, sizeof(u_long));
}

void cbuf2_set_next_song_CMockIgnore(void)
{
  Mock.cbuf2_set_next_song_IgnoreBool = (int)1;
}

void cbuf2_set_next_song_CMockExpect(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, u_long pos)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_set_next_song_CALL_INSTANCE));
  CMOCK_cbuf2_set_next_song_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_set_next_song_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_set_next_song_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_set_next_song_CallInstance, cmock_guts_index);
  Mock.cbuf2_set_next_song_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_set_next_song(cmock_call_instance, cbuf2, pos);
}

void cbuf2_set_next_song_StubWithCallback(CMOCK_cbuf2_set_next_song_CALLBACK Callback)
{
  Mock.cbuf2_set_next_song_CallbackFunctionPointer = Callback;
}

error_code cbuf2_init_relay_entry(CBUF2* cbuf2, RELAY_LIST* ptr, u_long burst_request)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_init_relay_entry_CallInstance);
  Mock.cbuf2_init_relay_entry_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_init_relay_entry_CallInstance);
  if (Mock.cbuf2_init_relay_entry_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_init_relay_entry_FinalReturn;
    memcpy(&Mock.cbuf2_init_relay_entry_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_init_relay_entry_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_init_relay_entry_CallbackFunctionPointer(cbuf2, ptr, burst_request, Mock.cbuf2_init_relay_entry_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_init_relay_entry' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_init_relay_entry' called with unexpected value for argument 'cbuf2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_ptr), (void*)(ptr), sizeof(RELAY_LIST), cmock_line, "Function 'cbuf2_init_relay_entry' called with unexpected value for argument 'ptr'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_burst_request), (void*)(&burst_request), sizeof(u_long), cmock_line, "Function 'cbuf2_init_relay_entry' called with unexpected value for argument 'burst_request'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_init_relay_entry(CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE* cmock_call_instance, CBUF2* cbuf2, RELAY_LIST* ptr, u_long burst_request)
{
  cmock_call_instance->Expected_cbuf2 = cbuf2;
  cmock_call_instance->Expected_ptr = ptr;
  memcpy(&cmock_call_instance->Expected_burst_request, &burst_request, sizeof(u_long));
}

void cbuf2_init_relay_entry_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE));
  CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_init_relay_entry_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_init_relay_entry_CallInstance, cmock_guts_index);
  Mock.cbuf2_init_relay_entry_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_init_relay_entry_IgnoreBool = (int)1;
}

void cbuf2_init_relay_entry_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, RELAY_LIST* ptr, u_long burst_request, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE));
  CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_init_relay_entry_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_init_relay_entry_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_init_relay_entry_CallInstance, cmock_guts_index);
  Mock.cbuf2_init_relay_entry_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_init_relay_entry(cmock_call_instance, cbuf2, ptr, burst_request);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_init_relay_entry_StubWithCallback(CMOCK_cbuf2_init_relay_entry_CALLBACK Callback)
{
  Mock.cbuf2_init_relay_entry_CallbackFunctionPointer = Callback;
}

error_code cbuf2_ogg_peek_song(CBUF2* cbuf2, char* out_buf, unsigned long buf_size, unsigned long* amt_filled, int* eos)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_ogg_peek_song_CallInstance);
  Mock.cbuf2_ogg_peek_song_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_ogg_peek_song_CallInstance);
  if (Mock.cbuf2_ogg_peek_song_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_ogg_peek_song_FinalReturn;
    memcpy(&Mock.cbuf2_ogg_peek_song_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_ogg_peek_song_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_ogg_peek_song_CallbackFunctionPointer(cbuf2, out_buf, buf_size, amt_filled, eos, Mock.cbuf2_ogg_peek_song_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_ogg_peek_song' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_ogg_peek_song' called with unexpected value for argument 'cbuf2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_out_buf, out_buf, cmock_line, "Function 'cbuf2_ogg_peek_song' called with unexpected value for argument 'out_buf'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_buf_size, buf_size, cmock_line, "Function 'cbuf2_ogg_peek_song' called with unexpected value for argument 'buf_size'.");
  }
  {
    if (cmock_call_instance->Expected_amt_filled == NULL)
      { UNITY_TEST_ASSERT_NULL(amt_filled, cmock_line, "Expected NULL. Function 'cbuf2_ogg_peek_song' called with unexpected value for argument 'amt_filled'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_amt_filled, amt_filled, 1, cmock_line, "Function 'cbuf2_ogg_peek_song' called with unexpected value for argument 'amt_filled'."); }
  }
  {
    if (cmock_call_instance->Expected_eos == NULL)
      { UNITY_TEST_ASSERT_NULL(eos, cmock_line, "Expected NULL. Function 'cbuf2_ogg_peek_song' called with unexpected value for argument 'eos'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_eos, eos, 1, cmock_line, "Function 'cbuf2_ogg_peek_song' called with unexpected value for argument 'eos'."); }
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_ogg_peek_song(CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE* cmock_call_instance, CBUF2* cbuf2, char* out_buf, unsigned long buf_size, unsigned long* amt_filled, int* eos)
{
  cmock_call_instance->Expected_cbuf2 = cbuf2;
  cmock_call_instance->Expected_out_buf = out_buf;
  cmock_call_instance->Expected_buf_size = buf_size;
  cmock_call_instance->Expected_amt_filled = amt_filled;
  cmock_call_instance->Expected_eos = eos;
}

void cbuf2_ogg_peek_song_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE));
  CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_ogg_peek_song_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_ogg_peek_song_CallInstance, cmock_guts_index);
  Mock.cbuf2_ogg_peek_song_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_ogg_peek_song_IgnoreBool = (int)1;
}

void cbuf2_ogg_peek_song_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, char* out_buf, unsigned long buf_size, unsigned long* amt_filled, int* eos, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE));
  CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_ogg_peek_song_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_ogg_peek_song_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_ogg_peek_song_CallInstance, cmock_guts_index);
  Mock.cbuf2_ogg_peek_song_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_ogg_peek_song(cmock_call_instance, cbuf2, out_buf, buf_size, amt_filled, eos);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_ogg_peek_song_StubWithCallback(CMOCK_cbuf2_ogg_peek_song_CALLBACK Callback)
{
  Mock.cbuf2_ogg_peek_song_CallbackFunctionPointer = Callback;
}

error_code cbuf2_extract_relay(CBUF2* cbuf2, char* data, u_long* pos, u_long* len, int icy_metadata)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_extract_relay_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_extract_relay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_extract_relay_CallInstance);
  Mock.cbuf2_extract_relay_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_extract_relay_CallInstance);
  if (Mock.cbuf2_extract_relay_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_extract_relay_FinalReturn;
    memcpy(&Mock.cbuf2_extract_relay_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_extract_relay_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_extract_relay_CallbackFunctionPointer(cbuf2, data, pos, len, icy_metadata, Mock.cbuf2_extract_relay_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_extract_relay' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_extract_relay' called with unexpected value for argument 'cbuf2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_data, data, cmock_line, "Function 'cbuf2_extract_relay' called with unexpected value for argument 'data'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pos), (void*)(pos), sizeof(u_long), cmock_line, "Function 'cbuf2_extract_relay' called with unexpected value for argument 'pos'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_len), (void*)(len), sizeof(u_long), cmock_line, "Function 'cbuf2_extract_relay' called with unexpected value for argument 'len'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_icy_metadata, icy_metadata, cmock_line, "Function 'cbuf2_extract_relay' called with unexpected value for argument 'icy_metadata'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_extract_relay(CMOCK_cbuf2_extract_relay_CALL_INSTANCE* cmock_call_instance, CBUF2* cbuf2, char* data, u_long* pos, u_long* len, int icy_metadata)
{
  cmock_call_instance->Expected_cbuf2 = cbuf2;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_pos = pos;
  cmock_call_instance->Expected_len = len;
  cmock_call_instance->Expected_icy_metadata = icy_metadata;
}

void cbuf2_extract_relay_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_extract_relay_CALL_INSTANCE));
  CMOCK_cbuf2_extract_relay_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_extract_relay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_extract_relay_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_extract_relay_CallInstance, cmock_guts_index);
  Mock.cbuf2_extract_relay_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_extract_relay_IgnoreBool = (int)1;
}

void cbuf2_extract_relay_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, char* data, u_long* pos, u_long* len, int icy_metadata, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_extract_relay_CALL_INSTANCE));
  CMOCK_cbuf2_extract_relay_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_extract_relay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_extract_relay_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_extract_relay_CallInstance, cmock_guts_index);
  Mock.cbuf2_extract_relay_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_extract_relay(cmock_call_instance, cbuf2, data, pos, len, icy_metadata);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_extract_relay_StubWithCallback(CMOCK_cbuf2_extract_relay_CALLBACK Callback)
{
  Mock.cbuf2_extract_relay_CallbackFunctionPointer = Callback;
}

error_code cbuf2_advance_ogg(RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, int requested_free_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cbuf2_advance_ogg_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_advance_ogg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cbuf2_advance_ogg_CallInstance);
  Mock.cbuf2_advance_ogg_CallInstance = CMock_Guts_MemNext(Mock.cbuf2_advance_ogg_CallInstance);
  if (Mock.cbuf2_advance_ogg_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.cbuf2_advance_ogg_FinalReturn;
    memcpy(&Mock.cbuf2_advance_ogg_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.cbuf2_advance_ogg_CallbackFunctionPointer != NULL)
  {
    return Mock.cbuf2_advance_ogg_CallbackFunctionPointer(rmi, cbuf2, requested_free_size, Mock.cbuf2_advance_ogg_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'cbuf2_advance_ogg' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_rmi), (void*)(rmi), sizeof(RIP_MANAGER_INFO), cmock_line, "Function 'cbuf2_advance_ogg' called with unexpected value for argument 'rmi'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cbuf2), (void*)(cbuf2), sizeof(CBUF2), cmock_line, "Function 'cbuf2_advance_ogg' called with unexpected value for argument 'cbuf2'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_requested_free_size, requested_free_size, cmock_line, "Function 'cbuf2_advance_ogg' called with unexpected value for argument 'requested_free_size'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cbuf2_advance_ogg(CMOCK_cbuf2_advance_ogg_CALL_INSTANCE* cmock_call_instance, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, int requested_free_size)
{
  cmock_call_instance->Expected_rmi = rmi;
  cmock_call_instance->Expected_cbuf2 = cbuf2;
  cmock_call_instance->Expected_requested_free_size = requested_free_size;
}

void cbuf2_advance_ogg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_advance_ogg_CALL_INSTANCE));
  CMOCK_cbuf2_advance_ogg_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_advance_ogg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_advance_ogg_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_advance_ogg_CallInstance, cmock_guts_index);
  Mock.cbuf2_advance_ogg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cbuf2_advance_ogg_IgnoreBool = (int)1;
}

void cbuf2_advance_ogg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, int requested_free_size, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cbuf2_advance_ogg_CALL_INSTANCE));
  CMOCK_cbuf2_advance_ogg_CALL_INSTANCE* cmock_call_instance = (CMOCK_cbuf2_advance_ogg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cbuf2_advance_ogg_CallInstance = CMock_Guts_MemChain(Mock.cbuf2_advance_ogg_CallInstance, cmock_guts_index);
  Mock.cbuf2_advance_ogg_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_cbuf2_advance_ogg(cmock_call_instance, rmi, cbuf2, requested_free_size);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void cbuf2_advance_ogg_StubWithCallback(CMOCK_cbuf2_advance_ogg_CALLBACK Callback)
{
  Mock.cbuf2_advance_ogg_CallbackFunctionPointer = Callback;
}

