/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockcharset.h"

typedef struct _CMOCK_utf8_mbtowc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int* Expected_pwc;
  char* Expected_s;
  size_t Expected_n;

} CMOCK_utf8_mbtowc_CALL_INSTANCE;

typedef struct _CMOCK_utf8_wctomb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  char* Expected_s;
  int Expected_wc;

} CMOCK_utf8_wctomb_CALL_INSTANCE;

typedef struct _CMOCK_charset_find_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  struct charset* ReturnVal;
  char* Expected_code;

} CMOCK_charset_find_CALL_INSTANCE;

typedef struct _CMOCK_charset_mbtowc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  struct charset* Expected_charset;
  int* Expected_pwc;
  char* Expected_s;
  size_t Expected_n;

} CMOCK_charset_mbtowc_CALL_INSTANCE;

typedef struct _CMOCK_charset_wctomb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  struct charset* Expected_charset;
  char* Expected_s;
  int Expected_wc;

} CMOCK_charset_wctomb_CALL_INSTANCE;

typedef struct _CMOCK_charset_max_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  struct charset* Expected_charset;

} CMOCK_charset_max_CALL_INSTANCE;

typedef struct _CMOCK_charset_convert_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  char* Expected_fromcode;
  char* Expected_tocode;
  char* Expected_from;
  size_t Expected_fromlen;
  char** Expected_to;
  size_t* Expected_tolen;

} CMOCK_charset_convert_CALL_INSTANCE;

static struct MockcharsetInstance
{
  int utf8_mbtowc_IgnoreBool;
  int utf8_mbtowc_FinalReturn;
  CMOCK_utf8_mbtowc_CALLBACK utf8_mbtowc_CallbackFunctionPointer;
  int utf8_mbtowc_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE utf8_mbtowc_CallInstance;
  int utf8_wctomb_IgnoreBool;
  int utf8_wctomb_FinalReturn;
  CMOCK_utf8_wctomb_CALLBACK utf8_wctomb_CallbackFunctionPointer;
  int utf8_wctomb_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE utf8_wctomb_CallInstance;
  int charset_find_IgnoreBool;
  struct charset* charset_find_FinalReturn;
  CMOCK_charset_find_CALLBACK charset_find_CallbackFunctionPointer;
  int charset_find_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE charset_find_CallInstance;
  int charset_mbtowc_IgnoreBool;
  int charset_mbtowc_FinalReturn;
  CMOCK_charset_mbtowc_CALLBACK charset_mbtowc_CallbackFunctionPointer;
  int charset_mbtowc_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE charset_mbtowc_CallInstance;
  int charset_wctomb_IgnoreBool;
  int charset_wctomb_FinalReturn;
  CMOCK_charset_wctomb_CALLBACK charset_wctomb_CallbackFunctionPointer;
  int charset_wctomb_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE charset_wctomb_CallInstance;
  int charset_max_IgnoreBool;
  int charset_max_FinalReturn;
  CMOCK_charset_max_CALLBACK charset_max_CallbackFunctionPointer;
  int charset_max_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE charset_max_CallInstance;
  int charset_convert_IgnoreBool;
  int charset_convert_FinalReturn;
  CMOCK_charset_convert_CALLBACK charset_convert_CallbackFunctionPointer;
  int charset_convert_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE charset_convert_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcharset_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.utf8_mbtowc_IgnoreBool)
    Mock.utf8_mbtowc_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.utf8_mbtowc_CallInstance, cmock_line, "Function 'utf8_mbtowc' called less times than expected.");
  if (Mock.utf8_mbtowc_CallbackFunctionPointer != NULL)
    Mock.utf8_mbtowc_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.utf8_wctomb_IgnoreBool)
    Mock.utf8_wctomb_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.utf8_wctomb_CallInstance, cmock_line, "Function 'utf8_wctomb' called less times than expected.");
  if (Mock.utf8_wctomb_CallbackFunctionPointer != NULL)
    Mock.utf8_wctomb_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.charset_find_IgnoreBool)
    Mock.charset_find_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.charset_find_CallInstance, cmock_line, "Function 'charset_find' called less times than expected.");
  if (Mock.charset_find_CallbackFunctionPointer != NULL)
    Mock.charset_find_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.charset_mbtowc_IgnoreBool)
    Mock.charset_mbtowc_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.charset_mbtowc_CallInstance, cmock_line, "Function 'charset_mbtowc' called less times than expected.");
  if (Mock.charset_mbtowc_CallbackFunctionPointer != NULL)
    Mock.charset_mbtowc_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.charset_wctomb_IgnoreBool)
    Mock.charset_wctomb_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.charset_wctomb_CallInstance, cmock_line, "Function 'charset_wctomb' called less times than expected.");
  if (Mock.charset_wctomb_CallbackFunctionPointer != NULL)
    Mock.charset_wctomb_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.charset_max_IgnoreBool)
    Mock.charset_max_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.charset_max_CallInstance, cmock_line, "Function 'charset_max' called less times than expected.");
  if (Mock.charset_max_CallbackFunctionPointer != NULL)
    Mock.charset_max_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.charset_convert_IgnoreBool)
    Mock.charset_convert_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.charset_convert_CallInstance, cmock_line, "Function 'charset_convert' called less times than expected.");
  if (Mock.charset_convert_CallbackFunctionPointer != NULL)
    Mock.charset_convert_CallInstance = CMOCK_GUTS_NONE;
}

void Mockcharset_Init(void)
{
  Mockcharset_Destroy();
}

void Mockcharset_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.utf8_mbtowc_CallbackFunctionPointer = NULL;
  Mock.utf8_mbtowc_CallbackCalls = 0;
  Mock.utf8_wctomb_CallbackFunctionPointer = NULL;
  Mock.utf8_wctomb_CallbackCalls = 0;
  Mock.charset_find_CallbackFunctionPointer = NULL;
  Mock.charset_find_CallbackCalls = 0;
  Mock.charset_mbtowc_CallbackFunctionPointer = NULL;
  Mock.charset_mbtowc_CallbackCalls = 0;
  Mock.charset_wctomb_CallbackFunctionPointer = NULL;
  Mock.charset_wctomb_CallbackCalls = 0;
  Mock.charset_max_CallbackFunctionPointer = NULL;
  Mock.charset_max_CallbackCalls = 0;
  Mock.charset_convert_CallbackFunctionPointer = NULL;
  Mock.charset_convert_CallbackCalls = 0;
}

int utf8_mbtowc(int* pwc, const char* s, size_t n)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_utf8_mbtowc_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_mbtowc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.utf8_mbtowc_CallInstance);
  Mock.utf8_mbtowc_CallInstance = CMock_Guts_MemNext(Mock.utf8_mbtowc_CallInstance);
  if (Mock.utf8_mbtowc_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.utf8_mbtowc_FinalReturn;
    Mock.utf8_mbtowc_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.utf8_mbtowc_CallbackFunctionPointer != NULL)
  {
    return Mock.utf8_mbtowc_CallbackFunctionPointer(pwc, s, n, Mock.utf8_mbtowc_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'utf8_mbtowc' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    if (cmock_call_instance->Expected_pwc == NULL)
      { UNITY_TEST_ASSERT_NULL(pwc, cmock_line, "Expected NULL. Function 'utf8_mbtowc' called with unexpected value for argument 'pwc'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_pwc, pwc, 1, cmock_line, "Function 'utf8_mbtowc' called with unexpected value for argument 'pwc'."); }
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, "Function 'utf8_mbtowc' called with unexpected value for argument 's'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_n), (void*)(&n), sizeof(size_t), cmock_line, "Function 'utf8_mbtowc' called with unexpected value for argument 'n'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_utf8_mbtowc(CMOCK_utf8_mbtowc_CALL_INSTANCE* cmock_call_instance, int* pwc, const char* s, size_t n)
{
  cmock_call_instance->Expected_pwc = pwc;
  cmock_call_instance->Expected_s = (char*)s;
  memcpy(&cmock_call_instance->Expected_n, &n, sizeof(size_t));
}

void utf8_mbtowc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_utf8_mbtowc_CALL_INSTANCE));
  CMOCK_utf8_mbtowc_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_mbtowc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.utf8_mbtowc_CallInstance = CMock_Guts_MemChain(Mock.utf8_mbtowc_CallInstance, cmock_guts_index);
  Mock.utf8_mbtowc_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.utf8_mbtowc_IgnoreBool = (int)1;
}

void utf8_mbtowc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int* pwc, const char* s, size_t n, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_utf8_mbtowc_CALL_INSTANCE));
  CMOCK_utf8_mbtowc_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_mbtowc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.utf8_mbtowc_CallInstance = CMock_Guts_MemChain(Mock.utf8_mbtowc_CallInstance, cmock_guts_index);
  Mock.utf8_mbtowc_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_utf8_mbtowc(cmock_call_instance, pwc, s, n);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void utf8_mbtowc_StubWithCallback(CMOCK_utf8_mbtowc_CALLBACK Callback)
{
  Mock.utf8_mbtowc_CallbackFunctionPointer = Callback;
}

int utf8_wctomb(char* s, int wc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_utf8_wctomb_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_wctomb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.utf8_wctomb_CallInstance);
  Mock.utf8_wctomb_CallInstance = CMock_Guts_MemNext(Mock.utf8_wctomb_CallInstance);
  if (Mock.utf8_wctomb_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.utf8_wctomb_FinalReturn;
    Mock.utf8_wctomb_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.utf8_wctomb_CallbackFunctionPointer != NULL)
  {
    return Mock.utf8_wctomb_CallbackFunctionPointer(s, wc, Mock.utf8_wctomb_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'utf8_wctomb' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, "Function 'utf8_wctomb' called with unexpected value for argument 's'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_wc, wc, cmock_line, "Function 'utf8_wctomb' called with unexpected value for argument 'wc'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_utf8_wctomb(CMOCK_utf8_wctomb_CALL_INSTANCE* cmock_call_instance, char* s, int wc)
{
  cmock_call_instance->Expected_s = s;
  cmock_call_instance->Expected_wc = wc;
}

void utf8_wctomb_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_utf8_wctomb_CALL_INSTANCE));
  CMOCK_utf8_wctomb_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_wctomb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.utf8_wctomb_CallInstance = CMock_Guts_MemChain(Mock.utf8_wctomb_CallInstance, cmock_guts_index);
  Mock.utf8_wctomb_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.utf8_wctomb_IgnoreBool = (int)1;
}

void utf8_wctomb_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* s, int wc, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_utf8_wctomb_CALL_INSTANCE));
  CMOCK_utf8_wctomb_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_wctomb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.utf8_wctomb_CallInstance = CMock_Guts_MemChain(Mock.utf8_wctomb_CallInstance, cmock_guts_index);
  Mock.utf8_wctomb_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_utf8_wctomb(cmock_call_instance, s, wc);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void utf8_wctomb_StubWithCallback(CMOCK_utf8_wctomb_CALLBACK Callback)
{
  Mock.utf8_wctomb_CallbackFunctionPointer = Callback;
}

struct charset* charset_find(const char* code)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_charset_find_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_find_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.charset_find_CallInstance);
  Mock.charset_find_CallInstance = CMock_Guts_MemNext(Mock.charset_find_CallInstance);
  if (Mock.charset_find_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.charset_find_FinalReturn;
    Mock.charset_find_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.charset_find_CallbackFunctionPointer != NULL)
  {
    return Mock.charset_find_CallbackFunctionPointer(code, Mock.charset_find_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'charset_find' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_code, code, cmock_line, "Function 'charset_find' called with unexpected value for argument 'code'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_charset_find(CMOCK_charset_find_CALL_INSTANCE* cmock_call_instance, const char* code)
{
  cmock_call_instance->Expected_code = (char*)code;
}

void charset_find_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, struct charset* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_find_CALL_INSTANCE));
  CMOCK_charset_find_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_find_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_find_CallInstance = CMock_Guts_MemChain(Mock.charset_find_CallInstance, cmock_guts_index);
  Mock.charset_find_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.charset_find_IgnoreBool = (int)1;
}

void charset_find_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* code, struct charset* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_find_CALL_INSTANCE));
  CMOCK_charset_find_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_find_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_find_CallInstance = CMock_Guts_MemChain(Mock.charset_find_CallInstance, cmock_guts_index);
  Mock.charset_find_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_charset_find(cmock_call_instance, code);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void charset_find_StubWithCallback(CMOCK_charset_find_CALLBACK Callback)
{
  Mock.charset_find_CallbackFunctionPointer = Callback;
}

int charset_mbtowc(struct charset* charset, int* pwc, const char* s, size_t n)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_charset_mbtowc_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_mbtowc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.charset_mbtowc_CallInstance);
  Mock.charset_mbtowc_CallInstance = CMock_Guts_MemNext(Mock.charset_mbtowc_CallInstance);
  if (Mock.charset_mbtowc_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.charset_mbtowc_FinalReturn;
    Mock.charset_mbtowc_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.charset_mbtowc_CallbackFunctionPointer != NULL)
  {
    return Mock.charset_mbtowc_CallbackFunctionPointer(charset, pwc, s, n, Mock.charset_mbtowc_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'charset_mbtowc' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_charset), (void*)(charset), sizeof(struct charset), cmock_line, "Function 'charset_mbtowc' called with unexpected value for argument 'charset'.");
  }
  {
    if (cmock_call_instance->Expected_pwc == NULL)
      { UNITY_TEST_ASSERT_NULL(pwc, cmock_line, "Expected NULL. Function 'charset_mbtowc' called with unexpected value for argument 'pwc'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_pwc, pwc, 1, cmock_line, "Function 'charset_mbtowc' called with unexpected value for argument 'pwc'."); }
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, "Function 'charset_mbtowc' called with unexpected value for argument 's'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_n), (void*)(&n), sizeof(size_t), cmock_line, "Function 'charset_mbtowc' called with unexpected value for argument 'n'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_charset_mbtowc(CMOCK_charset_mbtowc_CALL_INSTANCE* cmock_call_instance, struct charset* charset, int* pwc, const char* s, size_t n)
{
  cmock_call_instance->Expected_charset = charset;
  cmock_call_instance->Expected_pwc = pwc;
  cmock_call_instance->Expected_s = (char*)s;
  memcpy(&cmock_call_instance->Expected_n, &n, sizeof(size_t));
}

void charset_mbtowc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_mbtowc_CALL_INSTANCE));
  CMOCK_charset_mbtowc_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_mbtowc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_mbtowc_CallInstance = CMock_Guts_MemChain(Mock.charset_mbtowc_CallInstance, cmock_guts_index);
  Mock.charset_mbtowc_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.charset_mbtowc_IgnoreBool = (int)1;
}

void charset_mbtowc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct charset* charset, int* pwc, const char* s, size_t n, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_mbtowc_CALL_INSTANCE));
  CMOCK_charset_mbtowc_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_mbtowc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_mbtowc_CallInstance = CMock_Guts_MemChain(Mock.charset_mbtowc_CallInstance, cmock_guts_index);
  Mock.charset_mbtowc_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_charset_mbtowc(cmock_call_instance, charset, pwc, s, n);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void charset_mbtowc_StubWithCallback(CMOCK_charset_mbtowc_CALLBACK Callback)
{
  Mock.charset_mbtowc_CallbackFunctionPointer = Callback;
}

int charset_wctomb(struct charset* charset, char* s, int wc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_charset_wctomb_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_wctomb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.charset_wctomb_CallInstance);
  Mock.charset_wctomb_CallInstance = CMock_Guts_MemNext(Mock.charset_wctomb_CallInstance);
  if (Mock.charset_wctomb_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.charset_wctomb_FinalReturn;
    Mock.charset_wctomb_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.charset_wctomb_CallbackFunctionPointer != NULL)
  {
    return Mock.charset_wctomb_CallbackFunctionPointer(charset, s, wc, Mock.charset_wctomb_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'charset_wctomb' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_charset), (void*)(charset), sizeof(struct charset), cmock_line, "Function 'charset_wctomb' called with unexpected value for argument 'charset'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, "Function 'charset_wctomb' called with unexpected value for argument 's'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_wc, wc, cmock_line, "Function 'charset_wctomb' called with unexpected value for argument 'wc'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_charset_wctomb(CMOCK_charset_wctomb_CALL_INSTANCE* cmock_call_instance, struct charset* charset, char* s, int wc)
{
  cmock_call_instance->Expected_charset = charset;
  cmock_call_instance->Expected_s = s;
  cmock_call_instance->Expected_wc = wc;
}

void charset_wctomb_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_wctomb_CALL_INSTANCE));
  CMOCK_charset_wctomb_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_wctomb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_wctomb_CallInstance = CMock_Guts_MemChain(Mock.charset_wctomb_CallInstance, cmock_guts_index);
  Mock.charset_wctomb_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.charset_wctomb_IgnoreBool = (int)1;
}

void charset_wctomb_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct charset* charset, char* s, int wc, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_wctomb_CALL_INSTANCE));
  CMOCK_charset_wctomb_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_wctomb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_wctomb_CallInstance = CMock_Guts_MemChain(Mock.charset_wctomb_CallInstance, cmock_guts_index);
  Mock.charset_wctomb_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_charset_wctomb(cmock_call_instance, charset, s, wc);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void charset_wctomb_StubWithCallback(CMOCK_charset_wctomb_CALLBACK Callback)
{
  Mock.charset_wctomb_CallbackFunctionPointer = Callback;
}

int charset_max(struct charset* charset)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_charset_max_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_max_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.charset_max_CallInstance);
  Mock.charset_max_CallInstance = CMock_Guts_MemNext(Mock.charset_max_CallInstance);
  if (Mock.charset_max_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.charset_max_FinalReturn;
    Mock.charset_max_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.charset_max_CallbackFunctionPointer != NULL)
  {
    return Mock.charset_max_CallbackFunctionPointer(charset, Mock.charset_max_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'charset_max' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_charset), (void*)(charset), sizeof(struct charset), cmock_line, "Function 'charset_max' called with unexpected value for argument 'charset'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_charset_max(CMOCK_charset_max_CALL_INSTANCE* cmock_call_instance, struct charset* charset)
{
  cmock_call_instance->Expected_charset = charset;
}

void charset_max_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_max_CALL_INSTANCE));
  CMOCK_charset_max_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_max_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_max_CallInstance = CMock_Guts_MemChain(Mock.charset_max_CallInstance, cmock_guts_index);
  Mock.charset_max_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.charset_max_IgnoreBool = (int)1;
}

void charset_max_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct charset* charset, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_max_CALL_INSTANCE));
  CMOCK_charset_max_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_max_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_max_CallInstance = CMock_Guts_MemChain(Mock.charset_max_CallInstance, cmock_guts_index);
  Mock.charset_max_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_charset_max(cmock_call_instance, charset);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void charset_max_StubWithCallback(CMOCK_charset_max_CALLBACK Callback)
{
  Mock.charset_max_CallbackFunctionPointer = Callback;
}

int charset_convert(const char* fromcode, const char* tocode, const char* from, size_t fromlen, char** to, size_t* tolen)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_charset_convert_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_convert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.charset_convert_CallInstance);
  Mock.charset_convert_CallInstance = CMock_Guts_MemNext(Mock.charset_convert_CallInstance);
  if (Mock.charset_convert_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.charset_convert_FinalReturn;
    Mock.charset_convert_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.charset_convert_CallbackFunctionPointer != NULL)
  {
    return Mock.charset_convert_CallbackFunctionPointer(fromcode, tocode, from, fromlen, to, tolen, Mock.charset_convert_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'charset_convert' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_fromcode, fromcode, cmock_line, "Function 'charset_convert' called with unexpected value for argument 'fromcode'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_tocode, tocode, cmock_line, "Function 'charset_convert' called with unexpected value for argument 'tocode'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_from, from, cmock_line, "Function 'charset_convert' called with unexpected value for argument 'from'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_fromlen), (void*)(&fromlen), sizeof(size_t), cmock_line, "Function 'charset_convert' called with unexpected value for argument 'fromlen'.");
  }
  {
    if (cmock_call_instance->Expected_to == NULL)
      { UNITY_TEST_ASSERT_NULL(to, cmock_line, "Expected NULL. Function 'charset_convert' called with unexpected value for argument 'to'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_STRING_ARRAY(cmock_call_instance->Expected_to, to, 1, cmock_line, "Function 'charset_convert' called with unexpected value for argument 'to'."); }
  }
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_tolen), (void*)(tolen), sizeof(size_t), cmock_line, "Function 'charset_convert' called with unexpected value for argument 'tolen'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_charset_convert(CMOCK_charset_convert_CALL_INSTANCE* cmock_call_instance, const char* fromcode, const char* tocode, const char* from, size_t fromlen, char** to, size_t* tolen)
{
  cmock_call_instance->Expected_fromcode = (char*)fromcode;
  cmock_call_instance->Expected_tocode = (char*)tocode;
  cmock_call_instance->Expected_from = (char*)from;
  memcpy(&cmock_call_instance->Expected_fromlen, &fromlen, sizeof(size_t));
  memcpy(&cmock_call_instance->Expected_to, &to, sizeof(char**));
  cmock_call_instance->Expected_tolen = tolen;
}

void charset_convert_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_convert_CALL_INSTANCE));
  CMOCK_charset_convert_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_convert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_convert_CallInstance = CMock_Guts_MemChain(Mock.charset_convert_CallInstance, cmock_guts_index);
  Mock.charset_convert_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.charset_convert_IgnoreBool = (int)1;
}

void charset_convert_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* fromcode, const char* tocode, const char* from, size_t fromlen, char** to, size_t* tolen, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_charset_convert_CALL_INSTANCE));
  CMOCK_charset_convert_CALL_INSTANCE* cmock_call_instance = (CMOCK_charset_convert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.charset_convert_CallInstance = CMock_Guts_MemChain(Mock.charset_convert_CallInstance, cmock_guts_index);
  Mock.charset_convert_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_charset_convert(cmock_call_instance, fromcode, tocode, from, fromlen, to, tolen);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void charset_convert_StubWithCallback(CMOCK_charset_convert_CALLBACK Callback)
{
  Mock.charset_convert_CallbackFunctionPointer = Callback;
}

