/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockthreadlib.h"

typedef struct _CMOCK_threadlib_beginthread_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  error_code ReturnVal;
  THREAD_HANDLE* Expected_thread;
  cmock_threadlib_func_ptr1 Expected_callback;
  void* Expected_arg;

} CMOCK_threadlib_beginthread_CALL_INSTANCE;

static struct MockthreadlibInstance
{
  int threadlib_beginthread_IgnoreBool;
  error_code threadlib_beginthread_FinalReturn;
  CMOCK_threadlib_beginthread_CALLBACK threadlib_beginthread_CallbackFunctionPointer;
  int threadlib_beginthread_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE threadlib_beginthread_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockthreadlib_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.threadlib_beginthread_IgnoreBool)
    Mock.threadlib_beginthread_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.threadlib_beginthread_CallInstance, cmock_line, "Function 'threadlib_beginthread' called less times than expected.");
  if (Mock.threadlib_beginthread_CallbackFunctionPointer != NULL)
    Mock.threadlib_beginthread_CallInstance = CMOCK_GUTS_NONE;
}

void Mockthreadlib_Init(void)
{
  Mockthreadlib_Destroy();
}

void Mockthreadlib_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.threadlib_beginthread_CallbackFunctionPointer = NULL;
  Mock.threadlib_beginthread_CallbackCalls = 0;
}

error_code threadlib_beginthread(THREAD_HANDLE* thread, cmock_threadlib_func_ptr1 callback, void* arg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_threadlib_beginthread_CALL_INSTANCE* cmock_call_instance = (CMOCK_threadlib_beginthread_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.threadlib_beginthread_CallInstance);
  Mock.threadlib_beginthread_CallInstance = CMock_Guts_MemNext(Mock.threadlib_beginthread_CallInstance);
  if (Mock.threadlib_beginthread_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.threadlib_beginthread_FinalReturn;
    memcpy(&Mock.threadlib_beginthread_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(error_code));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.threadlib_beginthread_CallbackFunctionPointer != NULL)
  {
    return Mock.threadlib_beginthread_CallbackFunctionPointer(thread, callback, arg, Mock.threadlib_beginthread_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'threadlib_beginthread' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_thread), (void*)(thread), sizeof(THREAD_HANDLE), cmock_line, "Function 'threadlib_beginthread' called with unexpected value for argument 'thread'.");
  }
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_callback, callback, cmock_line, "Function 'threadlib_beginthread' called with unexpected value for argument 'callback'.");
  }
  {
    if (cmock_call_instance->Expected_arg == NULL)
      { UNITY_TEST_ASSERT_NULL(arg, cmock_line, "Expected NULL. Function 'threadlib_beginthread' called with unexpected value for argument 'arg'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_arg, arg, 1, cmock_line, "Function 'threadlib_beginthread' called with unexpected value for argument 'arg'."); }
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_threadlib_beginthread(CMOCK_threadlib_beginthread_CALL_INSTANCE* cmock_call_instance, THREAD_HANDLE* thread, cmock_threadlib_func_ptr1 callback, void* arg)
{
  cmock_call_instance->Expected_thread = thread;
  memcpy(&cmock_call_instance->Expected_callback, &callback, sizeof(cmock_threadlib_func_ptr1));
  cmock_call_instance->Expected_arg = arg;
}

void threadlib_beginthread_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_threadlib_beginthread_CALL_INSTANCE));
  CMOCK_threadlib_beginthread_CALL_INSTANCE* cmock_call_instance = (CMOCK_threadlib_beginthread_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.threadlib_beginthread_CallInstance = CMock_Guts_MemChain(Mock.threadlib_beginthread_CallInstance, cmock_guts_index);
  Mock.threadlib_beginthread_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.threadlib_beginthread_IgnoreBool = (int)1;
}

void threadlib_beginthread_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, THREAD_HANDLE* thread, cmock_threadlib_func_ptr1 callback, void* arg, error_code cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_threadlib_beginthread_CALL_INSTANCE));
  CMOCK_threadlib_beginthread_CALL_INSTANCE* cmock_call_instance = (CMOCK_threadlib_beginthread_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.threadlib_beginthread_CallInstance = CMock_Guts_MemChain(Mock.threadlib_beginthread_CallInstance, cmock_guts_index);
  Mock.threadlib_beginthread_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_threadlib_beginthread(cmock_call_instance, thread, callback, arg);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(error_code));
}

void threadlib_beginthread_StubWithCallback(CMOCK_threadlib_beginthread_CALLBACK Callback)
{
  Mock.threadlib_beginthread_CallbackFunctionPointer = Callback;
}

