/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTHREADLIB_H
#define _MOCKTHREADLIB_H

#include "threadlib.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockthreadlib_Init(void);
void Mockthreadlib_Destroy(void);
void Mockthreadlib_Verify(void);


typedef void(*cmock_threadlib_func_ptr1)(void*);


#define threadlib_beginthread_IgnoreAndReturn(cmock_retval) threadlib_beginthread_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void threadlib_beginthread_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define threadlib_beginthread_ExpectAndReturn(thread, callback, arg, cmock_retval) threadlib_beginthread_CMockExpectAndReturn(__LINE__, thread, callback, arg, cmock_retval)
void threadlib_beginthread_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, THREAD_HANDLE* thread, cmock_threadlib_func_ptr1 callback, void* arg, error_code cmock_to_return);
typedef error_code (* CMOCK_threadlib_beginthread_CALLBACK)(THREAD_HANDLE* thread, cmock_threadlib_func_ptr1 callback, void* arg, int cmock_num_calls);
void threadlib_beginthread_StubWithCallback(CMOCK_threadlib_beginthread_CALLBACK Callback);

#endif
