/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCBUF2_H
#define _MOCKCBUF2_H

#include "cbuf2.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockcbuf2_Init(void);
void Mockcbuf2_Destroy(void);
void Mockcbuf2_Verify(void);




#define cbuf2_init_IgnoreAndReturn(cmock_retval) cbuf2_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_init_ExpectAndReturn(cbuf2, content_type, have_relay, chunk_size, num_chunks, cmock_retval) cbuf2_init_CMockExpectAndReturn(__LINE__, cbuf2, content_type, have_relay, chunk_size, num_chunks, cmock_retval)
void cbuf2_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, int content_type, int have_relay, unsigned long chunk_size, unsigned long num_chunks, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_init_CALLBACK)(CBUF2* cbuf2, int content_type, int have_relay, unsigned long chunk_size, unsigned long num_chunks, int cmock_num_calls);
void cbuf2_init_StubWithCallback(CMOCK_cbuf2_init_CALLBACK Callback);
#define cbuf2_destroy_Ignore() cbuf2_destroy_CMockIgnore()
void cbuf2_destroy_CMockIgnore(void);
#define cbuf2_destroy_Expect(buffer) cbuf2_destroy_CMockExpect(__LINE__, buffer)
void cbuf2_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line, CBUF2* buffer);
typedef void (* CMOCK_cbuf2_destroy_CALLBACK)(CBUF2* buffer, int cmock_num_calls);
void cbuf2_destroy_StubWithCallback(CMOCK_cbuf2_destroy_CALLBACK Callback);
#define cbuf2_extract_IgnoreAndReturn(cmock_retval) cbuf2_extract_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_extract_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_extract_ExpectAndReturn(rmi, cbuf2, data, count, curr_song, cmock_retval) cbuf2_extract_CMockExpectAndReturn(__LINE__, rmi, cbuf2, data, count, curr_song, cmock_retval)
void cbuf2_extract_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, char* data, u_long count, u_long* curr_song, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_extract_CALLBACK)(RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, char* data, u_long count, u_long* curr_song, int cmock_num_calls);
void cbuf2_extract_StubWithCallback(CMOCK_cbuf2_extract_CALLBACK Callback);
#define cbuf2_peek_IgnoreAndReturn(cmock_retval) cbuf2_peek_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_peek_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_peek_ExpectAndReturn(buffer, items, count, cmock_retval) cbuf2_peek_CMockExpectAndReturn(__LINE__, buffer, items, count, cmock_retval)
void cbuf2_peek_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* buffer, char* items, u_long count, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_peek_CALLBACK)(CBUF2* buffer, char* items, u_long count, int cmock_num_calls);
void cbuf2_peek_StubWithCallback(CMOCK_cbuf2_peek_CALLBACK Callback);
#define cbuf2_insert_chunk_IgnoreAndReturn(cmock_retval) cbuf2_insert_chunk_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_insert_chunk_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_insert_chunk_ExpectAndReturn(rmi, cbuf2, data, count, content_type, ti, cmock_retval) cbuf2_insert_chunk_CMockExpectAndReturn(__LINE__, rmi, cbuf2, data, count, content_type, ti, cmock_retval)
void cbuf2_insert_chunk_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, const char* data, u_long count, int content_type, TRACK_INFO* ti, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_insert_chunk_CALLBACK)(RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, const char* data, u_long count, int content_type, TRACK_INFO* ti, int cmock_num_calls);
void cbuf2_insert_chunk_StubWithCallback(CMOCK_cbuf2_insert_chunk_CALLBACK Callback);
#define cbuf2_fastforward_IgnoreAndReturn(cmock_retval) cbuf2_fastforward_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_fastforward_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_fastforward_ExpectAndReturn(buffer, count, cmock_retval) cbuf2_fastforward_CMockExpectAndReturn(__LINE__, buffer, count, cmock_retval)
void cbuf2_fastforward_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* buffer, u_long count, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_fastforward_CALLBACK)(CBUF2* buffer, u_long count, int cmock_num_calls);
void cbuf2_fastforward_StubWithCallback(CMOCK_cbuf2_fastforward_CALLBACK Callback);
#define cbuf2_peek_rgn_IgnoreAndReturn(cmock_retval) cbuf2_peek_rgn_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_peek_rgn_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_peek_rgn_ExpectAndReturn(buffer, out_buf, start, length, cmock_retval) cbuf2_peek_rgn_CMockExpectAndReturn(__LINE__, buffer, out_buf, start, length, cmock_retval)
void cbuf2_peek_rgn_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* buffer, char* out_buf, u_long start, u_long length, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_peek_rgn_CALLBACK)(CBUF2* buffer, char* out_buf, u_long start, u_long length, int cmock_num_calls);
void cbuf2_peek_rgn_StubWithCallback(CMOCK_cbuf2_peek_rgn_CALLBACK Callback);
#define cbuf2_get_free_IgnoreAndReturn(cmock_retval) cbuf2_get_free_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_get_free_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, u_long cmock_to_return);
#define cbuf2_get_free_ExpectAndReturn(buffer, cmock_retval) cbuf2_get_free_CMockExpectAndReturn(__LINE__, buffer, cmock_retval)
void cbuf2_get_free_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* buffer, u_long cmock_to_return);
typedef u_long (* CMOCK_cbuf2_get_free_CALLBACK)(CBUF2* buffer, int cmock_num_calls);
void cbuf2_get_free_StubWithCallback(CMOCK_cbuf2_get_free_CALLBACK Callback);
#define cbuf2_get_free_tail_IgnoreAndReturn(cmock_retval) cbuf2_get_free_tail_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_get_free_tail_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, u_long cmock_to_return);
#define cbuf2_get_free_tail_ExpectAndReturn(cbuf2, cmock_retval) cbuf2_get_free_tail_CMockExpectAndReturn(__LINE__, cbuf2, cmock_retval)
void cbuf2_get_free_tail_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, u_long cmock_to_return);
typedef u_long (* CMOCK_cbuf2_get_free_tail_CALLBACK)(CBUF2* cbuf2, int cmock_num_calls);
void cbuf2_get_free_tail_StubWithCallback(CMOCK_cbuf2_get_free_tail_CALLBACK Callback);
#define cbuf2_write_index_IgnoreAndReturn(cmock_retval) cbuf2_write_index_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_write_index_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, u_long cmock_to_return);
#define cbuf2_write_index_ExpectAndReturn(cbuf2, cmock_retval) cbuf2_write_index_CMockExpectAndReturn(__LINE__, cbuf2, cmock_retval)
void cbuf2_write_index_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, u_long cmock_to_return);
typedef u_long (* CMOCK_cbuf2_write_index_CALLBACK)(CBUF2* cbuf2, int cmock_num_calls);
void cbuf2_write_index_StubWithCallback(CMOCK_cbuf2_write_index_CALLBACK Callback);
#define cbuf2_set_next_song_Ignore() cbuf2_set_next_song_CMockIgnore()
void cbuf2_set_next_song_CMockIgnore(void);
#define cbuf2_set_next_song_Expect(cbuf2, pos) cbuf2_set_next_song_CMockExpect(__LINE__, cbuf2, pos)
void cbuf2_set_next_song_CMockExpect(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, u_long pos);
typedef void (* CMOCK_cbuf2_set_next_song_CALLBACK)(CBUF2* cbuf2, u_long pos, int cmock_num_calls);
void cbuf2_set_next_song_StubWithCallback(CMOCK_cbuf2_set_next_song_CALLBACK Callback);
#define cbuf2_init_relay_entry_IgnoreAndReturn(cmock_retval) cbuf2_init_relay_entry_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_init_relay_entry_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_init_relay_entry_ExpectAndReturn(cbuf2, ptr, burst_request, cmock_retval) cbuf2_init_relay_entry_CMockExpectAndReturn(__LINE__, cbuf2, ptr, burst_request, cmock_retval)
void cbuf2_init_relay_entry_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, RELAY_LIST* ptr, u_long burst_request, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_init_relay_entry_CALLBACK)(CBUF2* cbuf2, RELAY_LIST* ptr, u_long burst_request, int cmock_num_calls);
void cbuf2_init_relay_entry_StubWithCallback(CMOCK_cbuf2_init_relay_entry_CALLBACK Callback);
#define cbuf2_ogg_peek_song_IgnoreAndReturn(cmock_retval) cbuf2_ogg_peek_song_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_ogg_peek_song_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_ogg_peek_song_ExpectAndReturn(cbuf2, out_buf, buf_size, amt_filled, eos, cmock_retval) cbuf2_ogg_peek_song_CMockExpectAndReturn(__LINE__, cbuf2, out_buf, buf_size, amt_filled, eos, cmock_retval)
void cbuf2_ogg_peek_song_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, char* out_buf, unsigned long buf_size, unsigned long* amt_filled, int* eos, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_ogg_peek_song_CALLBACK)(CBUF2* cbuf2, char* out_buf, unsigned long buf_size, unsigned long* amt_filled, int* eos, int cmock_num_calls);
void cbuf2_ogg_peek_song_StubWithCallback(CMOCK_cbuf2_ogg_peek_song_CALLBACK Callback);
#define cbuf2_extract_relay_IgnoreAndReturn(cmock_retval) cbuf2_extract_relay_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_extract_relay_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_extract_relay_ExpectAndReturn(cbuf2, data, pos, len, icy_metadata, cmock_retval) cbuf2_extract_relay_CMockExpectAndReturn(__LINE__, cbuf2, data, pos, len, icy_metadata, cmock_retval)
void cbuf2_extract_relay_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CBUF2* cbuf2, char* data, u_long* pos, u_long* len, int icy_metadata, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_extract_relay_CALLBACK)(CBUF2* cbuf2, char* data, u_long* pos, u_long* len, int icy_metadata, int cmock_num_calls);
void cbuf2_extract_relay_StubWithCallback(CMOCK_cbuf2_extract_relay_CALLBACK Callback);
#define cbuf2_advance_ogg_IgnoreAndReturn(cmock_retval) cbuf2_advance_ogg_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void cbuf2_advance_ogg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define cbuf2_advance_ogg_ExpectAndReturn(rmi, cbuf2, requested_free_size, cmock_retval) cbuf2_advance_ogg_CMockExpectAndReturn(__LINE__, rmi, cbuf2, requested_free_size, cmock_retval)
void cbuf2_advance_ogg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, int requested_free_size, error_code cmock_to_return);
typedef error_code (* CMOCK_cbuf2_advance_ogg_CALLBACK)(RIP_MANAGER_INFO* rmi, CBUF2* cbuf2, int requested_free_size, int cmock_num_calls);
void cbuf2_advance_ogg_StubWithCallback(CMOCK_cbuf2_advance_ogg_CALLBACK Callback);

#endif
