/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFILELIB_H
#define _MOCKFILELIB_H

#include "filelib.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockfilelib_Init(void);
void Mockfilelib_Destroy(void);
void Mockfilelib_Verify(void);




#define filelib_init_IgnoreAndReturn(cmock_retval) filelib_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void filelib_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define filelib_init_ExpectAndReturn(rmi, do_individual_tracks, do_count, count_start, keep_incomplete, do_show_file, content_type, output_directory, output_pattern, showfile_pattern, get_separate_dirs, get_date_stamp, icy_name, cmock_retval) filelib_init_CMockExpectAndReturn(__LINE__, rmi, do_individual_tracks, do_count, count_start, keep_incomplete, do_show_file, content_type, output_directory, output_pattern, showfile_pattern, get_separate_dirs, get_date_stamp, icy_name, cmock_retval)
void filelib_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, BOOL do_individual_tracks, BOOL do_count, int count_start, BOOL keep_incomplete, BOOL do_show_file, int content_type, char* output_directory, char* output_pattern, char* showfile_pattern, int get_separate_dirs, int get_date_stamp, char* icy_name, error_code cmock_to_return);
typedef error_code (* CMOCK_filelib_init_CALLBACK)(RIP_MANAGER_INFO* rmi, BOOL do_individual_tracks, BOOL do_count, int count_start, BOOL keep_incomplete, BOOL do_show_file, int content_type, char* output_directory, char* output_pattern, char* showfile_pattern, int get_separate_dirs, int get_date_stamp, char* icy_name, int cmock_num_calls);
void filelib_init_StubWithCallback(CMOCK_filelib_init_CALLBACK Callback);
#define filelib_start_IgnoreAndReturn(cmock_retval) filelib_start_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void filelib_start_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define filelib_start_ExpectAndReturn(rmi, ti, cmock_retval) filelib_start_CMockExpectAndReturn(__LINE__, rmi, ti, cmock_retval)
void filelib_start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, error_code cmock_to_return);
typedef error_code (* CMOCK_filelib_start_CALLBACK)(RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, int cmock_num_calls);
void filelib_start_StubWithCallback(CMOCK_filelib_start_CALLBACK Callback);
#define filelib_write_track_IgnoreAndReturn(cmock_retval) filelib_write_track_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void filelib_write_track_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define filelib_write_track_ExpectAndReturn(rmi, buf, size, cmock_retval) filelib_write_track_CMockExpectAndReturn(__LINE__, rmi, buf, size, cmock_retval)
void filelib_write_track_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, char* buf, u_long size, error_code cmock_to_return);
typedef error_code (* CMOCK_filelib_write_track_CALLBACK)(RIP_MANAGER_INFO* rmi, char* buf, u_long size, int cmock_num_calls);
void filelib_write_track_StubWithCallback(CMOCK_filelib_write_track_CALLBACK Callback);
#define filelib_write_show_IgnoreAndReturn(cmock_retval) filelib_write_show_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void filelib_write_show_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define filelib_write_show_ExpectAndReturn(rmi, buf, size, cmock_retval) filelib_write_show_CMockExpectAndReturn(__LINE__, rmi, buf, size, cmock_retval)
void filelib_write_show_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, char* buf, u_long size, error_code cmock_to_return);
typedef error_code (* CMOCK_filelib_write_show_CALLBACK)(RIP_MANAGER_INFO* rmi, char* buf, u_long size, int cmock_num_calls);
void filelib_write_show_StubWithCallback(CMOCK_filelib_write_show_CALLBACK Callback);
#define filelib_write_cue_IgnoreAndReturn(cmock_retval) filelib_write_cue_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void filelib_write_cue_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define filelib_write_cue_ExpectAndReturn(rmi, ti, secs, cmock_retval) filelib_write_cue_CMockExpectAndReturn(__LINE__, rmi, ti, secs, cmock_retval)
void filelib_write_cue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, int secs, error_code cmock_to_return);
typedef error_code (* CMOCK_filelib_write_cue_CALLBACK)(RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, int secs, int cmock_num_calls);
void filelib_write_cue_StubWithCallback(CMOCK_filelib_write_cue_CALLBACK Callback);
#define filelib_end_IgnoreAndReturn(cmock_retval) filelib_end_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void filelib_end_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define filelib_end_ExpectAndReturn(rmi, ti, overwrite, truncate_dup, fullpath, cmock_retval) filelib_end_CMockExpectAndReturn(__LINE__, rmi, ti, overwrite, truncate_dup, fullpath, cmock_retval)
void filelib_end_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, enum OverwriteOpt overwrite, BOOL truncate_dup, mchar* fullpath, error_code cmock_to_return);
typedef error_code (* CMOCK_filelib_end_CALLBACK)(RIP_MANAGER_INFO* rmi, TRACK_INFO* ti, enum OverwriteOpt overwrite, BOOL truncate_dup, mchar* fullpath, int cmock_num_calls);
void filelib_end_StubWithCallback(CMOCK_filelib_end_CALLBACK Callback);
#define filelib_shutdown_Ignore() filelib_shutdown_CMockIgnore()
void filelib_shutdown_CMockIgnore(void);
#define filelib_shutdown_Expect(rmi) filelib_shutdown_CMockExpect(__LINE__, rmi)
void filelib_shutdown_CMockExpect(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi);
typedef void (* CMOCK_filelib_shutdown_CALLBACK)(RIP_MANAGER_INFO* rmi, int cmock_num_calls);
void filelib_shutdown_StubWithCallback(CMOCK_filelib_shutdown_CALLBACK Callback);

#endif
