/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockutf8.h"

typedef struct _CMOCK_convert_set_charset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_charset;

} CMOCK_convert_set_charset_CALL_INSTANCE;

typedef struct _CMOCK_utf8_encode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  char* Expected_from;
  char** Expected_to;

} CMOCK_utf8_encode_CALL_INSTANCE;

typedef struct _CMOCK_utf8_decode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  char* Expected_from;
  char** Expected_to;

} CMOCK_utf8_decode_CALL_INSTANCE;

static struct Mockutf8Instance
{
  int convert_set_charset_IgnoreBool;
  CMOCK_convert_set_charset_CALLBACK convert_set_charset_CallbackFunctionPointer;
  int convert_set_charset_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE convert_set_charset_CallInstance;
  int utf8_encode_IgnoreBool;
  int utf8_encode_FinalReturn;
  CMOCK_utf8_encode_CALLBACK utf8_encode_CallbackFunctionPointer;
  int utf8_encode_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE utf8_encode_CallInstance;
  int utf8_decode_IgnoreBool;
  int utf8_decode_FinalReturn;
  CMOCK_utf8_decode_CALLBACK utf8_decode_CallbackFunctionPointer;
  int utf8_decode_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE utf8_decode_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockutf8_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.convert_set_charset_IgnoreBool)
    Mock.convert_set_charset_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.convert_set_charset_CallInstance, cmock_line, "Function 'convert_set_charset' called less times than expected.");
  if (Mock.convert_set_charset_CallbackFunctionPointer != NULL)
    Mock.convert_set_charset_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.utf8_encode_IgnoreBool)
    Mock.utf8_encode_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.utf8_encode_CallInstance, cmock_line, "Function 'utf8_encode' called less times than expected.");
  if (Mock.utf8_encode_CallbackFunctionPointer != NULL)
    Mock.utf8_encode_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.utf8_decode_IgnoreBool)
    Mock.utf8_decode_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.utf8_decode_CallInstance, cmock_line, "Function 'utf8_decode' called less times than expected.");
  if (Mock.utf8_decode_CallbackFunctionPointer != NULL)
    Mock.utf8_decode_CallInstance = CMOCK_GUTS_NONE;
}

void Mockutf8_Init(void)
{
  Mockutf8_Destroy();
}

void Mockutf8_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.convert_set_charset_CallbackFunctionPointer = NULL;
  Mock.convert_set_charset_CallbackCalls = 0;
  Mock.utf8_encode_CallbackFunctionPointer = NULL;
  Mock.utf8_encode_CallbackCalls = 0;
  Mock.utf8_decode_CallbackFunctionPointer = NULL;
  Mock.utf8_decode_CallbackCalls = 0;
}

void convert_set_charset(const char* charset)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_convert_set_charset_CALL_INSTANCE* cmock_call_instance = (CMOCK_convert_set_charset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.convert_set_charset_CallInstance);
  Mock.convert_set_charset_CallInstance = CMock_Guts_MemNext(Mock.convert_set_charset_CallInstance);
  if (Mock.convert_set_charset_IgnoreBool)
  {
    return;
  }
  if (Mock.convert_set_charset_CallbackFunctionPointer != NULL)
  {
    Mock.convert_set_charset_CallbackFunctionPointer(charset, Mock.convert_set_charset_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'convert_set_charset' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_charset, charset, cmock_line, "Function 'convert_set_charset' called with unexpected value for argument 'charset'.");
  }
}

void CMockExpectParameters_convert_set_charset(CMOCK_convert_set_charset_CALL_INSTANCE* cmock_call_instance, const char* charset)
{
  cmock_call_instance->Expected_charset = (char*)charset;
}

void convert_set_charset_CMockIgnore(void)
{
  Mock.convert_set_charset_IgnoreBool = (int)1;
}

void convert_set_charset_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* charset)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_convert_set_charset_CALL_INSTANCE));
  CMOCK_convert_set_charset_CALL_INSTANCE* cmock_call_instance = (CMOCK_convert_set_charset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.convert_set_charset_CallInstance = CMock_Guts_MemChain(Mock.convert_set_charset_CallInstance, cmock_guts_index);
  Mock.convert_set_charset_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_convert_set_charset(cmock_call_instance, charset);
}

void convert_set_charset_StubWithCallback(CMOCK_convert_set_charset_CALLBACK Callback)
{
  Mock.convert_set_charset_CallbackFunctionPointer = Callback;
}

int utf8_encode(const char* from, char** to)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_utf8_encode_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_encode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.utf8_encode_CallInstance);
  Mock.utf8_encode_CallInstance = CMock_Guts_MemNext(Mock.utf8_encode_CallInstance);
  if (Mock.utf8_encode_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.utf8_encode_FinalReturn;
    Mock.utf8_encode_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.utf8_encode_CallbackFunctionPointer != NULL)
  {
    return Mock.utf8_encode_CallbackFunctionPointer(from, to, Mock.utf8_encode_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'utf8_encode' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_from, from, cmock_line, "Function 'utf8_encode' called with unexpected value for argument 'from'.");
  }
  {
    if (cmock_call_instance->Expected_to == NULL)
      { UNITY_TEST_ASSERT_NULL(to, cmock_line, "Expected NULL. Function 'utf8_encode' called with unexpected value for argument 'to'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_STRING_ARRAY(cmock_call_instance->Expected_to, to, 1, cmock_line, "Function 'utf8_encode' called with unexpected value for argument 'to'."); }
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_utf8_encode(CMOCK_utf8_encode_CALL_INSTANCE* cmock_call_instance, const char* from, char** to)
{
  cmock_call_instance->Expected_from = (char*)from;
  memcpy(&cmock_call_instance->Expected_to, &to, sizeof(char**));
}

void utf8_encode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_utf8_encode_CALL_INSTANCE));
  CMOCK_utf8_encode_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_encode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.utf8_encode_CallInstance = CMock_Guts_MemChain(Mock.utf8_encode_CallInstance, cmock_guts_index);
  Mock.utf8_encode_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.utf8_encode_IgnoreBool = (int)1;
}

void utf8_encode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* from, char** to, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_utf8_encode_CALL_INSTANCE));
  CMOCK_utf8_encode_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_encode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.utf8_encode_CallInstance = CMock_Guts_MemChain(Mock.utf8_encode_CallInstance, cmock_guts_index);
  Mock.utf8_encode_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_utf8_encode(cmock_call_instance, from, to);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void utf8_encode_StubWithCallback(CMOCK_utf8_encode_CALLBACK Callback)
{
  Mock.utf8_encode_CallbackFunctionPointer = Callback;
}

int utf8_decode(const char* from, char** to)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_utf8_decode_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_decode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.utf8_decode_CallInstance);
  Mock.utf8_decode_CallInstance = CMock_Guts_MemNext(Mock.utf8_decode_CallInstance);
  if (Mock.utf8_decode_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.utf8_decode_FinalReturn;
    Mock.utf8_decode_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.utf8_decode_CallbackFunctionPointer != NULL)
  {
    return Mock.utf8_decode_CallbackFunctionPointer(from, to, Mock.utf8_decode_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'utf8_decode' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_from, from, cmock_line, "Function 'utf8_decode' called with unexpected value for argument 'from'.");
  }
  {
    if (cmock_call_instance->Expected_to == NULL)
      { UNITY_TEST_ASSERT_NULL(to, cmock_line, "Expected NULL. Function 'utf8_decode' called with unexpected value for argument 'to'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_STRING_ARRAY(cmock_call_instance->Expected_to, to, 1, cmock_line, "Function 'utf8_decode' called with unexpected value for argument 'to'."); }
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_utf8_decode(CMOCK_utf8_decode_CALL_INSTANCE* cmock_call_instance, const char* from, char** to)
{
  cmock_call_instance->Expected_from = (char*)from;
  memcpy(&cmock_call_instance->Expected_to, &to, sizeof(char**));
}

void utf8_decode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_utf8_decode_CALL_INSTANCE));
  CMOCK_utf8_decode_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_decode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.utf8_decode_CallInstance = CMock_Guts_MemChain(Mock.utf8_decode_CallInstance, cmock_guts_index);
  Mock.utf8_decode_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.utf8_decode_IgnoreBool = (int)1;
}

void utf8_decode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* from, char** to, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_utf8_decode_CALL_INSTANCE));
  CMOCK_utf8_decode_CALL_INSTANCE* cmock_call_instance = (CMOCK_utf8_decode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.utf8_decode_CallInstance = CMock_Guts_MemChain(Mock.utf8_decode_CallInstance, cmock_guts_index);
  Mock.utf8_decode_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_utf8_decode(cmock_call_instance, from, to);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void utf8_decode_StubWithCallback(CMOCK_utf8_decode_CALLBACK Callback)
{
  Mock.utf8_decode_CallbackFunctionPointer = Callback;
}

