/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKHTTPS_H
#define _MOCKHTTPS_H

#include "https.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockhttps_Init(void);
void Mockhttps_Destroy(void);
void Mockhttps_Verify(void);




#define https_init_Ignore() https_init_CMockIgnore()
void https_init_CMockIgnore(void);
#define https_init_Expect() https_init_CMockExpect(__LINE__)
void https_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_https_init_CALLBACK)(int cmock_num_calls);
void https_init_StubWithCallback(CMOCK_https_init_CALLBACK Callback);
#define https_sc_connect_IgnoreAndReturn(cmock_retval) https_sc_connect_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void https_sc_connect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define https_sc_connect_ExpectAndReturn(rmi, data, url, proxyurl, info, useragent, if_name, cmock_retval) https_sc_connect_CMockExpectAndReturn(__LINE__, rmi, data, url, proxyurl, info, useragent, if_name, cmock_retval)
void https_sc_connect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, HTTPS_DATA** data, const char* url, const char* proxyurl, SR_HTTP_HEADER* info, const char* useragent, const char* if_name, error_code cmock_to_return);
typedef error_code (* CMOCK_https_sc_connect_CALLBACK)(RIP_MANAGER_INFO* rmi, HTTPS_DATA** data, const char* url, const char* proxyurl, SR_HTTP_HEADER* info, const char* useragent, const char* if_name, int cmock_num_calls);
void https_sc_connect_StubWithCallback(CMOCK_https_sc_connect_CALLBACK Callback);
#define https_get_sc_header_IgnoreAndReturn(cmock_retval) https_get_sc_header_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void https_get_sc_header_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, error_code cmock_to_return);
#define https_get_sc_header_ExpectAndReturn(rmi, data, url, info, cmock_retval) https_get_sc_header_CMockExpectAndReturn(__LINE__, rmi, data, url, info, cmock_retval)
void https_get_sc_header_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RIP_MANAGER_INFO* rmi, HTTPS_DATA* data, const char* url, SR_HTTP_HEADER* info, error_code cmock_to_return);
typedef error_code (* CMOCK_https_get_sc_header_CALLBACK)(RIP_MANAGER_INFO* rmi, HTTPS_DATA* data, const char* url, SR_HTTP_HEADER* info, int cmock_num_calls);
void https_get_sc_header_StubWithCallback(CMOCK_https_get_sc_header_CALLBACK Callback);
#define https_sc_read_line_IgnoreAndReturn(cmock_retval) https_sc_read_line_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void https_sc_read_line_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define https_sc_read_line_ExpectAndReturn(data, buffer, size, cmock_retval) https_sc_read_line_CMockExpectAndReturn(__LINE__, data, buffer, size, cmock_retval)
void https_sc_read_line_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HTTPS_DATA* data, char* buffer, size_t size, int cmock_to_return);
typedef int (* CMOCK_https_sc_read_line_CALLBACK)(HTTPS_DATA* data, char* buffer, size_t size, int cmock_num_calls);
void https_sc_read_line_StubWithCallback(CMOCK_https_sc_read_line_CALLBACK Callback);
#define https_sc_read_data_IgnoreAndReturn(cmock_retval) https_sc_read_data_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void https_sc_read_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define https_sc_read_data_ExpectAndReturn(data, buffer, size, cmock_retval) https_sc_read_data_CMockExpectAndReturn(__LINE__, data, buffer, size, cmock_retval)
void https_sc_read_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HTTPS_DATA* data, char* buffer, size_t size, int cmock_to_return);
typedef int (* CMOCK_https_sc_read_data_CALLBACK)(HTTPS_DATA* data, char* buffer, size_t size, int cmock_num_calls);
void https_sc_read_data_StubWithCallback(CMOCK_https_sc_read_data_CALLBACK Callback);
#define https_sc_close_Ignore() https_sc_close_CMockIgnore()
void https_sc_close_CMockIgnore(void);
#define https_sc_close_Expect(data) https_sc_close_CMockExpect(__LINE__, data)
void https_sc_close_CMockExpect(UNITY_LINE_TYPE cmock_line, HTTPS_DATA* data);
typedef void (* CMOCK_https_sc_close_CALLBACK)(HTTPS_DATA* data, int cmock_num_calls);
void https_sc_close_StubWithCallback(CMOCK_https_sc_close_CALLBACK Callback);

#endif
